### ISSUE TITLE
fs module missing error in nextjs

### ISSUE THREAD

**Issue by milindgoel15** [kelektiv/node.bcrypt.js#1008]
* What went wrong?
Trying to use bcrypt in nextjs and calling bcrypt throws module not found error. Commenting/removing the bcrypt code resolves the issue.

```console
Import trace for requested module:
./node_modules/@mapbox/node-pre-gyp/lib/ sync ^\.\/.*$
./node_modules/@mapbox/node-pre-gyp/lib/node-pre-gyp.js
./node_modules/bcrypt/bcrypt.js
./pages/test.tsx
- wait compiling...
- error ./node_modules/@mapbox/node-pre-gyp/lib/clean.js:8:0
Module not found: Can't resolve 'fs'

https://nextjs.org/docs/messages/module-not-found
```

* What did you expect to happen?
No error is thrown

* Which version of nodejs and OS?
Nodejs: v20.9.0
Windows: 11 22h2

* Steps to reproduce:
1. Create fresh nextjs project
2. Install bcrypt
3. Add below code
4. Throws module not found on that route where this code is placed.

Sample nextjs page code:

<details>
<summary>code</summary>

```tsx
import React from "react";
import bcrypt from "bcrypt";

let Test = () => {
	const salt = bcrypt.genSaltSync(10);

	return (
		<>
			<p>hello world</p>
		</>
	);
};

export default Test;
```

</details>

**Comment by recrsn** [comment]
bcrypt is a native module and does not work in the browser. Use bcryptjs instead

It will work on server components with "use server" but you will need to disable bundling it.
