### ISSUE TITLE
Segmentation fault on bcrypt.hash call

### ISSUE THREAD

**Issue by jankvapil** [kelektiv/node.bcrypt.js#1015]
![image](https://github.com/kelektiv/node.bcrypt.js/assets/36538560/8afa95b1-c322-45aa-a551-ee47bdc89ab0)

running in docker image: node:21-alpine, interpret Node v21.4.0.

**Comment by recrsn** [comment]
Reinstall bcyrpt inside the docker container. You probably have glibc compiled binaries inside alpine (musl) environment
