### ISSUE TITLE
No matching version found for nvm@0.38.0

### ISSUE THREAD

**Issue by FaixyX** [kelektiv/node.bcrypt.js#1016]
### **OS and Node Version**
Ubuntu Ubuntu 20.04.6 LTS 64bit
Node Version: v20.10.0

### **Command:**
npm install bcrypt

### **Output:**
muhammad@faizan:~/Downloads/Mern/backend$ npm install bcrypt
npm ERR! code ETARGET
npm ERR! notarget No matching version found for nvm@0.38.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in: /home/muhammad/.npm/_logs/2023-12-06T14_47_14_715Z-debug-0.log

### **Log file:**
0 verbose cli /home/muhammad/.nvm/versions/node/v20.10.0/bin/node /home/muhammad/.nvm/versions/node/v20.10.0/bin/npm
1 info using npm@10.2.4
2 info using node@v20.10.0
3 timing npm:load:whichnode Completed in 18ms
4 timing config:load:defaults Completed in 3ms
5 timing config:load:file:/home/muhammad/.nvm/versions/node/v20.10.0/lib/node_modules/npm/npmrc Completed in 21ms
6 timing config:load:builtin Completed in 23ms
7 timing config:load:cli Completed in 3ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/home/muhammad/Downloads/Mern/backend/.npmrc Completed in 0ms
10 timing config:load:project Completed in 25ms
11 timing config:load:file:/home/muhammad/.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/home/muhammad/.nvm/versions/node/v20.10.0/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 1ms
16 timing config:load Completed in 59ms
17 timing npm:load:configload Completed in 59ms
18 timing config:load:flatten Completed in 5ms
19 timing npm:load:mkdirpcache Completed in 12ms
20 timing npm:load:mkdirplogs Completed in 4ms
21 verbose title npm install bcrypt
22 verbose argv "install" "bcrypt"
23 timing npm:load:setTitle Completed in 1ms
24 timing npm:load:display Completed in 1ms
25 verbose logfile logs-max:10 dir:/home/muhammad/.npm/_logs/2023-12-06T14_47_14_715Z-
26 verbose logfile /home/muhammad/.npm/_logs/2023-12-06T14_47_14_715Z-debug-0.log
27 timing npm:load:logFile Completed in 11ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 146ms
31 timing arborist:ctor Completed in 1ms
32 silly logfile start cleaning logs, removing 1 files
33 silly logfile done cleaning log files
34 timing arborist:ctor Completed in 0ms
35 timing idealTree:init Completed in 381ms
36 timing idealTree:userRequests Completed in 1ms
37 silly idealTree buildDeps
38 silly fetch manifest nvm@0.38.0
39 http fetch GET 200 https://registry.npmjs.org/nvm 1962ms (cache revalidated)
40 silly fetch manifest bcrypt@*
41 http fetch GET 200 https://registry.npmjs.org/bcrypt 14ms (cache hit)
42 silly placeDep ROOT bcrypt@5.1.1 OK for: workoutbuddy@1.0.0 want: *
43 silly fetch manifest @mapbox/node-pre-gyp@^1.0.11
44 silly fetch manifest node-addon-api@^5.0.0
45 silly placeDep ROOT nvm@ OK for: workoutbuddy@1.0.0 want: 0.38.0
46 http fetch GET 200 https://registry.npmjs.org/@mapbox%2fnode-pre-gyp 13ms (cache hit)
47 http fetch GET 200 https://registry.npmjs.org/node-addon-api 322ms (cache revalidated)
48 timing idealTree:#root Completed in 2337ms
49 silly placeDep ROOT @mapbox/node-pre-gyp@1.0.11 OK for: bcrypt@5.1.1 want: ^1.0.11
50 silly fetch manifest detect-libc@^2.0.0
51 silly fetch manifest https-proxy-agent@^5.0.0
52 silly fetch manifest make-dir@^3.1.0
53 silly fetch manifest node-fetch@^2.6.7
54 silly fetch manifest nopt@^5.0.0
55 silly fetch manifest npmlog@^5.0.1
56 silly fetch manifest rimraf@^3.0.2
57 silly fetch manifest tar@^6.1.11
58 silly placeDep ROOT node-addon-api@5.1.0 OK for: bcrypt@5.1.1 want: ^5.0.0
59 http fetch GET 200 https://registry.npmjs.org/detect-libc 85ms (cache hit)
60 http fetch GET 200 https://registry.npmjs.org/https-proxy-agent 83ms (cache hit)
61 http fetch GET 200 https://registry.npmjs.org/make-dir 83ms (cache hit)
62 http fetch GET 200 https://registry.npmjs.org/node-fetch 81ms (cache hit)
63 http fetch GET 200 https://registry.npmjs.org/tar 70ms (cache hit)
64 http fetch GET 200 https://registry.npmjs.org/nopt 86ms (cache hit)
65 http fetch GET 200 https://registry.npmjs.org/rimraf 79ms (cache hit)
66 http fetch GET 200 https://registry.npmjs.org/npmlog 86ms (cache hit)
67 timing idealTree:node_modules/bcrypt Completed in 121ms
68 silly fetch manifest encoding@^0.1.0
69 http fetch GET 200 https://registry.npmjs.org/encoding 6ms (cache hit)
70 silly placeDep ROOT detect-libc@2.0.2 OK for: @mapbox/node-pre-gyp@1.0.11 want: ^2.0.0
71 silly placeDep ROOT https-proxy-agent@5.0.1 OK for: @mapbox/node-pre-gyp@1.0.11 want: ^5.0.0
72 silly fetch manifest agent-base@6
73 silly fetch manifest debug@4
74 silly placeDep ROOT make-dir@3.1.0 OK for: @mapbox/node-pre-gyp@1.0.11 want: ^3.1.0
75 silly fetch manifest semver@^6.0.0
76 silly placeDep ROOT node-fetch@2.7.0 OK for: @mapbox/node-pre-gyp@1.0.11 want: ^2.6.7
77 silly fetch manifest whatwg-url@^5.0.0
78 silly placeDep node_modules/@mapbox/node-pre-gyp nopt@5.0.0 OK for: @mapbox/node-pre-gyp@1.0.11 want: ^5.0.0
79 silly placeDep ROOT npmlog@5.0.1 OK for: @mapbox/node-pre-gyp@1.0.11 want: ^5.0.1
80 silly fetch manifest are-we-there-yet@^2.0.0
81 silly fetch manifest console-control-strings@^1.1.0
82 silly fetch manifest gauge@^3.0.0
83 silly fetch manifest set-blocking@^2.0.0
84 silly placeDep ROOT rimraf@3.0.2 OK for: @mapbox/node-pre-gyp@1.0.11 want: ^3.0.2
85 silly fetch manifest glob@^7.1.3
86 silly placeDep ROOT tar@6.2.0 OK for: @mapbox/node-pre-gyp@1.0.11 want: ^6.1.11
87 silly fetch manifest chownr@^2.0.0
88 silly fetch manifest fs-minipass@^2.0.0
89 silly fetch manifest minipass@^5.0.0
90 silly fetch manifest minizlib@^2.1.1
91 silly fetch manifest mkdirp@^1.0.3
92 http fetch GET 200 https://registry.npmjs.org/debug 49ms (cache hit)
93 http fetch GET 200 https://registry.npmjs.org/are-we-there-yet 40ms (cache hit)
94 http fetch GET 200 https://registry.npmjs.org/console-control-strings 41ms (cache hit)
95 http fetch GET 200 https://registry.npmjs.org/set-blocking 41ms (cache hit)
96 http fetch GET 200 https://registry.npmjs.org/agent-base 55ms (cache hit)
97 http fetch GET 200 https://registry.npmjs.org/gauge 66ms (cache hit)
98 http fetch GET 200 https://registry.npmjs.org/semver 83ms (cache hit)
99 http fetch GET 200 https://registry.npmjs.org/whatwg-url 89ms (cache hit)
100 http fetch GET 200 https://registry.npmjs.org/glob 82ms (cache hit)
101 http fetch GET 200 https://registry.npmjs.org/fs-minipass 80ms (cache hit)
102 http fetch GET 200 https://registry.npmjs.org/chownr 83ms (cache hit)
103 http fetch GET 200 https://registry.npmjs.org/minizlib 80ms (cache hit)
104 http fetch GET 200 https://registry.npmjs.org/minipass 83ms (cache hit)
105 http fetch GET 200 https://registry.npmjs.org/mkdirp 83ms (cache hit)
106 timing idealTree:node_modules/@mapbox/node-pre-gyp Completed in 126ms
107 timing idealTree:node_modules/detect-libc Completed in 0ms
108 silly placeDep ROOT agent-base@6.0.2 OK for: https-proxy-agent@5.0.1 want: 6
109 silly placeDep node_modules/https-proxy-agent debug@4.3.4 OK for: https-proxy-agent@5.0.1 want: 4
110 silly fetch manifest ms@2.1.2
111 http fetch GET 200 https://registry.npmjs.org/ms 5ms (cache hit)
112 timing idealTree:node_modules/https-proxy-agent Completed in 13ms
113 silly placeDep node_modules/agent-base debug@4.3.4 OK for: agent-base@6.0.2 want: 4
114 timing idealTree:node_modules/agent-base Completed in 3ms
115 silly placeDep node_modules/make-dir semver@6.3.1 OK for: make-dir@3.1.0 want: ^6.0.0
116 timing idealTree:node_modules/make-dir Completed in 2ms
117 timing idealTree:node_modules/node-addon-api Completed in 1ms
118 silly placeDep ROOT whatwg-url@5.0.0 OK for: node-fetch@2.7.0 want: ^5.0.0
119 silly fetch manifest tr46@~0.0.3
120 silly fetch manifest webidl-conversions@^3.0.0
121 http fetch GET 200 https://registry.npmjs.org/tr46 6ms (cache hit)
122 http fetch GET 200 https://registry.npmjs.org/webidl-conversions 7ms (cache hit)
123 timing idealTree:node_modules/node-fetch Completed in 11ms
124 silly placeDep ROOT are-we-there-yet@2.0.0 OK for: npmlog@5.0.1 want: ^2.0.0
125 silly fetch manifest delegates@^1.0.0
126 silly fetch manifest readable-stream@^3.6.0
127 silly placeDep ROOT console-control-strings@1.1.0 OK for: npmlog@5.0.1 want: ^1.1.0
128 silly placeDep ROOT gauge@3.0.2 OK for: npmlog@5.0.1 want: ^3.0.0
129 silly fetch manifest aproba@^1.0.3 || ^2.0.0
130 silly fetch manifest color-support@^1.1.2
131 silly fetch manifest has-unicode@^2.0.1
132 silly fetch manifest object-assign@^4.1.1
133 silly fetch manifest signal-exit@^3.0.0
134 silly fetch manifest wide-align@^1.1.2
135 silly placeDep ROOT set-blocking@2.0.0 OK for: npmlog@5.0.1 want: ^2.0.0
136 http fetch GET 200 https://registry.npmjs.org/delegates 31ms (cache hit)
137 http fetch GET 200 https://registry.npmjs.org/color-support 27ms (cache hit)
138 http fetch GET 200 https://registry.npmjs.org/readable-stream 33ms (cache hit)
139 http fetch GET 200 https://registry.npmjs.org/has-unicode 33ms (cache hit)
140 http fetch GET 200 https://registry.npmjs.org/object-assign 33ms (cache hit)
141 http fetch GET 200 https://registry.npmjs.org/aproba 37ms (cache hit)
142 http fetch GET 200 https://registry.npmjs.org/signal-exit 35ms (cache hit)
143 http fetch GET 200 https://registry.npmjs.org/wide-align 36ms (cache hit)
144 timing idealTree:node_modules/npmlog Completed in 48ms
145 silly placeDep ROOT delegates@1.0.0 OK for: are-we-there-yet@2.0.0 want: ^1.0.0
146 silly placeDep node_modules/are-we-there-yet readable-stream@3.6.2 OK for: are-we-there-yet@2.0.0 want: ^3.6.0
147 timing idealTree:node_modules/are-we-there-yet Completed in 5ms
148 timing idealTree:node_modules/console-control-strings Completed in 0ms
149 timing idealTree:node_modules/delegates Completed in 0ms
150 silly placeDep ROOT aproba@2.0.0 OK for: gauge@3.0.2 want: ^1.0.3 || ^2.0.0
151 silly placeDep ROOT color-support@1.1.3 OK for: gauge@3.0.2 want: ^1.1.2
152 silly placeDep ROOT has-unicode@2.0.1 OK for: gauge@3.0.2 want: ^2.0.1
153 silly placeDep ROOT object-assign@4.1.1 OK for: gauge@3.0.2 want: ^4.1.1
154 silly placeDep ROOT signal-exit@3.0.7 OK for: gauge@3.0.2 want: ^3.0.0
155 silly placeDep ROOT wide-align@1.1.5 OK for: gauge@3.0.2 want: ^1.1.2
156 timing idealTree:node_modules/gauge Completed in 8ms
157 timing idealTree:node_modules/aproba Completed in 0ms
158 timing idealTree:node_modules/color-support Completed in 0ms
159 timing idealTree:node_modules/has-unicode Completed in 0ms
160 timing idealTree:node_modules/nvm Completed in 0ms
161 timing idealTree:node_modules/object-assign Completed in 0ms
162 silly placeDep ROOT glob@7.2.3 OK for: rimraf@3.0.2 want: ^7.1.3
163 silly fetch manifest fs.realpath@^1.0.0
164 silly fetch manifest inflight@^1.0.4
165 silly fetch manifest once@^1.3.0
166 silly fetch manifest path-is-absolute@^1.0.0
167 http fetch GET 200 https://registry.npmjs.org/fs.realpath 15ms (cache hit)
168 http fetch GET 200 https://registry.npmjs.org/inflight 14ms (cache hit)
169 http fetch GET 200 https://registry.npmjs.org/once 14ms (cache hit)
170 http fetch GET 200 https://registry.npmjs.org/path-is-absolute 14ms (cache hit)
171 timing idealTree:node_modules/rimraf Completed in 25ms
172 silly placeDep ROOT fs.realpath@1.0.0 OK for: glob@7.2.3 want: ^1.0.0
173 silly placeDep ROOT inflight@1.0.6 OK for: glob@7.2.3 want: ^1.0.4
174 silly fetch manifest wrappy@1
175 silly placeDep ROOT once@1.4.0 OK for: glob@7.2.3 want: ^1.3.0
176 silly placeDep ROOT path-is-absolute@1.0.1 OK for: glob@7.2.3 want: ^1.0.0
177 http fetch GET 200 https://registry.npmjs.org/wrappy 9ms (cache hit)
178 timing idealTree:node_modules/glob Completed in 17ms
179 timing idealTree:node_modules/fs.realpath Completed in 0ms
180 silly placeDep ROOT wrappy@1.0.2 OK for: inflight@1.0.6 want: 1
181 timing idealTree:node_modules/inflight Completed in 3ms
182 timing idealTree:node_modules/once Completed in 0ms
183 timing idealTree:node_modules/path-is-absolute Completed in 0ms
184 timing idealTree:node_modules/set-blocking Completed in 0ms
185 timing idealTree:node_modules/signal-exit Completed in 0ms
186 silly placeDep ROOT chownr@2.0.0 OK for: tar@6.2.0 want: ^2.0.0
187 silly placeDep ROOT fs-minipass@2.1.0 OK for: tar@6.2.0 want: ^2.0.0
188 silly fetch manifest minipass@^3.0.0
189 silly placeDep ROOT minipass@5.0.0 OK for: tar@6.2.0 want: ^5.0.0
190 silly placeDep ROOT minizlib@2.1.2 OK for: tar@6.2.0 want: ^2.1.1
191 silly placeDep ROOT mkdirp@1.0.4 OK for: tar@6.2.0 want: ^1.0.3
192 timing idealTree:node_modules/tar Completed in 15ms
193 timing idealTree:node_modules/chownr Completed in 0ms
194 silly placeDep node_modules/fs-minipass minipass@3.3.6 OK for: fs-minipass@2.1.0 want: ^3.0.0
195 timing idealTree:node_modules/fs-minipass Completed in 2ms
196 timing idealTree:node_modules/minipass Completed in 0ms
197 silly placeDep node_modules/minizlib minipass@3.3.6 OK for: minizlib@2.1.2 want: ^3.0.0
198 timing idealTree:node_modules/minizlib Completed in 2ms
199 timing idealTree:node_modules/mkdirp Completed in 0ms
200 silly placeDep ROOT tr46@0.0.3 OK for: whatwg-url@5.0.0 want: ~0.0.3
201 silly placeDep ROOT webidl-conversions@3.0.1 OK for: whatwg-url@5.0.0 want: ^3.0.0
202 timing idealTree:node_modules/whatwg-url Completed in 3ms
203 timing idealTree:node_modules/tr46 Completed in 0ms
204 timing idealTree:node_modules/webidl-conversions Completed in 0ms
205 timing idealTree:node_modules/wide-align Completed in 0ms
206 timing idealTree:node_modules/wrappy Completed in 0ms
207 timing idealTree:node_modules/@mapbox/node-pre-gyp/node_modules/nopt Completed in 0ms
208 silly placeDep node_modules/agent-base ms@2.1.2 OK for: debug@4.3.4 want: 2.1.2
209 timing idealTree:node_modules/agent-base/node_modules/debug Completed in 2ms
210 timing idealTree:node_modules/agent-base/node_modules/ms Completed in 0ms
211 timing idealTree:node_modules/are-we-there-yet/node_modules/readable-stream Completed in 0ms
212 timing idealTree:node_modules/fs-minipass/node_modules/minipass Completed in 0ms
213 silly placeDep node_modules/https-proxy-agent ms@2.1.2 OK for: debug@4.3.4 want: 2.1.2
214 timing idealTree:node_modules/https-proxy-agent/node_modules/debug Completed in 1ms
215 timing idealTree:node_modules/https-proxy-agent/node_modules/ms Completed in 0ms
216 timing idealTree:node_modules/make-dir/node_modules/semver Completed in 0ms
217 timing idealTree:node_modules/minizlib/node_modules/minipass Completed in 0ms
218 timing idealTree:buildDeps Completed in 2754ms
219 timing idealTree:fixDepFlags Completed in 4ms
220 timing idealTree Completed in 3143ms
221 timing command:install Completed in 3158ms
222 verbose type version
223 verbose stack nvm: No matching version found for nvm@0.38.0.
223 verbose stack     at module.exports (/home/muhammad/.nvm/versions/node/v20.10.0/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:209:23)
223 verbose stack     at RegistryFetcher.manifest (/home/muhammad/.nvm/versions/node/v20.10.0/lib/node_modules/npm/node_modules/pacote/lib/registry.js:119:22)
223 verbose stack     at async #nodeFromEdge (/home/muhammad/.nvm/versions/node/v20.10.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1049:19)
223 verbose stack     at async #buildDepStep (/home/muhammad/.nvm/versions/node/v20.10.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:917:11)
223 verbose stack     at async Arborist.buildIdealTree (/home/muhammad/.nvm/versions/node/v20.10.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:196:7)
223 verbose stack     at async Promise.all (index 1)
223 verbose stack     at async Arborist.reify (/home/muhammad/.nvm/versions/node/v20.10.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:159:5)
223 verbose stack     at async Install.exec (/home/muhammad/.nvm/versions/node/v20.10.0/lib/node_modules/npm/lib/commands/install.js:152:5)
223 verbose stack     at async module.exports (/home/muhammad/.nvm/versions/node/v20.10.0/lib/node_modules/npm/lib/cli-entry.js:61:5)
224 verbose cwd /home/muhammad/Downloads/Mern/backend
225 verbose Linux 5.15.0-89-generic
226 verbose node v20.10.0
227 verbose npm  v10.2.4
228 error code ETARGET
229 error notarget No matching version found for nvm@0.38.0.
230 error notarget In most cases you or one of your dependencies are requesting
230 error notarget a package version that doesn't exist.
231 verbose exit 1
232 timing npm Completed in 3523ms
233 verbose unfinished npm timer reify 1701874035078
234 verbose unfinished npm timer reify:loadTrees 1701874035087
235 verbose code 1
236 error A complete log of this run can be found in: /home/muhammad/.npm/_logs/2023-12-06T14_47_14_715Z-debug-0.log

**Comment by recrsn** [comment]
Some issues with your dependencies, unrelated to bcrypt
