### ISSUE TITLE
Fails in next-auth@beta in Next.js 14

### ISSUE THREAD

**Issue by igmtink** [kelektiv/node.bcrypt.js#1017]
* What went wrong?
I followed this tutorial provided by [Next.js 14](https://nextjs.org/learn/dashboard-app/adding-authentication)
Using `bcrypt` inside of `auth.config.ts` of `next-auth@beta` in Next.js 14 causes the app to crash with unusual errors:

![image](https://github.com/kelektiv/node.bcrypt.js/assets/117252369/e8e8af88-8bc1-4e45-90e0-1ffbf3aac430)

```
./node_modules/.pnpm/@mapbox+node-pre-gyp@1.0.11/node_modules/@mapbox/node-pre-gyp/lib/util/nw-pre-gyp/index.html
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <!doctype html>
| <html>
| <head>

Import trace for requested module:
./node_modules/.pnpm/@mapbox+node-pre-gyp@1.0.11/node_modules/@mapbox/node-pre-gyp/lib/util/nw-pre-gyp/index.html
./node_modules/.pnpm/@mapbox+node-pre-gyp@1.0.11/node_modules/@mapbox/node-pre-gyp/lib/ sync ^\.\/.*$
./node_modules/.pnpm/@mapbox+node-pre-gyp@1.0.11/node_modules/@mapbox/node-pre-gyp/lib/node-pre-gyp.js
./node_modules/.pnpm/bcrypt@5.1.1/node_modules/bcrypt/bcrypt.js
./lib/auth/auth.config.ts
```

* What did you expect to happen?
`bcrypt` should work in `next-auth@beta` in Next.js 14

* Which version of nodejs and OS?
```
Operating System:
  Platform: Windows 11
  Version: 23H2
Binaries:
  Node: 23.3.0
  npm: 10.2.4
  pnpm: 8.12.1
Relevant packages:
  next: 14.0.4
  next-auth: 5.0.0-beta.4
  react: ^18
  react-dom: ^18
```

* If you find a bug, please write a failing test.
Ok, maybe once I find out more.

**Comment by lightify97** [comment]
@igmtink I'm experiencing the same issue. Found any solution?

**Comment by userari** [comment]
Experiencing same issue here :/

**Comment by igmtink** [comment]
i don't find any solution until now

**Comment by umair-mirza** [comment]
Same. Got the same error at version Next.js 13.5. No fix so far.

**Comment by 2wheeh** [comment]
`node-pre-gyp` is removed in dependencies: 
- #890

but somehow it still remains in [npm](https://www.npmjs.com/package/bcrypt?activeTab=code):
<img width="338" alt="image" src="https://github.com/kelektiv/node.bcrypt.js/assets/40269597/430afb20-4787-4d53-990f-c0a6ff293faf">

This is the thing

**Comment by 2wheeh** [comment]
### Workaround: 
```ts
 const authConfig = { 
  //...
  providers: [],  // Add providers with an empty array for now
 } 

 const { auth } = NextAuth({ authConfig })
 const { signIn, singOut } = NextAuth({ 
    ...authConfig,
    providers: [
    // your logic with `bcrypt`
   ],
 });
```
[next-learn](https://github.com/vercel/next-learn) is taking this way.

**Comment by recrsn** [comment]
bcrypt will never be compatible with a server-side bundler platform. 

If nextjs allows to exclude some modules to be bundled then it would work

**Comment by 2wheeh** [comment]
> bcrypt will never be compatible with a server-side bundler platform.

@recrsn so that workaround works because `signIn`, `signOut` are called in client side and `auth` is in server side.
and after replacing `node-pre-gyp`, this will not be changed. is this right understanding?

**Comment by userari** [comment]
I switched from bcrypt to **bcryptjs** and it worked for me. I had to uninstall bcrypt & @types/bcrypt and install bcryptjs & @types/bcryptjs instead and restart the app (don't know why it didn't work without an uninstallation). 

Hope it will work for you

**Comment by dmsoftbr** [comment]
> I switched from bcrypt to **bcryptjs** and it worked for me. I had to uninstall bcrypt & @types/bcrypt and install bcryptjs & @types/bcryptjs instead and restart the app (don't know why it didn't work without an uninstallation).
> 
> Hope it will work for you

For me, the crypto module not found error occurs using bcryptjs. Do you have this issue?

**Comment by userari** [comment]
> > I switched from bcrypt to **bcryptjs** and it worked for me. I had to uninstall bcrypt & @types/bcrypt and install bcryptjs & @types/bcryptjs instead and restart the app (don't know why it didn't work without an uninstallation).
> > Hope it will work for you
> 
> For me, the crypto module not found error occurs using bcryptjs. Do you have this issue?

I do not have this issue, try to remove node_modules,  uninstall bcrypt & @types/bcrypt, and try to reinstall node_modules, hope it will work :(

**Comment by recrsn** [comment]
@2wheeh The edge runtime is not NodeJS, any native modules will not work there

`crypto` is also a nodejs specific module so bcryptjs may not even work depending on how it performs platform detection.

**Comment by jawkhan** [comment]
> ### Workaround:
> 1. [next-learn](https://github.com/vercel/next-learn) is taking this way.
> 
> ```ts
>  const authConfig = { 
>   //...
>   providers: [],  // Add providers with an empty array for now
>  } 
> 
>  const { auth } = NextAuth({ authConfig }) // called in `middleware.ts`
>  const { signIn, singOut } = NextAuth({ 
>     ...authConfig,
>     providers: [
>     // your logic with `bcrypt`
>    ],
>  });
> ```
> 
> 2. or just use `bcryptjs` instead.

Changing from `bcrypt` to `bcryptjs` worked for me. Thank you!

**Comment by shumakmanohar** [comment]
This issue still exists , any solution ?

**Comment by drilon305** [comment]
@shumakmanohar  try and look if u made a mistake 'use client' -> 'use server' for me it worked this method.

**Comment by agleymelo** [comment]
middleware is all problem, remove it or found another solution 😀

**Comment by VaultBoy9519** [comment]
Hello) Looks like a solution has been found
Check re-exports if you use them. Server components that use bcrypt and are exported to other locations MUST NOT be re-exported from the same index.ts as client components. Now I import functions directly from the export file - everything is fine, there are no errors.
![image](https://github.com/user-attachments/assets/ce71e116-d88f-4a68-8415-f67cc99b0bc0)
![image](https://github.com/user-attachments/assets/0fb8464a-340a-4b1e-9d40-b67aab225c07)
![image](https://github.com/user-attachments/assets/1b0d16b6-b8d5-4095-8166-cb16dbf034f3)
![image](https://github.com/user-attachments/assets/e9002c15-79d5-4501-afa2-2c2af06ca49f)

**Comment by agleymelo** [comment]
> Hello) Looks like a solution has been found Check re-exports if you use them. Server components that use bcrypt and are exported to other locations MUST NOT be re-exported from the same index.ts as client components. Now I import functions directly from the export file - everything is fine, there are no errors. ![image](https://private-user-images.githubusercontent.com/34946644/369651342-ce71e116-d88f-4a68-8415-f67cc99b0bc0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5NTkxODcsIm5iZiI6MTcyNjk1ODg4NywicGF0aCI6Ii8zNDk0NjY0NC8zNjk2NTEzNDItY2U3MWUxMTYtZDg4Zi00YTY4LTg0MTUtZjY3Y2M5OWIwYmMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIxVDIyNDgwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzNmFlYmQzZGIzNDA5NmUyYjZjOTU4MzYzNTRjMzdmNWJhMWZkZjVhODIzOWNkODEzZGI3M2I0NWEwODA4NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pTQ0_Gg_nnjXgfIQkK7XH-9c3j5MZjaXVwBrxXtO2Y0) ![image](https://private-user-images.githubusercontent.com/34946644/369651368-0fb8464a-340a-4b1e-9d40-b67aab225c07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5NTkxODcsIm5iZiI6MTcyNjk1ODg4NywicGF0aCI6Ii8zNDk0NjY0NC8zNjk2NTEzNjgtMGZiODQ2NGEtMzQwYS00YjFlLTlkNDAtYjY3YWFiMjI1YzA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIxVDIyNDgwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxOGE3ZTg0Zjg3OTE1YzA2NjE1OGViY2NiODU1ZTIyYzhmYTNhNzQyNmRjZmM4ZDA0MTk0ZDAyZjhiZWIzNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8UOG1o-saC9upjQn9VjHXLnkMIuSBpDwz83jm-vYtuM) ![image](https://private-user-images.githubusercontent.com/34946644/369651572-1b0d16b6-b8d5-4095-8166-cb16dbf034f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5NTkxODcsIm5iZiI6MTcyNjk1ODg4NywicGF0aCI6Ii8zNDk0NjY0NC8zNjk2NTE1NzItMWIwZDE2YjYtYjhkNS00MDk1LTgxNjYtY2IxNmRiZjAzNGYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIxVDIyNDgwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmMDQ3ZWZmOWUxZWNmODMzN2FjZDNkOTRlODcxNmFjNDc3ZTgzNmMyZjcwODdkZjNlY2RiZGJlZTNiNzk4MzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NaUsBNQ8pD5koCDR9-8NcQ_CbTUnTQ-NyfZN2m2GW5U) ![image](https://private-user-images.githubusercontent.com/34946644/369651815-e9002c15-79d5-4501-afa2-2c2af06ca49f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5NTkxODcsIm5iZiI6MTcyNjk1ODg4NywicGF0aCI6Ii8zNDk0NjY0NC8zNjk2NTE4MTUtZTkwMDJjMTUtNzlkNS00NTAxLWFmYTItMmMyYWYwNmNhNDlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIxVDIyNDgwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmOWJmYzE5ZWQzYTBjN2Y0OTdjZDNhMGZiNGVhODQ4NGU1OWJhYWU0ZDkyMDc4YzNiYmM0YTk4NmQwOWIyNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.K2kUF0zYxsucnpErTd1FKD0nX-v7MRFnTZ4lJ30mXGk)

and a good solution is to use what you just showed

**Comment by KrownWealth** [comment]
Not re-exporting in index.ts works for me

**Comment by mdmahendri** [comment]
> @shumakmanohar try and look if u made a mistake 'use client' -> 'use server' for me it worked this method.

very nice of you to mention this, problem solved!

**Comment by sovetski** [comment]
Any update please? for me using bcryptjs is not a good solution, the package did not get any update since 8 years..

**Comment by sammycristian20** [comment]
![image](https://github.com/user-attachments/assets/901b7c67-772c-4292-9272-1bdf5a6eced2)

I have this error NextRequest not appear what is your suggestion
