### ISSUE TITLE
string-width\index.js not supported.

### ISSUE THREAD

**Issue by breno404** [kelektiv/node.bcrypt.js#1020]
* What went wrong?
I can't use bcrypt because "string-width\index.js not supported."

* What did you expect to happen?
Install and run bcrypt

* Which version of nodejs and OS?
Node: 20.10.0 
OS: Windows 11

* If you find a bug, please write a failing test.
1. Start a new typescript project and use this setting:
<code>{
  "include": ["src/**/*"],
  "exclude": ["node_modules"],
  "compilerOptions": {
    "target": "ES6",
    "lib": ["ES5", "ES2015", "ES2016", "ES2017", "ES2018"],
    "module": "Node16" /* Specify what module code is generated. */,
    "rootDir": "src" /* Specify the root folder within your source files. */,
    "moduleResolution": "Node16" /* Specify how TypeScript looks up a file from a given module specifier. */,
    "baseUrl": ".",
    "paths": {
      "@/config/*": ["./src/config/*"],
      "@/entities/*": ["src/models/*"],
      "@/controllers/*": ["./src/controllers/*"],
      "@/services/*": ["./src/services/*"]
    },
    "resolveJsonModule": true /* Enable importing .json files. */,
    "noResolve": false /* Disallow 'import's, 'require's or '<reference>'s from expanding the number of files TypeScript should add to a project. */,
    "allowJs": true /* Allow JavaScript files to be a part of your program. Use the 'checkJS' option to get errors from these files. */,
    "skipLibCheck": true /* Skip type checking all .d.ts files. */
  }
}</code>

2. Run yarn add command:
yarn add bcrypt

3. Try using the dependency:
import bcrypt from "bcrypt"

[SCREENSHOTS]:
*tsconfig:
![image](https://github.com/kelektiv/node.bcrypt.js/assets/48841329/908750ef-f6f0-4a81-8a2e-46db7ae3bf69)

*command line:
![image](https://github.com/kelektiv/node.bcrypt.js/assets/48841329/e1491bd5-25c3-4f0b-aabe-50f7850a3a27)

*import dependency:
![image](https://github.com/kelektiv/node.bcrypt.js/assets/48841329/89f2f06a-5c76-4d48-a7e8-c27d5d6ef307)

**Comment by breno404** [comment]
I add the "lib" property in the tsconfig file and apparently this solved it:
"lib": ["ES5", "ES2015", "ES2016", "ES2017", "ES2018"],

I know that is in screenshot but before when the error occurred there was no

**Comment by aw1875** [comment]
Have you had any luck finding a proper solution do this? Right now I've got a hacky workaround that works but its annoying to have to do that every time I add a new package.

**Comment by recrsn** [comment]
Since string-width is not an es-module, you will need to use `esModuleInterop` till the ecosystem catches up.

**Comment by breno404** [comment]
@aw1875 still nothing, I'm using bcryptjs as an alternative.
