### ISSUE TITLE
fatal error LNK1181: cannot open input file 'kernel32.lib'

### ISSUE THREAD

**Issue by skotchio** [kelektiv/node.bcrypt.js#112]
Hi. I'm trying to install bcrypt on my Windows 7 machine. I've installed all dependencies from the manual. But when I do:

```
>  npm install bcrypt
```

I'm getting the error message: fatal error LNK1181: cannot open input file 'kernel32.lib'

Help please.

**Comment by JitendraDaswani** [comment]
Hi guys,
I am facing the same issue: LINK : fatal error LNK1181: cannot open input file 'kernel32.lib' [D:\conduco-d
evelop\conduco-develop\node_modules\zombie\node_modules\jsdom\node_modules\cont
extify\build\contextify.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:807:
12)

Please help me to resolve this issue. Thanks in advance
