### ISSUE TITLE
Break in pattern for long password.

### ISSUE THREAD

**Issue by NicolasPelletier** [kelektiv/node.bcrypt.js#128]
Just to leave you a note. I don't know if it is a bug or not.

From what I seem to remember, after a certain length of password, the hash start to repeat. So I wrote an experiment with a Chinese character. This increments the password length from zero characters to 100 repeating characters. It prints the length of the password in characters, the length in bytes and then the hash for the ever longer password.

``` javascript
/*jslint node: true, indent: 4, stupid: true */
var bcrypt = require('bcrypt'),
    salt = '$2a$05$0000000000000000000000',
    pw,
    hash = [],
    i,
    charLen,
    byLength,
    log;

pw = '';
hash[0] = bcrypt.hashSync(pw, salt);

for (i = 1; i < 100; i += 1) {
    pw += '\u6e2f'; // http://www.fileformat.info/info/unicode/char/6e2f/index.htm
    hash[i] = bcrypt.hashSync(pw, salt);

    charLen = pw.length;
    byLength = Buffer.byteLength(pw, 'utf8');

    log = ((charLen < 10) ? '0' : '') + charLen + ' - ';
    log += ((byLength < 10) ? '00' : (byLength < 100) ? '0' : '') + byLength + ': ';
    log += hash[i];
    if (hash[i] === hash[i - 1]) {
        log += ' - same as previous';
    }
    console.log(log);
}
```

Look at the output of this. When the length of the password reaches 24 ( 72 bytes ), any characters added to that password has no effect on the hash. This is as expected...

But, look at length 85 ( 255 bytes ).  For some reasons, the hash is totally different from the others. Every hash from length 25 to 100 is identical, except for length 85.

I am not knowledgeable about BCrypt to find out if there is a problem in your code and submit a pull request, but I wanted to let you know in case it revealed a flaw somewhere in your code around length of 255 bytes.

**Comment by ListsOfArrays** [comment]
This was a bug found in the OpenBSD reference implementation used.
This bug has been fixed in the newer versions of the reference implementation.
Please see this bugfix commit to OpenBSD: https://github.com/openbsd/src/commit/4ffb3abbc586afe49cc5632ec7f89d54860fb8d9
