### ISSUE TITLE
Bcrypt installation issue on Mac 10.7.5

### ISSUE THREAD

**Issue by ishortman** [kelektiv/node.bcrypt.js#136]
Getting an error with installation of bcrypt 0.7.2 for node.  Using mac osx 10.7.5 and have all the required tools installed such as python(2.7.1) and command line tools.
1. ran sudo npm install bcrypt
2. error returned:
   npm verb rebuildBundles [ 'bindings' ]
   npm info install bcrypt@0.7.2
   npm verb unsafe-perm in lifecycle false

> bcrypt@0.7.2 install /Users/429636/Projects/ngwp-node-t2/node_modules/bcrypt
> node-gyp rebuild

npm verb set uid from=0 to=144848777
gyp info it worked if it ends with ok
gyp verb cli [ 'node', '/usr/local/bin/node-gyp', 'rebuild' ]
gyp info using node-gyp@0.8.2
gyp info using node@0.8.14 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded for `%s` python /usr/bin/python
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: python: no user 144848777
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:540:15)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:99:17)
gyp ERR! stack     at maybeClose (child_process.js:638:16)
gyp ERR! stack     at Socket.ChildProcess.spawn.stdin (child_process.js:815:11)
gyp ERR! stack     at Socket.EventEmitter.emit (events.js:96:17)
gyp ERR! stack     at Socket._destroy.destroyed (net.js:357:10)
gyp ERR! stack     at process.startup.processNextTick.process._tickCallback (node.js:244:9)
gyp ERR! System Darwin 11.4.2
gyp ERR! command "node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/429636/Projects/ngwp-node-t2/node_modules/bcrypt
gyp ERR! node -v v0.8.14
gyp ERR! node-gyp -v v0.8.2
gyp ERR! not ok 
npm info bcrypt@0.7.2 Failed to exec install script
npm info /Users/429636/Projects/ngwp-node-t2/node_modules/bcrypt unbuild
npm verb from cache /Users/429636/Projects/ngwp-node-t2/node_modules/bcrypt/package.json
npm info preuninstall bcrypt@0.7.2
npm info uninstall bcrypt@0.7.2
npm verb true,/Users/429636/Projects/ngwp-node-t2/node_modules,/Users/429636/Projects/ngwp-node-t2/node_modules unbuild bcrypt@0.7.2
npm info postuninstall bcrypt@0.7.2
npm ERR! bcrypt@0.7.2 install: `node-gyp rebuild`
npm ERR! `sh "-c" "node-gyp rebuild"` failed with 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.7.2 install script.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 11.4.2
npm ERR! command "node" "/usr/local/bin/npm" "install" "--verbose"
npm ERR! cwd /Users/429636/Projects/ngwp-node-t2
npm ERR! node -v v0.8.14
npm ERR! npm -v 1.1.65
npm ERR! code ELIFECYCLE
npm verb exit [ 1, true ]

Any recommendations to get this fixed?

**Comment by abhirajPeerbits** [comment]
**Getting an error with installation of bcrypt 0.7.2 for node. Using mac osx 10.7.5 and have all the required tools installed such as python(2.7.1) and command line tools.**

ITCPU034:~ pbmini1$ cd /Users/pbmini1/Desktop/ABHISHEK_SAVANI_2/shailDemo/sail-demo/sails_demo_HS 
ITCPU034:sails_demo_HS pbmini1$ **sudo npm install bcrypt** 
Password:

> bcrypt@3.0.3 install /Users/pbmini1/Desktop/ABHISHEK_SAVANI_2/shailDemo/sail-demo/sails_demo_HS/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp WARN Pre-built binaries not installable for bcrypt@3.0.3 and node@10.14.1 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/Users/pbmini1/Desktop/ABHISHEK_SAVANI_2/shailDemo/sail-demo/sails_demo_HS/node_modules/bcrypt/lib' 
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/Users/pbmini1/Desktop/ABHISHEK_SAVANI_2/shailDemo/sail-demo/sails_demo_HS/node_modules/bcrypt/build'
gyp ERR! System Darwin 17.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/pbmini1/Desktop/ABHISHEK_SAVANI_2/shailDemo/sail-demo/sails_demo_HS/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/Users/pbmini1/Desktop/ABHISHEK_SAVANI_2/shailDemo/sail-demo/sails_demo_HS/node_modules/bcrypt/lib/binding" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd /Users/pbmini1/Desktop/ABHISHEK_SAVANI_2/shailDemo/sail-demo/sails_demo_HS/node_modules/bcrypt
gyp ERR! node -v v10.14.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/pbmini1/Desktop/ABHISHEK_SAVANI_2/shailDemo/sail-demo/sails_demo_HS/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/Users/pbmini1/Desktop/ABHISHEK_SAVANI_2/shailDemo/sail-demo/sails_demo_HS/node_modules/bcrypt/lib/binding --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/pbmini1/Desktop/ABHISHEK_SAVANI_2/shailDemo/sail-demo/sails_demo_HS/node_modules/bcrypt/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Darwin 17.0.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/pbmini1/Desktop/ABHISHEK_SAVANI_2/shailDemo/sail-demo/sails_demo_HS/node_modules/bcrypt/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/pbmini1/Desktop/ABHISHEK_SAVANI_2/shailDemo/sail-demo/sails_demo_HS/node_modules/bcrypt
node-pre-gyp ERR! node -v v10.14.1
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/pbmini1/Desktop/ABHISHEK_SAVANI_2/shailDemo/sail-demo/sails_demo_HS/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/Users/pbmini1/Desktop/ABHISHEK_SAVANI_2/shailDemo/sail-demo/sails_demo_HS/node_modules/bcrypt/lib/binding --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
npm WARN enoent ENOENT: no such file or directory, open '/Users/pbmini1/Desktop/ABHISHEK_SAVANI_2/shailDemo/sail-demo/sails_demo_HS/package.json'
npm WARN sails_demo_HS No description
npm WARN sails_demo_HS No repository field.
npm WARN sails_demo_HS No README data
npm WARN sails_demo_HS No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@3.0.3 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@3.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pbmini1/.npm/_logs/2019-02-06T11_51_29_406Z-debug.log

**Comment by agathver** [comment]
@abhirajPeerbits Do not run as root / sudo. bcrypt (or any node module will not install). This is not a bcrypt issue. Fix directory permissions

**Comment by agathver** [comment]
Feel free to open a new issue if the error persists instead of bumping an old thread
