### ISSUE TITLE
dyld: lazy symbol binding failed: Symbol not found

### ISSUE THREAD

**Issue by nornagon** [kelektiv/node.bcrypt.js#16]
I'm running this module on OSX 10.6.6, node.js v0.4.1, with bcrypt installed by 'npm install bcrypt'.

When I `require('bcrypt')`, I get these messages:

<pre>dyld: lazy symbol binding failed: Symbol not found: __ZN2v811HandleScopeC1Ev
  Referenced from: /usr/local/Cellar/node-v/0.4.1/lib/node/.npm/bcrypt/0.2.3/package/build/default/bcrypt_lib.node
  Expected in: flat namespace

dyld: Symbol not found: __ZN2v811HandleScopeC1Ev
  Referenced from: /usr/local/Cellar/node-v/0.4.1/lib/node/.npm/bcrypt/0.2.3/package/build/default/bcrypt_lib.node
  Expected in: flat namespace</pre>

**Comment by durja** [comment]
I am using bcrypt 3.0.1 and node 8.9.3 version and I get the error as stated above.

`dyld: lazy symbol binding failed: Symbol not found :__ZN4node19GetCurrentEventLoopEPN2v87IsolateE Referenced from: /Users/local/WebstormProjects/be/node_modules/bcrypt/lib/binding/bcrypt_lib.node
  Expected in: flat namespace

dyld: Symbol not found: __ZN4node19GetCurrentEventLoopEPN2v87IsolateE
  Referenced from: /Users/local/WebstormProjects/be/node_modules/node_modules/bcrypt/lib/binding/bcrypt_lib.node
  Expected in: flat namespace`

**Comment by agathver** [comment]
@dujra Try recompiling the addon. `npm rebuild bcrypt --build-from-source`

**Comment by bossley** [comment]
@agathver Thank you! This worked for me!

**Comment by andrewaarestad** [comment]
This is happening for me with node 8.2.1 and bcrypt 3.0.2.  I was able to fix it locally by recompiling as suggested by @agathver but that's not an option for me in production so I had to downgrade bcrypt.

**Comment by gastonelhordoy** [comment]
> This is happening for me with node 8.2.1 and bcrypt 3.0.2. I was able to fix it locally by recompiling as suggested by @agathver but that's not an option for me in production so I had to downgrade bcrypt.

Hey @andrewaarestad, which version of bcrypt worked for you? Thanks man!

**Comment by andrewaarestad** [comment]
@gastonelhordoy I haven't had any issues after downgrading to bcrypt 3.0.0.

**Comment by gastonelhordoy** [comment]
Thanks @andrewaarestad, it worked!

**Comment by connor11528** [comment]
@agathver thanks for the command. Any insight into why running this command fixes the error?

Worked for me. Interested to know what was wrong!

**Comment by AndyAlex** [comment]
@andrewaarestad I tried downgrading to 3.0.0 but still had the same problem (Node v8.9.4). Running `npm rebuild bcrypt --build-from-source ` worked for me, but that's not a very nice "hack". I'm interested if (and when) this can be fixed. It's not very cool for production environments.

Regards all

**Comment by PK1210** [comment]
npm rebuild bcrypt --build-from-source  worked for me as well but can anyone explain me why and how is it working

**Comment by agathver** [comment]
@PK1210 There was an ABI incompatibility between 8.X releases. You have to recompile from sources in order to bind to the correct symbols, if you are on the affected versions.

**Comment by joseh182** [comment]
> @dujra Try recompiling the addon. `npm rebuild bcrypt --build-from-source`

Worked for me! Thanks

**Comment by Klutch27** [comment]
September 2019 and @agathver solution `npm rebuild bcrypt --build-from-source` worked for me. Not sure why this is the case though? No one else on my team ran into this issue except for me. Thanks for the help!

**Comment by Sharat005** [comment]
@agathver Worked for me as well! Thanks :)

**Comment by FullstackJack** [comment]
I forgot to `nvm use`. It was installed with a different version of Node than the default system Node.

**Comment by Tsourdox** [comment]
I just updated node to the latest version 13.x and that solved it for me :)
