### ISSUE TITLE
strange behavior for compare async after compareSync on windows for invalid hash strings

### ISSUE THREAD

**Issue by fresheneesz** [kelektiv/node.bcrypt.js#177]
Update:

It seems that "somehash" isn't a valid hash, and causes undefined behavior. This behavior should be defined: throw an error indicating the hash isn't valid.

Original:

It seems that (async) compare _always_ returns true for any passed hash to check:

```
var bcrypt = require("bcrypt")

var result = bcrypt.compareSync("somepassword", "somehash")
console.log("Sync: "+result) // returns false correctly

bcrypt.compare("somepassword", "somehash", function(err, result) {
    console.log("Async: "+result) // returns true!
})
```

Interesting thing I noticed, if you start salt generation before doing the comparisons, they both correctly return false - bizarre:

```
var bcrypt = require("bcrypt")

bcrypt.genSalt(10, 30, function(err, salt) {})

bcrypt.compare("somepassword", "somehash", function(err, result) {
    console.log("Async: "+result) // returns false correctly
})

var result = bcrypt.compareSync("somepassword", "somehash")
console.log("Sync: "+result)    // returns false correctly this time!
```

Environment: Windows 7 32-bit, node 0.10.9, "bcrypt@0.7.6"

**Comment by MeloGit** [comment]
Hi @defunctzombie , 

I have the same issue, the bcrypt compareSync function does not recognize my password once I restarts my sails server or after a long service life of the sails server. I am working on windows 
and I do not really understand or could come to the issue

**Comment by tribhuwank** [comment]
bcrypt.compareAsync(password, this.password) always returning false. my code is:
const Promise = require('bluebird')
const bcrypt = Promise.promisifyAll(require('bcrypt-nodejs'))

function hashPassword (user, options) {
  const SALT_FACTOR = 8

  if (!user.changed('password')) {
    return
  }

  return bcrypt
    .genSaltAsync(SALT_FACTOR)
    .then(salt => bcrypt.hashAsync(user.password, salt, null))
    .then(hash => {
      user.setDataValue('password', hash)
    })
}

module.exports = (sequelize, DataTypes) => {
  const User = sequelize.define('User', {
    name: {
      type:DataTypes.STRING,
      allowNull: false
    },
    email: {
      type: DataTypes.STRING,
      unique: true,
      allowNull: false
    },    
    mobile: {
      type:DataTypes.STRING,
      allowNull: false
    },
    gender: {
        type: DataTypes.BOOLEAN,
        allowNull: false,
        defaultValue: true
      },
    age:DataTypes.INTEGER,
    password:{
      type: DataTypes.STRING,
      allowNull: false
    }
   
  }, {
    hooks: {
     beforeSave: hashPassword
    }
  })

  User.prototype.comparePassword = function (password) {
    return bcrypt.compareAsync(password, this.password)
  }

  User.associate = function (models) {
  }

  return User
}

Can you anybody makes understand why so?


Thanks.
