### ISSUE TITLE
precompiled binaries?

### ISSUE THREAD

**Issue by Pomax** [kelektiv/node.bcrypt.js#186]
In the spirit of `sqlite3` moving to precompiled binaries, only using node-gyp compiling when no binaries are found for the platform `npm install` is called on, I'd like to request the same approach for bcrypt, so that we don't have to worry about having the correct headers and c++ stack on windows or OSX (not everyone has a full VC++ stack or XCode, and with precompiled binaries, no one would need those either =)

**Comment by GongT** [comment]
so is there any precompiled binaries now?

I install bcrypt and it failed to download binary file from `https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.1/bcrypt_lib-v1.0.1-node-v51-linux-x64.tar.gz`    
(then it fail to compile, because I do not have python)

I'm doing something like:
```
SASS_BINARY_SITE=http://npm.taobao.org/mirrors/node-sass npm install node-sass
SQLITE3_BINARY_SITE=http://npm.taobao.org/mirrors/sqlite3 npm install sqlite3

npm install phantomjs --phantomjs_cdnurl=http://npm.taobao.org/mirrors/phantomjs
```
Is there any options like `BCRYPT_BINARY_SITE` or `--bcrypt_cndurl=`?

**Comment by Pomax** [comment]
I don't know your config actually does, but I don't see anything in it that involves binaries. Just because the environment variable is *called* `..._BINARY` doesn't make the rest of the commands suddenly be binary installations; the instructions you show for those env. vars are just the regular npm install commands, but with a different npm mirror as base URL. If you get installation failures, the obvious first step is to not do things this way and instead rely on npm being able to do everything it needs to do based on what's in your `package.json`. Package/dependency installation does not require playing a guessing game with environment variables.

**Comment by GongT** [comment]
I don't understand how node-sass magically did this, but it really work.

If I install node-sass with this, it will take about 2~3 seconds
```bash
export SASS_BINARY_SITE=http://npm.taobao.org/mirrors/node-sass
npm i -d --progress=false --global node-sass
```

I can see this in npm log:
```
Downloading binary from http://npm.taobao.org/mirrors/node-sass/v4.3.0/linux-x64-48_binding.node
Download complete
```

but if I use only 
```bash
npm i -d --progress=false --global node-sass
```

It will take about 10~20 **minutes**. I try this 10 times, it will fail 8 times.


----
*fucking GFW*
