### ISSUE TITLE
npm install fails, npm install bcrypt works

### ISSUE THREAD

**Issue by binarykitchen** [kelektiv/node.bcrypt.js#193]
In my package.json I have this line `"bcrypt": "~0.7.7"` under the dependencies. When I install my app simply via `npm install` then the app crashes while running grunt tests with:

> > Mocha exploded!
> > Error: Could not load the bindings file. Tried:
> >     .../xxx/node_modules/bcrypt/build/bcrypt_lib.node
> >     .../xxx/node_modules/bcrypt/build/Debug/bcrypt_lib.node
> >     .../xxx/node_modules/bcrypt/build/Release/bcrypt_lib.node
> >     .../xxx/node_modules/bcrypt/out/Debug/bcrypt_lib.node
> >     .../xxx/node_modules/bcrypt/Debug/bcrypt_lib.node
> >     .../xxx/node_modules/bcrypt/out/Release/bcrypt_lib.node
> >     .../xxx/node_modules/bcrypt/Release/bcrypt_lib.node
> >     .../xxx/node_modules/bcrypt/build/default/bcrypt_lib.node
> >     .../xxx/node_modules/bcrypt/compiled/0.10.22/darwin/x64/bcrypt_lib.node
> >     .../xxx/node_modules/bcrypt/node_modules/bindings/bindings.js:84:13)
> >     .../xxx/node_modules/bcrypt/bcrypt.js:1:97)

I have to run manually `npm install bcrypt` again after `npm install` and then it works. Really weird.

This forces me to add this line in package.json to make it work with `npm install`:

```
  "scripts": {
    "start":        "node ./server/server",
    "postinstall":  "npm install bcrypt", // kludge! bad workaround
    "test":         "grunt test"
  },
```

I know, it's bad. But I have to add this postinstall script so that it won't crash on my server when deployed.

Any clues?

**Comment by mrpmorris** [comment]
Do you have Python installed? node-gyp requires 2.5 < version < 3.0

**Comment by binarykitchen** [comment]
why do you ask me when this is a npm thing? if `package.json` fails to declare all the dependencies such as the correct python version, then address this to the makers of npm.

furthermore - if you don't mind me being straightforward - i think python has no major place in the javascript universe. i totally understand that node-gyp is required because of all those different platforms. sounds like blaming the user whereas the user-land configures the installation process. in other words, blame eve for eating the apple whereas the apple was laid out by a higher power (just a 'bad' example, i am not that religious ;)

**Comment by ncb000gt** [comment]
At the moment, if you want the module to work you'll have to setup some of
the dependencies yourself. We depend on other modules to handle platform
and OS comparability. These dependencies have other dependencies. We make
note of these in the readme. For instance if you want to use the module you
currently have to compile it which means you'll need a compiler, we're not
going to include one here...

This isn't about blaming the user, just notes the current state of cross
platform node addons. This may change at some point but that'll definitely
be down the road.
