### ISSUE TITLE
Domains can't catch errors inside bcrypt callbacks

### ISSUE THREAD

**Issue by ben-ng** [kelektiv/node.bcrypt.js#235]
---
### We are not going to fix this. If you want to make a PR, please do so and we can review it however no one maintaining this currently uses domains or thinks they are worthwhile to support. If that changes or someone makes a PR we will revisit.

---

I've noticed that errors inside bcrypt callbacks can't be caught by domains.

Minimal test case:

``` js
var bcrypt = require('bcrypt')
  , domain = require('domain')
  , d = domain.create()

d.on('error', function (e) {
  console.log('error caught: ' + e)
})

d.run(function () {
  bcrypt.genSalt(10, function() {
    throw new Error('this one fails')
  });
})
```

I expect to see 'error caught: this one fails'. It doesn't appear.

However, if you run the domain again, now both errors are caught:

``` js
var bcrypt = require('bcrypt')
  , domain = require('domain')
  , d = domain.create()

d.on('error', function (e) {
  console.log('error caught: ' + e)
})

d.run(function () {
  bcrypt.genSalt(10, function() {
    throw new Error('this one fails')
  });
})

d.run(function () {
  throw new Error('this one works')
})
```

Now both errors are caught by the domain.

**Comment by mannyvergel** [comment]
Is there any work around for this? I really need a domain aware bcrypt

**Comment by benjamn** [comment]
```js
require("domain");
require("bcrypt").hash("a", 5, function(){})

**Comment by benjamn** [comment]
As another somewhat scarier datapoint, in the Node 0.10.45 REPL, the following commands crash the shell:
```js
> require("domain")
{ _stack: [],
  Domain: 
   { [Function: Domain]
     super_: { [Function: EventEmitter] listenerCount: [Function] } },
  createDomain: [Function],
  create: [Function],
  active: null }
> require("bcrypt").hash("a", 5, function(){})
undefined
>
undefined:0


TypeError: undefined is not a function
```

**Comment by ffxsam** [comment]
Experiencing the same issue as @benjamn - causing a totally breaking state in production.

**Comment by defunctzombie** [comment]
Closing [Domains are deprecated](https://nodejs.org/dist/latest-v7.x/docs/api/domain.html)
