### ISSUE TITLE
Any plan to support promises of node 0.11

### ISSUE THREAD

**Issue by dozoisch** [kelektiv/node.bcrypt.js#239]
Any plan to support `yield` and promises of node 0.11?

As a patch, it could be a simple bcrypt_thunk.js file in the root so people can `require('bcrypt/bcryp_thunks')`

I made a quick wrapping lib, and a few test if you are interested!

_Kind of linked to #194_

**Comment by ndreckshage** [comment]
easy way to wrap if it helps anyone

```
module.exports = require('bluebird').promisifyAll(require('bcrypt'));
```

```
yield bcrypt.genSaltAsync(10); // etc
```
