### ISSUE TITLE
meteor npm install  --bcrypt -save is throwing an error

### ISSUE THREAD

**Issue by skumaroh** [kelektiv/node.bcrypt.js#451]
screenshot attached with details.
Node version is v.4.6
windows 10
![image](https://cloud.githubusercontent.com/assets/6601876/19297210/38e62900-9008-11e6-9ffc-50759abb5bd5.png)

**Comment by ncb000gt** [comment]
Does it build for you if you build it from the repository?

I'm guessing the error in red is the real problem `The Windows SDK version 8.1 was not found...`. Take a look at what that describes, try again, and let us know how that works out. Thanks.

**Comment by skumaroh** [comment]
I didn't try from repository.

But you are correct. I manually installed SDK version 8.1 on my PC. That error is gone.

Now I have one stupid error. I should be able to fix that.

Thank you so much!


Best Regards, Kumar


________________________________

**Comment by psbyron3** [comment]
I'm having a similar error code. I just updated node as well as npm. Perhaps bcrypt is not supported in Nodev7??

<img width="781" alt="screen shot 2016-10-26 at 3 19 29 pm" src="https://cloud.githubusercontent.com/assets/17244224/19747298/b8741244-9b8f-11e6-943d-f48dd4bb1312.png">

**Comment by ByronKos** [comment]
Had the same issue. Installed: 
https://developer.microsoft.com/en-us/windows/downloads/windows-8-1-sdk

Got another error:
"node gyp error TRACKER : error TRK0005: Failed to locate: “CL.exe”. The system cannot find the file specified"

Solution:
http://stackoverflow.com/questions/33183161/node-gyp-error-tracker-error-trk0005-failed-to-locate-cl-exe-the-system-c

Another error:
" '__pfnDliNotifyHook2': redefinition; different type modifiers "

Solution:
https://github.com/nodejs/node-gyp/issues/972
