### ISSUE TITLE
Can not compare sync a hashed password

### ISSUE THREAD

**Issue by muuvmuuv** [kelektiv/node.bcrypt.js#455]
Hey, im trying to compare a hashed password from a woltlab forum database with the input from my login page. The woltlab forum uses his own encryption but it looks a bit similar. Here is there php class: [Password.class.php](https://github.com/WoltLab/WCF/blob/master/wcfsetup/install/files/lib/util/PasswordUtil.class.php)
I want to get that work in a MEAN project.

* What went wrong?
bcrypt does not compare the hash with the password from the input right.

* What did you expect to happen?
A comparison

* Which version of nodejs and OS?
NodeJS: v6.3.1
OS: Mac OS 10.12.1 (16B2555) Sierra

* If you find a bug, please write a failing test.
I think this is no bug. Its just that WCF is using $2a$08$ (60 chars long) and bcrypt uses something else for comparison.

I'm totally new to encryption things. If this does not explain it at all, I'll post the code somewhere.

WoltLab HASH: $2a$08$4nOs/4XT8sgoP6/MhPltguVHxu8k9u7z6lbCLpnTs1OM9eS0zc/M6 (plain: test)

**Comment by defunctzombie** [comment]
Unless they used the exact same type of bcrypt then this won't work.
