### ISSUE TITLE
Is it possible to strengthen an encryption by adding iteration rounds?

### ISSUE THREAD

**Issue by TheLudd** [kelektiv/node.bcrypt.js#457]
If I have a database of encrypted user passwords, all stored with the bcrypt algorithm using 14 rounds, is it possible with this lib to add 1 round to each encrypted password and thus have all passwords stored with 15 rounds?

I understood this as being one of the key features of the bcrypt algorithm from the [Wikipedia page](https://en.wikipedia.org/wiki/Bcrypt). 

> Besides incorporating a salt to protect against rainbow table attacks, bcrypt is an adaptive function: over time, the iteration count can be increased to make it slower, so it remains resistant to brute-force search attacks even with increasing computation power.

**Comment by vlakoff** [comment]
That's not possible. You have to wait the user types his password again, at this moment you have the plaintext password and can hash it using the updated bcrypt cost.

**Comment by TheLudd** [comment]
Thank you for the answer. I take it then that this is not possible at all using the bcrypt algortigm?

**Comment by vlakoff** [comment]
Yep, it's one-way. Once it's hashed, it's hashed. To verify or rehash a password, you need the plaintext.

**Comment by TheLudd** [comment]
Thanks

**Comment by vlakoff** [comment]
You may be interested by the top answers on these Stack Exchange questions:
* [Do I have to recompute all hashes if I change the work factor in bcrypt?](http://crypto.stackexchange.com/questions/3003/do-i-have-to-recompute-all-hashes-if-i-change-the-work-factor-in-bcrypt)
* [Is it possible to increase the cost of BCrypt or PBKDF2 when its already calculated and without the original password?](http://security.stackexchange.com/questions/15847/is-it-possible-to-increase-the-cost-of-bcrypt-or-pbkdf2-when-its-already-calcula)
