### ISSUE TITLE
npm install bcrypt is throwing an error. 

### ISSUE THREAD

**Issue by jaselchauhan** [kelektiv/node.bcrypt.js#459]
Hi,

I am trying to install Bcrypt via npm but am getting the below error (screenshot and npm debug log file attached). I have the latest versions of both Node and NPM (v7.2.0 and 4.0.2 respectively). Also tried running with sudo but get the same error.

<img width="1393" alt="screenshot 2016-11-27 22 28 42" src="https://cloud.githubusercontent.com/assets/14994308/20652434/f7027b7a-b4f0-11e6-8ff6-5da2d35ae843.png">
)

I have been using Bcrypt for a few months now and haven't run into any issues.

Any help would be greatly appreciated,

Thanks!

[npm-debug.log.zip](https://github.com/kelektiv/node.bcrypt.js/files/615106/npm-debug.log.zip)

**Comment by defunctzombie** [comment]
You probably need to launch xcode and agree to new license terms.
