### ISSUE TITLE
v1.0.0 build issues on AWS

### ISSUE THREAD

**Issue by ffxsam** [kelektiv/node.bcrypt.js#460]
I'm using [Galaxy](https://galaxy.meteor.com) to deploy my Meteor/React app. My app has used bcrypt 0.8.7 for quite some time, but upgrading to bcrypt 1.0.0 causes breakage upon deployment:

```
v086
2016-12-04 19:41:07-08:00> bcrypt@1.0.0 install /app/bundle/programs/server/npm/node_modules/bcrypt
v086
2016-12-04 19:41:07-08:00> node-pre-gyp install --fallback-to-build
v086
2016-12-04 19:41:07-08:00
v086
2016-12-04 19:41:07-08:00sh: 1: node-pre-gyp: not found
v086
2016-12-04 19:41:07-08:00
v086
2016-12-04 19:41:07-08:00npm ERR! Linux 4.4.0-45-generic
```

https://forums.meteor.com/t/bcrypt-1-x-major-issues-wont-deploy-to-galaxy/31969

I believe Galaxy uses Ubuntu images. When I downgrade to bcrypt 0.8.7, everything deploys as expected.

**Comment by Agathver** [comment]
Do you have build-tools installed (gcc, make, binutils, and python)? 
I don't know about Galaxy image, but the vanilla Ubuntu ones on AWS don't come with build-essentials preinstalled.

**Comment by ffxsam** [comment]
I'll check, and get back to you ASAP. Thanks!

**Comment by Siyfion** [comment]
I'm also experiencing this same issue, v1.0.0 fails v0.8.7 works fine.

**Comment by defunctzombie** [comment]
The `node-gyp-pre` command is run during via the `install` script portion. According to [the documentation](https://docs.npmjs.com/misc/scripts) this is run after the package is installed. `node-gyp-pre` is in the dependencies list and should be available. I would check that your install did not have other errors. Or try to clean install again.
