### ISSUE TITLE
Compare method not rejecting promise on error

### ISSUE THREAD

**Issue by adamreisnz** [kelektiv/node.bcrypt.js#468]
Hello,

First of all, it's great that bcrypt now supports a Promise API.
However, it seems there are still a few "holes" in it.

One that I ran into, was related to these lines of code:

https://github.com/kelektiv/node.bcrypt.js/blob/master/bcrypt.js#L157
https://github.com/kelektiv/node.bcrypt.js/blob/master/bcrypt.js#L163

If there is no callback provided (e.g. Promise API is used), then both of these lines will trigger a `TypeError: cb is not a function`.

What needs to happen, is a similar check as a few lines below, and then reject with the error instead of passing it to the callback, if no callback is given. Something like this:

```js
const err = new Error('data and hash arguments required');
if (!cb) {
  return Promise.reject(err);
}
else {
  return process.nextTick(function() {
      cb(err);
  });
}
```

I would create a PR, but not sure what the deal is with wrapping the errors in `process.nextTick`.

This is with brypt 1.0.1.

**Comment by Agathver** [comment]
I'm working on a PR to fix this.

**Comment by Agathver** [comment]
@adamreisnz Can you supply some code that triggered the error ?

**Comment by adamreisnz** [comment]
I think I was simply calling the `compare` method with an empty password:

```
bcrypt.compare(candidatePassword, this.password);
```

Where `this.password` may have been undefined.

I've since put a guard in place to capture these cases gracefully, but since I'm relying on that call returning a Promise, it needs to properly reject with the appropriate error in case of failure.

Let me know if there's anything else you need.
