### ISSUE TITLE
Error npm install bcrypt-as-promised --save Im using windows 8.1

### ISSUE THREAD

**Issue by Ingosmar89219** [kelektiv/node.bcrypt.js#474]
C:\Users\osmarvirux>node -v
v6.9.4

C:\Users\osmarvirux>npm -v
3.10.9

C:\Users\osmarvirux>cd documents

C:\Users\osmarvirux\Documents>cd pagos_nodejs

C:\Users\osmarvirux\Documents\pagos_nodejs>cd recurringpayment
El sistema no puede encontrar la ruta especificada.

C:\Users\osmarvirux\Documents\pagos_nodejs>cd recurringpayments

C:\Users\osmarvirux\Documents\pagos_nodejs\RecurringPayments>npm install bcrypt-
as-promised --save

> bcrypt@0.8.7 install C:\Users\osmarvirux\Documents\pagos_nodejs\RecurringPayme
nts\node_modules\bcrypt
> node-gyp rebuild

C:\Users\osmarvirux\Documents\pagos_nodejs\RecurringPayments\node_modules\bcrypt
>if not defined npm_config_node_gyp (node "C:\Users\osmarvirux\AppData\Roaming\n
pm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.j
s" rebuild )  else (node "" rebuild )
Los proyectos de esta solución se van a compilar de uno en uno. Para habilitar l
a compilación en paralelo, agregue el modificador "/m".
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.Cpp.Platform.t
argets(42,5): error MSB8020: The builds tools for Visual Studio 2010 (Platform
Toolset = 'v100') cannot be found. To build using the v100 build tools, either
click the Project menu or right-click the solution, and then select "Update VC+
+ Projects...". Install Visual Studio 2010 to build using the Visual Studio 201
0 build tools. [C:\Users\osmarvirux\Documents\pagos_nodejs\RecurringPayments\no
de_modules\bcrypt\build\bcrypt_lib.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\osmarvirux\AppData\Roaming\n
pm\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:215:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\osmarvirux\\A
ppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.j
s" "rebuild"
gyp ERR! cwd C:\Users\osmarvirux\Documents\pagos_nodejs\RecurringPayments\node_m
odules\bcrypt
gyp ERR! node -v v6.9.4
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ch
okidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"
})
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\osmarvirux\\AppD
ata\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "bcrypt-as-prom
ised" "--save"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.8.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.7 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\osmarvirux\Documents\pagos_nodejs\RecurringPayments\npm-de
bug.log

**Comment by defunctzombie** [comment]
Please read the readme.
