### ISSUE TITLE
How can I fetch hash code from database and pass as input if my email and password is encrypted

### ISSUE THREAD

**Issue by AndroidHitchhiking** [kelektiv/node.bcrypt.js#477]
A situation happens when I store user information in case of signup with encrypted data using function `bcrypt.hash(myPlaintextPassword, saltRounds, function(err, hash) {
  // Store hash in your password DB.
});`

and now I need to login by email id and password which is inserted in DB as encrypted, So how can I use below function and pass hash code, because I don't have hash code and can not fetch it from DB (On what behalf?).
`bcrypt.compare(myPlaintextPassword, hash, function(err, res) {
    // res == true
});`

**Comment by Agathver** [comment]
Fetch the hash from the DB.

**Comment by AndroidHitchhiking** [comment]
@Agathver Thanks for response but in my case username is also a hash in my DB. In this situation I an note run `{ username: username }`

**Comment by Agathver** [comment]
That's is not how username password combinations are supposed to be stored. Username should use a deterministic storage. 

Anyways this is not an issue with the library. You should open a StackOverflow question.
