### ISSUE TITLE
Not able to install node version 6.0.0

### ISSUE THREAD

**Issue by kamal-bhatt** [kelektiv/node.bcrypt.js#484]
![image](https://cloud.githubusercontent.com/assets/22490116/22771723/a920ca58-eebe-11e6-9990-26c88b042c5c.png)

**Comment by sneakersgames** [comment]
Sure, lose it, sure. Maybe you could notice **a lot of people having this problem** and act on it. Maybe it's not an issue but something is not clear about this error for most people. Please advise!
