### ISSUE TITLE
The promise examples in the readme does not work

### ISSUE THREAD

**Issue by kevinsimper** [kelektiv/node.bcrypt.js#488]
Testcase here: https://runkit.com/58a5c3ae25e6da001336e711/58a5c3ae25e6da001336e712

```
var bcrypt = require("bcrypt")

bcrypt.hash('password', 'saltRounds').then(function(hash) {
    console.log(hash)
});
```

Returns undefined

**Comment by Agathver** [comment]
RunKit supports v0.8.7 which does not have promises.

**Comment by kevinsimper** [comment]
That is weird and I don't know how to change it :(
