### ISSUE TITLE
bcrypt DigitalOcean VM problem

### ISSUE THREAD

**Issue by lokk0** [kelektiv/node.bcrypt.js#498]
I have a problems with installing bcrypt on my vm on DigitalOcean. 
UBUNTU 16.04.2 x 64, Node (v6.10.0), npm (v 3.10.10)
It works perfectly on my mac, but I have such output in vm's terminal:
![zrzut ekranu 2017-03-16 o 21 52 24](https://cloud.githubusercontent.com/assets/16150083/24020416/f97db826-0a93-11e7-8b2c-9f2df22f2a1d.png)

Can you help?

Kind regards

**Comment by bondz** [comment]
related to #497

**Comment by Agathver** [comment]
Make sure you have installed the `build-essentials` package in ubuntu, as described in the README.

**Comment by lokk0** [comment]
Hi guys,
thanks for answers
the build-essentials has been already installed, but the error is still there. It looks like the install stops at 80% ant then there is an error.

![zrzut ekranu 2017-03-17 o 06 54 19](https://cloud.githubusercontent.com/assets/16150083/24032210/b301b0d2-0ade-11e7-9b8e-389ecb029093.png)

**Comment by lokk0** [comment]
This is the last log message:

![zrzut ekranu 2017-03-17 o 17 27 11](https://cloud.githubusercontent.com/assets/16150083/24055328/7da89c6c-0b37-11e7-945b-a0ccdecbf7f2.png)

**Comment by lokk0** [comment]
Here is the npm-debug.log

[debug-log.pdf](https://github.com/kelektiv/node.bcrypt.js/files/851946/debug-log.pdf)

**Comment by Agathver** [comment]
You need to install the `python` package as well. I looked into digital ocean VMs and they come with python3 by default. `node-gyp`, the package that builds node modules require python2.

**Comment by lokk0** [comment]
Thanks for your answers.
It looks like it is a dependencies problem.
I used bcryptjs (the one without dependencies) and it works ;)
