### ISSUE TITLE
BCRYPT module is not installing 

### ISSUE THREAD

**Issue by shobhit148** [kelektiv/node.bcrypt.js#501]
Hello BCRYPT team,

I am trying to use BCRYPT module but it is not getting installed, I tried every best solution and it is keep giving errors.

Below I am attaching a debug log please check that and let me know how to fix this, I am urgently in need of this.
[npm-debug.log.zip](https://github.com/kelektiv/node.bcrypt.js/files/860303/npm-debug.log.zip)

**Comment by Agathver** [comment]
See the README and https://github.com/kelektiv/node.bcrypt.js/wiki/Installation-Instructions

**Comment by akrumel** [comment]
Looks like you are trying to deploy on elastic beanstalk. Place the following in your project's '.ebextensions/app.config' file (you can change the file name):

packages:
   yum:
     gcc: []
     make: []
     openssl-devel: []
     libxml2: []
     libxml2-devel: []
     gcc-c++: []
     python27: []

Not sure if all packages required so you may be able to optimize. antwal's comment in [issue 476](https://github.com/kelektiv/node.bcrypt.js/issues/476) helped and I added the python27 package.

**Comment by tundrax** [comment]
When using Ansible, ``node-pre-gyp ERR!`` halts the playbook execution.

**Comment by Agathver** [comment]
@tundrax Ensure the following packages are present `python` `g++` and `make`.

**Comment by seonman** [comment]
As @akrumel mentioned above, adding '.ebextensions/app.config' makes everything OK.
But, you should be aware that AWS Beanstalk with t1.micro will cause the bcrypt installation error. After switching it to t2.small, I could find everything working well.
