### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by hackjus** [kelektiv/node.bcrypt.js#507]
cannot install it at all
here is logs

![Uploading dd.png…]()

**Comment by Haskaalo** [comment]
Hi there! There's no images so we can't really see what's your problem.

But make sure you've already installed what is listed [here](https://github.com/kelektiv/node.bcrypt.js/wiki/Installation-Instructions)

**Comment by hackjus** [comment]
![image](https://cloud.githubusercontent.com/assets/19831373/26277447/21a66222-3dba-11e7-8673-9453a89dd083.png)
![image](https://cloud.githubusercontent.com/assets/19831373/26277455/5778b6f2-3dba-11e7-96d6-21e9ab645ccf.png)
confused ?what happened? why ????

**Comment by Haskaalo** [comment]
Have you done `npm install --global --production windows-build-tools` on powershell with administrator permission? If yes then try running the install in admin. If it still fail, it might be a problem on your side because on the picture you sent us, it look like a problem with microsoft.NET

**Comment by Haskaalo** [comment]
You're also running an outdated version of npm, update npm with `npm install -g npm` and also install the latest version of node.js

**Comment by hackjus** [comment]
i tried npm instal --global ---production window-build-tools but faild to npm install anthing from package.json .  by the way i give it up !

**Comment by Haskaalo** [comment]
Your package.json must be broken, attach it

**Comment by Agathver** [comment]
You are using a very old version of bcrypt. Pre-built packages for it are not available and it fails to compile on newer node versions.

**Comment by Agathver** [comment]
Closing as issue was due to using very old version of bcrypt with unsatisfied dependencies
