### ISSUE TITLE
Wrong false result while compare

### ISSUE THREAD

**Issue by braska** [kelektiv/node.bcrypt.js#508]
I try to compare some hash generated by Python bcrypt lib or PHP password_hash function. For example:
```js
bcrypt.compare("123456", "$2b$12$Elajt8MG7thLN3D/PNiHpOn6LDuvMMyDLbB5hWiyggSpGuJsvgfGa", function(err, res) {console.log(res);});
```
or

```js
bcrypt.compare("123456", "$2b$12$23xBGadSp8LV9Iu/cR1Ame8/AtkrGMLJAh8Exh3mBOSWPdkvyTzUm", function(err, res) {console.log(res);});
```

or 

```js
bcrypt.compare("123456", "$2y$10$8ijLRibwngJRlXzETTaXhOy1FGimleQE8OEZq3R7FjI1ao8YFMsPW", function(err, res) {console.log(res);});
```

The result of this operation is false. But other implementations give `true`. For example, `bcryptjs` (node module), PHP impl, Python bcrypt lib, and different online services for checking bcrypt.

I try it on different platforms:
- Fedora 22 + Node v7.4.0
- Debian 8.7 + Node v7.9.0 (inside Docker container, host Fedora 22)
- Debian 8.7 + Node v7.9.0 (inside Docker container, host AWS Mody Linux (Alphine Linux))

**Comment by Agathver** [comment]
Out of all possible bcrypt version strings, this library only supports '$2a$'. The hash generated is almost identical for most of the uses except for passwords than 254. 

However, the library does not contain the code which has the aforementioned issue. Thus all `$2a$` `$2b$` and `$2y$` hashes should be compatible.

As a workaround, I would suggest replacing `$2y$` with `$2a$`.

**Comment by sergtop** [comment]
same problem with compare

had to add `.replace('$2y$','$2a$')` to my hash value before compare, and the reverse before DB save :(

**Comment by Agathver** [comment]
There are also issues regarding charsets. BCrypt is a byte-level encoder and knows nothing about the chars, and different charsets evaluate to differrent bytes for the same character.

**Comment by Agathver** [comment]
$2y$ is only specific to PHP https://security.stackexchange.com/questions/20541/insecure-versions-of-crypt-hashes. For all practical purposes replacing `y` with `a` should work, if the 2y hash was generated using the correct algorithm.
