### ISSUE TITLE
Please add node 8 prebuilt files.

### ISSUE THREAD

**Issue by JamesKyburz** [kelektiv/node.bcrypt.js#510]
Thanks for reporting a new issue with the node bcrypt module!

To help you resolve your issue faster please make sure you have done the following:

* Searched existing issues (even closed ones) for your same problem
* Make sure you have installed the required dependencies listed on the readme
* Read your npm error log for lines telling you what failed, usually it is a problem with not having the correct dependencies installed to build the native module

Once you have done the above and are still confident that the issue is with the module, please describe it below. Some things that really help get your issue resolved faster are:

* What went wrong?
* What did you expect to happen?
* Which version of nodejs and OS?
* If you find a bug, please write a failing test.

Thanks!

P.S. If it doesn't look like you read the above then your issue will likely be closed without further explanation. Sorry, but there are just too many issues opened with no useful information or questions which have been previously addressed.

**Comment by agauniyal** [comment]
There is a PR here - https://github.com/kelektiv/node.bcrypt.js/pull/511

**Comment by tobiasmuecksch** [comment]
Why isn't this merged yet?

**Comment by tobiasmuecksch** [comment]
With node 8.1.2 the auto-build works again for me. So the prebuilt files aren't necessary anymore.

**Comment by taojoe** [comment]
node 8.1.2 not work, prebuilt still needed.

**Comment by wyckster** [comment]
We experienced this issue with 8.1.3 today as well.  In the absence of prebuilt files, it tries to do some python stuff to build something but none of those steps worked (missing python).  We were running on Windows Server 2016 x64.  We even tried installing python and trying to go again, but it was literally calling "python" when it should have been calling "py".  I'm sure there were bigger issues, but that's as far as I got.

I can provide logs if anyone thinks it would help.

I assume this all goes away once prebuilt files are provided, so please do that.

**Comment by Agathver** [comment]
There are various reasons for node-gyp to fail on windows, providing pre-built windows binaries is a priority for us. The PR needs some work.

**Comment by Agathver** [comment]
@JamesKyburz @wyckster @taojoe  Pre-built windows binaries has been added
