### ISSUE TITLE
Install Fail on Centos v7

### ISSUE THREAD

**Issue by gtemme** [kelektiv/node.bcrypt.js#512]
Having issues installing bcrypt. It falls back to source compile.
I have installed the compilers required per the wiki instructions.
![image](https://cloud.githubusercontent.com/assets/24897228/26747866/9405671c-47ad-11e7-9303-4fbcecec0376.png)

Attached is install log, although I am not sure what is the actual problem. 
[npm-debug.txt](https://github.com/kelektiv/node.bcrypt.js/files/1049145/npm-debug.txt)

Also tried manually compiling, by 
cloning from git
cd into node.bcrypt.js directory
run node-gyp rebuild
But, this throws error:
Undefined variable module_name in binding.gyp while trying to load binding.gyp

Any assist is appreciated.

**Comment by Troepster** [comment]
+1

**Comment by Troepster** [comment]
Hi

I just got it to work
I cloned the repo then ran the following commands:
`node-pre-gyp configure`
`node-pre-gyp build`

**Comment by Agathver** [comment]
The `binding.gyp` and `nan` needs updating, there is a PR for it, but it is pending merge.

**Comment by Agathver** [comment]
It looks like you are trying to install the package in a directory owned by root or performing `npm install` under the user root (using su, or direct root login). `node-gyp` refuses to install under root permissions, [unless the `unsafe-perm` option is set](https://docs.npmjs.com/misc/config#unsafe-perm).
