### ISSUE TITLE
NodeJS 8 - Installation fails

### ISSUE THREAD

**Issue by tobiasmuecksch** [kelektiv/node.bcrypt.js#516]
Installation of version 1.0.2 fails on macOS 10.13 (Beta 1)

With this error message:

```
node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.2/bcrypt_lib-v1.0.2-node-v57-darwin-x64.tar.gz 
```

I made sure that the following packages are present and working: `python` `g++` and `make`

**EDIT:** Well, I found out, that after downgrading from Node 8.x to 7.10.0 the installation started working again. I guess this is error is somehow related to Node 8.x

**Comment by abarcenas29** [comment]
I also have the same error #517 on Heroku too.

**Comment by tobiasmuecksch** [comment]
@abarcenas29  I just found this manual entry:

https://github.com/kelektiv/node.bcrypt.js/wiki/Installation-Instructions

I will try to install the needed compilers on my Mac and then install it again. If that works I will close this issue.

**Comment by tobiasmuecksch** [comment]
Nope, that does not help :(

`python`, `g++` and `make` are present and working on my system...

**Comment by tobiasmuecksch** [comment]
Well, I found it that after downgrading from Node 8.x to 7.10.0 the installation started working again. I guess this is error is somehow related to Node 8.x
