### ISSUE TITLE
Error 404 :  npm install bcrypt on Debian 8

### ISSUE THREAD

**Issue by MatthieuHPP** [kelektiv/node.bcrypt.js#519]
Hi,

What went wrong: Failed at the bcrypt@1.0.2  via npm install bcrypt

What did you expect to happen: successfull installation of bcrypt

Which version of nodejs: node@6.11.0 and OS: Debian 8

Here is beginning of the error message
"node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.2/bcrypt_lib-v1.0.2-node-v48-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.2 and node@6.11.0 (node-v48 ABI) (falling back to source compile with node-gyp) "

I saw many threads mentioning this error but I did not find any solution yet.

Many thanks for you help.

Matthieu

**Comment by Agathver** [comment]
Install compilers as instructed in
https://github.com/kelektiv/node.bcrypt.js/wiki/Installation-Instructions

**Comment by MatthieuHPP** [comment]
Many thanks. It didier.mondelain@ujf-grenoble.fr not work for me. 
Matthieu
