### ISSUE TITLE
Issue while encoding the hash

### ISSUE THREAD

**Issue by 488kuroi** [kelektiv/node.bcrypt.js#522]
Hi there,

running the basic method ''bcrypt.hash"; the value returned as hash is different from what the blowfish logic expects.
In fact, the returned value from a salt like: **'$2a$05$a4uYRohrywB0ZwKfQXfSb$"**
with a string like **"prova3"**;
is returned as: "$2a$05$a4uYRohrywB0ZwKfQXfS[ __..__ ]gc2/i5lEWltPXeM7uP0V.FJtzdbF.ZO"
instead of: "$2a$05$a4uYRohrywB0ZwKfQXfS[ __b.__ ]gc2/i5lEWltPXeM7uP0V.FJtzdbF.ZO".

As you can see, in the square brackets, that there's a double dot, in the string and not only one after the salt string. 

The bug has been relevated in 0.8.7 and superior versions, on Windows and Linux OS.

Please fix this bug.

Kind regards,
Kuroi

**Comment by Agathver** [comment]
bcrypt expects a 128-bit (22 base64 chars) salt and the salt you have given here is of 21 character. Behaviour in this case is not defined. 

This implementation of bcrypt is based on the openbsd variant, and other libraries (like JTRs variant, used in PHP, for instance) handle these cases differently.
