### ISSUE TITLE
Unable to deploy app to heroku and bcrypt seems to be causing the issue

### ISSUE THREAD

**Issue by dsopel94** [kelektiv/node.bcrypt.js#523]
Hi, new programmer here and I am having issues with deploying an app to heroku. I'm using Windows 10 and node v6.9.4 and I get the error below. Any help would be appreaciated!

`remote: -----> Node.js app detected
remote:
remote: -----> Creating runtime environment
remote:
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        NPM_CONFIG_PRODUCTION=true
remote:        NPM_CONFIG_DISTURL=https://nodejs.org/download/release/
remote:        NODE_VERBOSE=false
remote:        NODE_ENV=production
remote:        NODE_MODULES_CACHE=true
remote:
remote: -----> Installing binaries
remote:        engines.node (package.json):  unspecified
remote:        engines.npm (package.json):   unspecified (use default)
remote:
remote:        Resolving node version 6.x via semver.io...
remote:        Downloading and installing node 6.11.0...
remote:        Using default npm version: 3.10.10
remote:
remote: -----> Restoring cache
remote:        Skipping cache restore (new-signature)
remote:
remote: -----> Building dependencies
remote:        Installing node modules (package.json)
remote:
remote:        > bcrypt@1.0.2 install /tmp/build_468255291043e02d6df9a5fb702a80de/node_modules/bcrypt
remote:        > node-pre-gyp install --fallback-to-build
remote:
remote:        node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.2/bcrypt_lib-v1.0.2-node-v48-linux-x64.tar.gz
remote:        node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.2 and node@6.11.0 (node-v48 ABI) (falling back to source compile with node-gyp)
remote:        make: Entering directory '/tmp/build_468255291043e02d6df9a5fb702a80de/node_modules/bcrypt/build'
remote:        CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
remote:        CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
remote:        CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
remote:        SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node
remote:        COPY Release/bcrypt_lib.node
remote:        COPY /tmp/build_468255291043e02d6df9a5fb702a80de/node_modules/bcrypt/lib/binding/bcrypt_lib.node
remote:        TOUCH Release/obj.target/action_after_build.stamp
remote:        make: Leaving directory '/tmp/build_468255291043e02d6df9a5fb702a80de/node_modules/bcrypt/build'`

**Comment by Agathver** [comment]
This does not seem like an error. From this part of the log, the installation of bcrypt appears to complete succesfully

**Comment by ericnograles** [comment]
@dsopel94 had this issue myself on occasion.  It'll slightly slow down your builds, but have you tried disabling the Node Modules Cache (set `NODE_MODULES_CACHE` to `false`)?  I've seen this happen with things like bcrypt and also node-sass where a binary needs to be reconstructed on each build...somehow, the caching sometimes screws things up.
