### ISSUE TITLE
Regular Expression Denial of Service (ReDoS) Vulnerability 

### ISSUE THREAD

**Issue by rokoroku** [kelektiv/node.bcrypt.js#526]
There is a vulnerability report on snyk (https://snyk.io/test/npm/bcrypt/1.0.2) with [`node-pre-gyp@0.6.32`](https://snyk.io/test/npm/node-pre-gyp/0.6.32), and has been resolved since [`node-pre-gyp@0.6.34`](https://snyk.io/test/npm/node-pre-gyp/0.6.34)

See  [CHANGELOG](https://github.com/mapbox/node-pre-gyp/blob/master/CHANGELOG.md#0634) of `node-pre-gyp@0.6.34`.

**Comment by Agathver** [comment]
Thanks for reporting. However, this does not affect the normal usage of the library as node-pre-gyp is used only during installation.

**Comment by Agathver** [comment]
Latest changes have been merged to master which updates node-pre-gyp to 0.6.36, that resolves the issue.

**Comment by sammarks** [comment]
Can we get a release with this change included?

**Comment by agathver** [comment]
I will make a release soon.
However, this is nothing critical.
