### ISSUE TITLE
Fallback to source compile if pre-built module is ABI incompatible

### ISSUE THREAD

**Issue by agathver** [kelektiv/node.bcrypt.js#530]
A pre-built module which is ABI incompatible should be detected and the installation should perform a source build. Needed for Alpine Linux Docker images.

Related issues:
#528 

Waiting for:
https://github.com/mapbox/node-pre-gyp/issues/309

**Comment by Nopik** [comment]
The mapbox/node-pre-gyp seems to be closed now?

**Comment by agathver** [comment]
We now have libc aware binaries
