### ISSUE TITLE
How is this secure?

### ISSUE THREAD

**Issue by wbhob** [kelektiv/node.bcrypt.js#532]
Thanks for reporting a new issue with the node bcrypt module!

To help you resolve your issue faster please make sure you have done the following:

* Searched existing issues (even closed ones) for your same problem
* Make sure you have installed the required dependencies listed on the readme
* Read your npm error log for lines telling you what failed, usually it is a problem with not having the correct dependencies installed to build the native module

Once you have done the above and are still confident that the issue is with the module, please describe it below. Some things that really help get your issue resolved faster are:

* What went wrong?
Salts are simply prepended to hashes. I'm worried about this, because in theory, someone could strip out the first 30 characters, and use a rainbow table against the password to get the original value.
* What did you expect to happen?
I would expect the salt to be baked into the hash.
* Which version of nodejs and OS?
Node 8.1.3, macOS 10.12
* If you find a bug, please write a failing test.

Thanks!

P.S. If it doesn't look like you read the above then your issue will likely be closed without further explanation. Sorry, but there are just too many issues opened with no useful information or questions which have been previously addressed.

**Comment by wbhob** [comment]
What I mean by this, is that instead of operating: `Hash(salt||password)`, the operation is `salt||Hash(password)`.

**Comment by wbhob** [comment]
Nevermind, I was wrong... sorry

**Comment by tborychowski** [comment]
Hi @wbhob, would you mind explaining more? I have the same concerns.
i.e. if I have a hash - I can run `bcrypt.compare` against the rainbow table, no?

**Comment by wbhob** [comment]
you could do that, but the reason hackers have rainbow tables is quick lookups. since bcrypt is a slow hashing fuction, it will take an inconceivable amount of time to check all the passwords in a rainbow table. so to answer your question, yes, they could compare against EVERY rainbow table entry, but even with powerful computers, it would take infinitely long to find a match

**Comment by tborychowski** [comment]
ok, I see. Thanks!

**Comment by agathver** [comment]
@tborychowski 
Rainbow tables like a hash table of hash => plaintext for a particular hashing algorithm. In modern hashes, a random value called salt is appended to the password before hashing. Thus, the same plain text always gives different values. This renders rainbow tables useless.

**Comment by tborychowski** [comment]
@agathver  sorry, you're right, I meant plaint text password lists (to compare plaintext passwords using `bcrypt.compare()` with the hashed ones)
