### ISSUE TITLE
Non-deterministic behaviour with broken salt

### ISSUE THREAD

**Issue by jkozak** [kelektiv/node.bcrypt.js#533]
I am trying to create a salt from a private entropy pool.  I did this using `Buffer.toString('base64')` which I discover is not the same base64 encoding that bcrypt uses.  This is my problem,obviously.

But, the broken salt generated above `$2a$08$AW+W7bhRA/wdtMNJe00IPg` has extremely perverse qualities; it generates different hashes at different invocations!  Looking at `bcrypt.cc`, `decode_base64` fails silently on finding the bad char `+`  and the code continues with whatever was already in memory instead.

`bcrypt-js`, by comparison flags this as an error, which I believe `bcrypt` should also.

**Comment by agathver** [comment]
Thanks for pointing out! 

`bcrypt.cc` is mostly unmodified OpenBSD code.

**Comment by agathver** [comment]
All implementations of bcrypt do have undefined behaviour when the salt is outside `/[0-9a-zA-Z]+/`

Its a thing worth mentioning in the docs.
