### ISSUE TITLE
question: will hash length always be 60 characters long?

### ISSUE THREAD

**Issue by nxmohamad** [kelektiv/node.bcrypt.js#534]
not an issue, but a question.

I am trying to create tests for my function that uses bcrypt. Code below:
```
function hashPassword(password, cb) {
  // Generate a salt at level 10 strength
  bcrypt.genSalt(10, (err, salt) => {
    bcrypt.hash(password, salt, (err, hash) => {
      return cb(err, hash)
    });
  });
};
```

My question is that, will the hash always be 60 characters? Or is that also dependent on the level of the salt?

**Comment by agathver** [comment]
By bcrypt specification, the generated hash, in base64 will be 53 characters, rest make for the mcf hash identifier and hash cost. And that will be 60 for quite a long time, unless we need a hash cost of 100 which is a _very very big number_

https://security.stackexchange.com/questions/17207/recommended-of-rounds-for-bcrypt.

_The age of universe is about 4.17e+17 while 2^100 = 1.267e+30_

**Comment by nxmohamad** [comment]
Thank you so much @agathver :) Learnt something new today

**Comment by Quadriphobs1** [comment]
Hi @agathver, I am down with a challenge, I am using bcrypt to hash password, however, the database field expect on 50 characters at maximum, how do I set the length I want because this would not give me the expected result as when saved part of it would be lost and won't be able to compare to original password again

**Comment by TheWithz** [comment]
@Quadriphobs1 I might be too late, but bcrypt output can be reduced to 40 bytes https://stackoverflow.com/a/5882472
