### ISSUE TITLE
Comparing return false, even if password are matched

### ISSUE THREAD

**Issue by iamdubx** [kelektiv/node.bcrypt.js#535]
Hello. I don't know what could go wrong. But the comparing is failed for me:

```
userSchema.methods.comparePassword = function (candidatePassword, cb) {
  bcrypt.compare(candidatePassword, this.password, function (err, isMatch) {
    if (err) {
      console.log('err')
      return cb (err)
    }
    console.log(candidatePassword)
    console.log(isMatch)
    cb (null, isMatch)
  })
}
```

The most strange part, that a week ago everything worked just fine. No changes was implemented. The `candidatePassword` is passing correctly, but `isMatch` is return false. Please help me.

**Comment by iamdubx** [comment]
I assume it can't access `this.password` but why???

**Comment by agathver** [comment]
Perhaps your issue is with `this`
I think you assume the behavior `this` as it is exhibited in Java. JS is different https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/this

**Comment by iamdubx** [comment]
Sorry, my issue wasn't related to this awesome lib!
