### ISSUE TITLE
publish node 8 compatibility

### ISSUE THREAD

**Issue by bobzoller** [kelektiv/node.bcrypt.js#536]
Seems like some Node 8 issues were fixed in #527 but they have not been published to npm yet.

**Comment by bobzoller** [comment]
On second glance the changes are mostly around CI and 1.0.2 seems to work fine on Node 8... but still, probably valid to publish the dependencies change, yeah?

**Comment by agathver** [comment]
Most issues were really about missing compiled native libs, so a release is not necessary now. There are some other issues like testing download binaries that we would like to fix, before the release.

And perhaps, the next major release could be based on NAPI  See: #513

**Comment by ncb000gt** [comment]
Published to npm.
