### ISSUE TITLE
ERR! Tried to download(404): bcrypt_lib-v1.0.3-node-v57-darwin-x64.tar.gz

### ISSUE THREAD

**Issue by iTonyYo** [kelektiv/node.bcrypt.js#537]
macosSierra@10.12.5
python@2.7.10
node.js@8.4.0
node-gyp@3.6.2
node-pre-gyp@0.6.36

![image](https://user-images.githubusercontent.com/5499703/29662171-f9c04490-888b-11e7-8d4a-b9101edf5248.png)

**Comment by sladg** [comment]
Same here for Fedora 26 using NVM.

`node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.3/bcrypt_lib-v1.0.3-node-v57-linux-x64.tar.gz `
Looks like download links has been changed?

[Current Links](https://github.com/kelektiv/node.bcrypt.js/releases/v1.0.3)

**Comment by agathver** [comment]
You are missing devtools in your system. You will find installation issues and solutions here.
https://github.com/kelektiv/node.bcrypt.js/wiki/Installation-Instructions

**Comment by nathanbuchar** [comment]
I too am encountering this trying to install `bcrypt@1.0.3`

macOS Sierra@10.12.6
node@8.4.0
npm@5.3.0

As mentioned above, `npm i bcrypt@1.0.2` runs without issues.

**Comment by agathver** [comment]
Apparently there was a new release and the native binaries are not yet uploaded. I'm currently away from my machine and upload new ones when I'm available.

**Comment by nathanbuchar** [comment]
Thanks, @agathver :)

**Comment by iTonyYo** [comment]
Thanks a lot! @agathver

**Comment by mundipf** [comment]
This is still happening.

**Comment by FIZLIN** [comment]
I'm experiencing this no matter the version of crypt.

**Comment by preillyme** [comment]
When will ```node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.3/bcrypt_lib-v1.0.3-node-v59-darwin-x64.tar.gz``` be fixed? Can someone please upload new native binaries.

**Comment by ahaidery19** [comment]
Also getting the same issue as preillyme -- any update on when the new native binaries will be uploaded?

**Comment by cesar3030** [comment]
Same issue for me as well

**Comment by nicofr83** [comment]
same issue ....

**Comment by ahaidery19** [comment]
a workaround for me that worked was to use:

yarn global add node-gyp

(will need yarn for this first)

**Comment by nicofr83** [comment]
Thanks

**Comment by anguyen09** [comment]
@ahaidery19 This worked for me as well

**Comment by praveen399** [comment]
same issue here

**Comment by dashko** [comment]
This is still an issue.

**Comment by keith24** [comment]
This repo doesn't even have releases enabled at this time.

**Comment by agathver** [comment]
Pre-built binaries are available: https://github.com/kelektiv/node.bcrypt.js/releases/tag/v3.0.0
It takes time to upload them and are provided on a best-effort basis. The recommended way it to source compile and it just needs a C compiler, the instructions to do so are even clearly mentioned in the readme. (https://github.com/kelektiv/node.bcrypt.js/wiki/Installation-Instructions)

If there is still an install error, open a new issue instead of resurrecting old ones.
