### ISSUE TITLE
Windows binaries

### ISSUE THREAD

**Issue by twentic** [kelektiv/node.bcrypt.js#540]
When installing bcrypt in windows, shows an error that doesn't found the downloads for 1.0.3:

`meteor npm install --save bcrypt`

> bcrypt@1.0.3 install C:\TEST\node_modules\bcrypt
> node-pre-gyp install --fallback-to-build

`node-pre-gyp ERR! Tried to download(502): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.3/bcrypt_lib-v1.0.3-node-v46-win32-ia32.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.3 and node@4.8.4 (node-v46 ABI) (falling back to source compile with node-gyp)
`

Can you add to the downloads for the 1.0.3 release please?

**Comment by xjose97x** [comment]
@agathver any update here?
Yesterday I tried to install bcrypt through npm in windows, and failed as well. Are there any workarounds for this?

Thanks in advance.

**Comment by boybundit** [comment]
@xjose97x I have to use `v1.0.2` in the mean time.
```sh
npm install bcrypt@1.0.2
```
You can force fixed version in `package.json` by removing `^` prefix.
```json
"dependencies": {
  "bcrypt": "1.0.2"
}
```

**Comment by mrexodia** [comment]
Would be nice if you could trigger the build again...

**Comment by AlexanderYW** [comment]
I have the same issue with the "v48" for "v1.0.3". I'm "forced" to downgrade to "v1.0.2" too

Sadly this took me hours to realise because i was tired :(

**Comment by agathver** [comment]
The latest appveyor build has pushed all binaries for all node versions, this issue should be fixed now.

**Comment by justbill2020** [comment]
I'm also having an issue with this. 

[2017-09-26T14_01_27_823Z-debug.log](https://github.com/kelektiv/node.bcrypt.js/files/1333437/2017-09-26T14_01_27_823Z-debug.log)

**Comment by agathver** [comment]
@justbill2020 It seems you have issues with your NodeJS installation. May be the PATH isn't configured properly
