### ISSUE TITLE
invalid salt in hash fn

### ISSUE THREAD

**Issue by paulddrix** [kelektiv/node.bcrypt.js#543]
I tried to hash a password async and providing a string such as 'hello' to be the salt, and this is the returned error:

Invalid Salt. Salt must be in the form of: $Ver$logs(NumRounds)$saltvalue

This is what the docs say about the salt, however it does not show what happens if you do not specify a number.

salt - [REQUIRED] - the salt to be used to hash the password. if specified as a number then a salt will be generated with the specified number of rounds and used (see example under Usage).

nodejs vsersion = v6.9.1 
OS =MAC OS X V10.12.6 
  
Thank for for your time, I was thinking of having the user provide the salt every time so that I don't have to save it in the DB, the password would be hashed before leaving the client

**Comment by agathver** [comment]
The required salt must be in the format of `$2a$<rounds>$<salt>`
The recommended is to  pass the number of rounds so as to generate the salt automatically. 

The salt must be a 128 bit base64 encoded value (22 chars).

>Thank for for your time, I was thinking of having the user provide the salt every time so that I don't have to save it in the DB, the password would be hashed before leaving the client

The generated hash from bcrypt will contain the hash anyway. You may need to strip the salt in that case. It seems you may be trying to implement some form of [digest authentication](https://en.wikipedia.org/wiki/Digest_access_authentication)

**Comment by paulddrix** [comment]
So if I base64 encode the salt(a string) provided by the user, then I can hash the password and send over the password hash to the server where I have one to match it against.

**Comment by agathver** [comment]
Yes. The value should be 128-bit though. Assuming ASCII, the value should be 16 characters.
