### ISSUE TITLE
bcrypt fails to compile on FreeBSD 11

### ISSUE THREAD

**Issue by randomnonsense** [kelektiv/node.bcrypt.js#552]
There's a problem with "_LIBCPP_TRIVIAL_PAIR_COPY_CTOR" due to changes in FreeBSD's ABI, as explained here: https://reviews.llvm.org/D21329 what effectively breaks compiling of bcrypt

![bcrypt](https://user-images.githubusercontent.com/31191881/31848308-efd5a656-b62f-11e7-8f3a-66ea91bc36f3.png)

Any advice how to work around this is welcome. Obviously there's always the way to manually modify the source and compile directly, but I am completely unfamiliar with node and its related projects. I was supposed to auto-install bcrypt using npm. Any hints will do. Many thanks in advance.

In case of particular projects, this disabled the whole FreeBSD usebase from using e.g. https://github.com/jfurrow/flood

**Comment by agathver** [comment]
I've never used BSD before, but I think, there must be a libcpp-compat library somewhere. The error messages shown here tells that there is some error in "stdio.h". 

Or it may be possible that your headers and LLVM version are out-of-sync.

**Comment by randomnonsense** [comment]
Take a look at the llvm discussion (linked) please. FreeBSD guys removed support for non-trivial pair copy constructors (which bcrypt apparently still uses) from the ABI.

**Comment by agathver** [comment]
> Take a look at the llvm discussion (linked) please. FreeBSD guys removed support for non-trivial pair copy constructors (which bcrypt apparently still uses) from the ABI.

We do not use `std::pair` anywhere. And the message says:

...
In file included from /usr/include/c++/v1/stdio.h:102
/usr/include/c++/v1/ config:73:2: error: ...
```

I'll try to reproduce this in a FreeBSD box soon.

**Comment by randomnonsense** [comment]
> We do not use std::pair anywhere. And the message says:
> `... In file included from /usr/include/c++/v1/stdio.h:10 ...`

My understanding is that this is the __config file described and reworked by https://reviews.llvm.org/D21329 (see the very first file which received commits in that thread) which instructs the compiler to throw an error if it stumbles on something it is not supposed to, and in this case, what it does is "disabling pre ABI v1 features. All of these options are deprecated". Correct me if I am wrong.

**Comment by agathver** [comment]
`_LIBCPP_TRIVIAL_PAIR_COPY_CTOR` it neither defined in bcrypt or in https://github.com/nodejs/nan (another native package we depend on).

I cannot figure out where does this get defined.

If you could upload your npm-debug.log, it may help to shed some more light on this

**Comment by agathver** [comment]
@randomnonsense I fetched a fresh FreeBSD iso, installed node from ports and tried to run `npm install bcrypt` as well as couple of NodeJS apps that use bcrypt, all of then worked fine

**Comment by randomnonsense** [comment]
Yes, if you use node6-6.11.3_1 and npm3-3.10.10_2. Flood **requires "NodeJS 7 or higher**. See its project page. The upgrade was just announced by the author. Can flood build using node6? Yes, **for now**.

 Install "node" which is the current node 8.6.0, not "node6", and see bcrypt failing as I reported above.

**Comment by randomnonsense** [comment]
Please list your steps on FreeBSD. Using the current stable node 8.6.0 and npm 5.4.2 installed via the standard package manager bcrypt fails to compile, as originally reported.

**Comment by agathver** [comment]
Using FreeBSD 11.1
Installed node from ports www/node which gives NodeJS 8.6 and NPM 5.4.2
npm init
npm install bcrypt

This shows an error about FreeBSD binaries not available and then compiles

I also tried this with node6 and npm 3 from ports

**Comment by agathver** [comment]
It's strange to face this error on FreeBSD. Apple also uses the same Clang (with that patch included) and it installs just fine.

It's also strange as bcrypt code does not include any of the mentioned deprecated code anywhere.

**Comment by agathver** [comment]
Closing the issue, as unable to replicate.
@randomnonsense I think, your system headers and clang may be out-of-sync.

**Comment by randomnonsense** [comment]
Only today I had time to test this further. The outcome is puzzling, but at least its clear what to do:

If you install node from packages (pkg install node), bcrypt fails to compile. Error as originally reported. [i]Howerver[/i], if you make install node from ports (www/node), everything works fine. 

First time I am seeing a discrepancy like this. Likely, the problem is the environment compiling the node port for the package system, i.e. linked against obsoleted libs? I am guessing here.

Anyway, the solution is: Do not install node from packages. Build the port yourself.
