### ISSUE TITLE
Tried to download(undefined): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.3/bcrypt_lib-v1.0.3-node-v48-win32-x64.tar.gz

### ISSUE THREAD

**Issue by edelCustodio** [kelektiv/node.bcrypt.js#556]
I have been had this issue when I have tried to install the latest version of bcrypt. Someone could help me with this?

$ npm install bcrypt --save

> bcrypt@1.0.3 install C:\Users\Edel Custodio Frias\Documents\Electron\cyber-server\node_modules\bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(undefined): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.3/bcrypt_lib-v1.0.3-node-v48-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.3 and node@6.11.5 (node-v48 ABI) (falling back to source compile with node-gyp)

C:\Users\Edel Custodio Frias\Documents\Electron\cyber-server\node_modules\bcrypt>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bi
n\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean )

C:\Users\Edel Custodio Frias\Documents\Electron\cyber-server\node_modules\bcrypt>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bi
n\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build "--module=C:\Users\Edel Custodio Frias\Documents\Electron\cyber-server\node_modul
es\bcrypt\lib\binding\bcrypt_lib.node" --module_name=bcrypt_lib "--module_path=C:\Users\Edel Custodio Frias\Documents\Electron\cyber-server\node_modules\bcrypt\lib\binding"
 )  else (node "" configure --fallback-to-build "--module=C:\Users\Edel Custodio Frias\Documents\Electron\cyber-server\node_modules\bcrypt\lib\binding\bcrypt_lib.node" --mo
dule_name=bcrypt_lib "--module_path=C:\Users\Edel Custodio Frias\Documents\Electron\cyber-server\node_modules\bcrypt\lib\binding" )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--f
allback-to-build" "--module=C:\\Users\\Edel Custodio Frias\\Documents\\Electron\\cyber-server\\node_modules\\bcrypt\\lib\\binding\\bcrypt_lib.node" "--module_name=bcrypt_li
b" "--module_path=C:\\Users\\Edel Custodio Frias\\Documents\\Electron\\cyber-server\\node_modules\\bcrypt\\lib\\binding"
gyp ERR! cwd C:\Users\Edel Custodio Frias\Documents\Electron\cyber-server\node_modules\bcrypt
gyp ERR! node -v v6.11.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\Edel Custodio Frias\Documents\Electron\cyber-server\node_modu
les\bcrypt\lib\binding\bcrypt_lib.node --module_name=bcrypt_lib --module_path=C:\Users\Edel Custodio Frias\Documents\Electron\cyber-server\node_modules\bcrypt\lib\binding'
(1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Edel Custodio Frias\Documents\Electron\cyber-server\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:920:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
node-pre-gyp ERR! System Windows_NT 10.0.15063
node-pre-gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\Edel Custodio Frias\\Documents\\Electron\\cyber-server\\node_modules\\node-pre-gyp\\bin\\n
ode-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\Edel Custodio Frias\Documents\Electron\cyber-server\node_modules\bcrypt
node-pre-gyp ERR! node -v v6.11.5
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\Edel Custodio Frias\Documents\Electron\cyber-server\node_modules\bcrypt\lib\binding\bcrypt_l
ib.node --module_name=bcrypt_lib --module_path=C:\Users\Edel Custodio Frias\Documents\Electron\cyber-server\node_modules\bcrypt\lib\binding' (1)
npm WARN cyber-server@1.1.1 No description
npm WARN cyber-server@1.1.1 No repository field.
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "bcrypt" "--save"
npm ERR! node v6.11.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@1.0.3 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@1.0.3 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

**Comment by agathver** [comment]
Well, the link works, and the pre-compiled module exists. Looks like you have some proxy or other communication issues.

**Comment by julien-f** [comment]
Same issue here, no proxy and no recent changes, it worked before.

**Comment by jrpool** [comment]
I, similarly, am getting:
```
Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.3/bcrypt_lib-v1.0.3-node-v59-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.3 and node@9.0.0 (node-v59 ABI) (falling back to source compile with node-gyp)
```

**Comment by agathver** [comment]
@jrpool Node 9 has issues with npm which causes our build to fail. We are unable to provide prebuilt packages for it at the moment. See https://github.com/npm/npm/issues/19143

**Comment by agathver** [comment]
@edelCustodio 
````
node-pre-gyp ERR! Tried to download(undefined):
````
This only happens on a network error. In other cases, there is always an error code.
