### ISSUE TITLE
bcrypt not getting compiled on Node 8.8.1 on AWS AMI

### ISSUE THREAD

**Issue by lajpatshah** [kelektiv/node.bcrypt.js#560]
I tried to install gcc as well yet it is not compiling.

Please guide as to how do I install bcrypt on my environment

**Comment by agathver** [comment]
https://github.com/kelektiv/node.bcrypt.js/wiki/Installation-Instructions

**Comment by agathver** [comment]
Node.JS 8.x on AWS certainly doesn't require you to install a compile bcrypt on the host. Check if there are other problems as well.

**Comment by lajpatshah** [comment]
hi are the pre built libraries made available for node 8.8.1????

**Comment by agathver** [comment]
@lajpatshah Yeah, since quite a while

**Comment by lajpatshah** [comment]
Sorry to keep on troubling with same issue but while installing bcrypt i am getting below error...can you plz help? i am using amazon ami

3061 silly install bcrypt@1.0.3
3062 info lifecycle bcrypt@1.0.3~install: bcrypt@1.0.3
3063 verbose lifecycle bcrypt@1.0.3~install: unsafe-perm in lifecycle false
3064 verbose lifecycle bcrypt@1.0.3~install: PATH: /opt/elasticbeanstalk/node-install/node-v8.8.1-linux-x64/lib/node_modules/npm/bin/node-gyp-bin:/tmp/deployment/application/node_modules/bcrypt/node_modules/.bin:/tmp/deployment/application/node_modules/.bin:/opt/elasticbeanstalk/node-install/node-v8.8.1-linux-x64/bin:/opt/elasticbeanstalk/lib/ruby/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin
3065 verbose lifecycle bcrypt@1.0.3~install: CWD: /tmp/deployment/application/node_modules/bcrypt
3066 silly lifecycle bcrypt@1.0.3~install: Args: [ '-c', 'node-pre-gyp install --fallback-to-build' ]
3067 silly lifecycle bcrypt@1.0.3~install: Returned: code: 1  signal: null
3068 info lifecycle bcrypt@1.0.3~install: Failed to exec install script
3069 verbose unlock done using /tmp/.npm/_locks/staging-6d252812679aa9c6.lock for /tmp/deployment/application/node_modules/.staging
3070 verbose stack Error: bcrypt@1.0.3 install: `node-pre-gyp install --fallback-to-build`
3070 verbose stack Exit status 1
3070 verbose stack     at EventEmitter.<anonymous> (/opt/elasticbeanstalk/node-install/node-v8.8.1-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
3070 verbose stack     at emitTwo (events.js:125:13)
3070 verbose stack     at EventEmitter.emit (events.js:213:7)
3070 verbose stack     at ChildProcess.<anonymous> (/opt/elasticbeanstalk/node-install/node-v8.8.1-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
3070 verbose stack     at emitTwo (events.js:125:13)
3070 verbose stack     at ChildProcess.emit (events.js:213:7)
3070 verbose stack     at maybeClose (internal/child_process.js:927:16)
3070 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
3071 verbose pkgid bcrypt@1.0.3
3072 verbose cwd /tmp/deployment/application
3073 verbose Linux 4.9.77-31.58.amzn1.x86_64
3074 verbose argv "/opt/elasticbeanstalk/node-install/node-v8.8.1-linux-x64/bin/node" "/opt/elasticbeanstalk/node-install/node-v8.8.1-linux-x64/bin/npm" "--production" "install"
3075 verbose node v8.8.1
3076 verbose npm  v5.4.2
3077 error code ELIFECYCLE
3078 error errno 1
3079 error bcrypt@1.0.3 install: `node-pre-gyp install --fallback-to-build`
3079 error Exit status 1
3080 error Failed at the bcrypt@1.0.3 install script.
3080 error This is probably not a problem with npm. There is likely additional logging output above.
3081 verbose exit [ 1, true ]
