### ISSUE TITLE
bcrypt install on windows 8.1 64bit

### ISSUE THREAD

**Issue by vikaskhamkar24** [kelektiv/node.bcrypt.js#561]
I am trying to install bcrypt on windows 8.1 64 bit
npm install bcrypt 
but I am getting following error

> \qsi_support\Q_Support_System\support_portal\node_modules\bcrypt>if not define
npm_config_node_gyp (node "C:\Users\Administrator\AppData\Roaming\nvm\v8.3.0\n
e_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" r
uild )  else (node "" rebuild )
ilding the projects in this solution one at a time. To enable parallel build,
ease add the "/m" switch.
\qsi_support\Q_Support_System\support_portal\node_modules\bcrypt\build\bcrypt
ib.vcxproj(20,3): error MSB4019: The imported project "F:\Microsoft.Cpp.Defau
.props" was not found. Confirm that the path in the <Import> declaration is c
rect, and that the file exists on disk.
p ERR! build error
p ERR! stack Error: `msbuild` failed with exit code: 1
p ERR! stack     at ChildProcess.onExit (C:\Users\Administrator\AppData\Roamin
nvm\v8.3.0\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
p ERR! stack     at emitTwo (events.js:125:13)
p ERR! stack     at ChildProcess.emit (events.js:213:7)
p ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
js:200:12)
p ERR! System Windows_NT 6.2.9200
p ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator
AppData\\Roaming\\nvm\\v8.3.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\
ode-gyp.js" "rebuild"
p ERR! cwd F:\qsi_support\Q_Support_System\support_portal\node_modules\bcrypt
p ERR! node -v v8.3.0
p ERR! node-gyp -v v3.6.2
p ERR! not ok
m WARN Error: EPERM: operation not permitted, lstat 'F:\qsi_support\Q_Support_
stem\support_portal\node_modules\fsevents\node_modules'
m WARN  { Error: EPERM: operation not permitted, lstat 'F:\qsi_support\Q_Suppo
_System\support_portal\node_modules\fsevents\node_modules'
m WARN   stack: 'Error: EPERM: operation not permitted, lstat \'F:\\qsi_suppor
\Q_Support_System\\support_portal\\node_modules\\fsevents\\node_modules\'',
m WARN   errno: -4048,
m WARN   code: 'EPERM',
m WARN   syscall: 'lstat',
m WARN   path: 'F:\\qsi_support\\Q_Support_System\\support_portal\\node_module
\fsevents\\node_modules' }
m ERR! code ELIFECYCLE
m ERR! errno 1
m ERR! bcrypt@0.8.7 install: `node-gyp rebuild`
m ERR! Exit status 1
m ERR!
m ERR! Failed at the bcrypt@0.8.7 install script.
m ERR! This is probably not a problem with npm. There is likely additional log
ng output above.
m ERR! A complete log of this run can be found in:
m ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2017-12-01T1
22_51_457Z-debug.log

>

**Comment by agathver** [comment]
Please update to bcrypt v1.0.2
