### ISSUE TITLE
pre-built bcrypt binaries

### ISSUE THREAD

**Issue by Mwaiwathu** [kelektiv/node.bcrypt.js#567]
Bcrypt is a binary and depends on node-gyp . But especially in shared node servers with no shell support or compiler tools can't the module have pre built binaries for popular architectures and fall back of node-gyp when such binaries are not available.

Baking my own build is a non starter as the target server may have different architecture from my build environment.

**Comment by agathver** [comment]
Prebuilt binaries are missing for node 9 only. There are bugs in node 9 and npm that fails constantly in our CI to generate binaries. There is nothing much we can do about it currently other that waiting for a fix. 

I would advice you to stick with node 8. 9 still had bugs here and there.
