### ISSUE TITLE
getting errors while trying to install on express nodejs windows 10

### ISSUE THREAD

**Issue by waqasraza123** [kelektiv/node.bcrypt.js#570]
I am getting following errors while trying to install the package.

`npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Error: EPERM: operation not permitted, rename '.....\node_modules\fsevents' -> '.....\node_modules\.fsevents.DELETE'
npm ERR! path .....\node_modules\gauge
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename
npm ERR! Error: EPERM: operation not permitted, rename '.....\node_modules\gauge' -> '.....\node_modules\.gauge.DELETE'
npm ERR!  { Error: EPERM: operation not permitted, rename '.....\node_modules\gauge' -> '.....\node_modules\.gauge.DELETE'
npm ERR!   cause:
npm ERR!    { Error: EPERM: operation not permitted, rename '.....\node_modules\gauge' -> '.....\node_modules\.gauge.DELETE'
npm ERR!      errno: -4048,
npm ERR!      code: 'EPERM',
npm ERR!      syscall: 'rename',
npm ERR!      path: '.....\\node_modules\\gauge',
npm ERR!      dest: '.....\\node_modules\\.gauge.DELETE' },
npm ERR!   stack: 'Error: EPERM: operation not permitted, rename \'.....\\node_modules\\gauge\' -> \'.....\\node_modules\\.gauge.DELETE\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path: '.....\\node_modules\\gauge',
npm ERR!   dest: '.....\\node_modules\\.gauge.DELETE',
npm ERR!   parent: 'server' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     .....\AppData\Roaming\npm-cache\_logs\2018-01-15T01_16_28_718Z-debug.log`

**Comment by agathver** [comment]
Looks like you  have some permission issues related to module 'gauge'
