### ISSUE TITLE
bcrypt.compareAsync(password, this.password) always returning false

### ISSUE THREAD

**Issue by tribhuwank** [kelektiv/node.bcrypt.js#574]
const Promise = require('bluebird')
const bcrypt = Promise.promisifyAll(require('bcrypt-nodejs'))

function hashPassword (user, options) {
  const SALT_FACTOR = 8

  if (!user.changed('password')) {
    return
  }

  return bcrypt
    .genSaltAsync(SALT_FACTOR)
    .then(salt => bcrypt.hashAsync(user.password, salt, null))
    .then(hash => {
      user.setDataValue('password', hash)
    })
}

module.exports = (sequelize, DataTypes) => {
  const User = sequelize.define('User', {
    name: {
      type:DataTypes.STRING,
      allowNull: false
    },
    email: {
      type: DataTypes.STRING,
      unique: true,
      allowNull: false
    },    
    mobile: {
      type:DataTypes.STRING,
      allowNull: false
    },
    gender: {
        type: DataTypes.BOOLEAN,
        allowNull: false,
        defaultValue: true
      },
    age:DataTypes.INTEGER,
    password:{
      type: DataTypes.STRING,
      allowNull: false
    }
   
  }, {
    hooks: {
     beforeSave: hashPassword
    }
  })

  User.prototype.comparePassword = function (password) {
    return bcrypt.compareAsync(password, this.password)
  }

  User.associate = function (models) {
  }

  return User
}

This code giving false always once i used comparePassword 

const isPasswordValid = await user.comparePassword(password)
      if (!isPasswordValid) {
        return res.status(403).send({
          error: 'The login information was incorrect'
        })
      }

**Comment by agathver** [comment]
Wrong library.
This is 'bcrypt'
