### ISSUE TITLE
Security issue in hoek 4.2.0 lib

### ISSUE THREAD

**Issue by ralphkocher** [kelektiv/node.bcrypt.js#581]
bcrypt 1.0.3 uses the hoek 4.2.0 lib. This version of hoek has an security issue (Prototype pollution attack). Issue is fixed in hoek 5.0.3. Is it possible to update hoek at bcrypt?

More Info: https://nodesecurity.io/advisories/566

**Comment by agathver** [comment]
@ralphkocher Thanks for reporting this. 

We do not depend on any library during normal operation of bcrypt, apart from `node-pre-gyp` where a hard-coded string is always passed as input. This vulnerability is very unlikey to affect us, no user input ever touches any third party code.

Some updates are due, we'll publish a new version with all these changes.

**Comment by agathver** [comment]
Fixed
