### ISSUE TITLE
bcrypt@1.0.3 fail at install script

### ISSUE THREAD

**Issue by paulnunz** [kelektiv/node.bcrypt.js#582]
I am unable to install locally bcrypt using npm for my node project. See error listing below:

npm = 5.6.0
os = macos 10.13.3
Xcode 9.2
Build version 9C40b

xxx:xxx:~/_project name_ $sudo npm install bcrypt --save

> fsevents@1.1.3 install /Users/xxx/_project name_/node_modules/fsevents
> node install

sh: node: command not found

> bcrypt@1.0.3 install /Users/xxx/xxx/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

env: node: No such file or directory
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: spawn ENOENT

npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! bcrypt@1.0.3 install: `node-pre-gyp install --fallback-to-build`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the bcrypt@1.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxx/.npm/_logs/2018-03-05T20_06_21_615Z-debug.log

2774 verbose npm  v5.6.0
2775 error file sh
2776 error code ELIFECYCLE
2777 error errno ENOENT
2778 error syscall spawn
2779 error bcrypt@1.0.3 install: `node-pre-gyp install --fallback-to-build`
2779 error spawn ENOENT
2780 error Failed at the bcrypt@1.0.3 install script.
2780 error This is probably not a problem with npm. There is likely additional logging output above.
2781 verbose exit [ 1, true ]

**Comment by devnieL** [comment]
Hello,  I'm having the same problem. 😕Did you solve it ?

**Comment by paulnunz** [comment]
No. I have all the required dependencies on my machine. I am stuck.

**Comment by agathver** [comment]
Please do not use `sudo` for a local install of bcrypt.

Please add your debug.log, without it it's impossible to know what went wrong.

**Comment by paulnunz** [comment]
[2018-03-05T20_21_25_106Z-debug.log.zip](https://github.com/kelektiv/node.bcrypt.js/files/1785171/2018-03-05T20_21_25_106Z-debug.log.zip)

**Comment by agathver** [comment]
@paulnunz
Its a permission issue.
```
2758 verbose lifecycle bcrypt@1.0.3~install: unsafe-perm in lifecycle false

```

Please do not use sudo for installing bcrypt. NodeJS prevents installing native modules while running as root.
https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by paulnunz** [comment]
That fixed it! Thank you.

**Comment by devnieL** [comment]
In my case the problem was that I was uploading the node_modules to my server. I added it to my .cfignore and it got solved.
Thanks!
