### ISSUE TITLE
Publish a new version for Node 10

### ISSUE THREAD

**Issue by targos** [kelektiv/node.bcrypt.js#588]
[NAN 2.8.0](https://github.com/nodejs/nan/blob/77d0046d4a8378a0cd31d8110130471b44c99d8d/CHANGELOG.md#280-nov-15-2017) made a fix to stop using V8's `ForceSet` API which has been removed.
The master branch here is already at NAN 2.9.2. Is it possible to publish a new version? This should fix the package and its dependents for Node 10.

**Comment by agathver** [comment]
So node 10 has been released? I have been living under a rock it seems...

If it's just a version bump then it should be quick to do that.

**Comment by targos** [comment]
> So node 10 has been released?

Not yet. It will be released later this month.

**Comment by agathver** [comment]
Just published a v2.0.0. That should cover it.

**Comment by targos** [comment]
Thanks! I confirm it works with Node master.
