### ISSUE TITLE
Can't install bcrypt

### ISSUE THREAD

**Issue by makarychev13** [kelektiv/node.bcrypt.js#591]
Hello. I am trying to install bcrypt this:
`npm i bcrypt --save`
`sudo npm i bcrypt --save`
`sudo npm i bcrypt --unsafe-perm=true --allow-root --save`

Catching this error: https://pastebin.com/5HfmfrnH
How to resolve this problem?

P.S. 
Ubuntu 17.10
node 8.11.1
npm 5.8.0

**Comment by agathver** [comment]
Can you send the full log file? Pre-build binaries are broken ATM.

**Comment by makarychev13** [comment]
Console output: https://pastebin.com/6hdWfxtF
Log: https://pastebin.com/mpZAzTWq

**Comment by agathver** [comment]
Version v2.0.1 was published. Could you check if it fixes your issues?

**Comment by agathver** [comment]
@juicycool92 You are running `npm install` as root. It will fail unless you set `unsafe-perm` to true (not recommended) https://docs.npmjs.com/misc/config#unsafe-perm

**Comment by juicycool92** [comment]
@agathver 
Thanks for information,
after i remove all dir and install again, its works nicely on bycrypt 2.0.1

**Comment by agathver** [comment]
@makarychev13 
You did not have the required dependencies (python2, make, g++) for a source install (see wiki). However, good news, we have prebuilt binaries working again since v2.0.1
