### ISSUE TITLE
window 10 i can't install   :-(

### ISSUE THREAD

**Issue by jaman99** [kelektiv/node.bcrypt.js#592]
C:\Users\MD Jaman\Desktop\mywebpro>npm install bcrypt --save

> bcrypt@2.0.0 install C:\Users\MD Jaman\Desktop\mywebpro\node_modules\bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(302): https://github.com/kelektiv/node.bcrypt.js/releases/download/v2.0.0/bcrypt_lib-v2.0.0-node-v57-win32-x64-unknown.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@2.0.0 and node@8.9.0 (node-v57 ABI, unknown) (falling back to source compile with node-gyp)

C:\Users\MD Jaman\Desktop\mywebpro\node_modules\bcrypt>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean )

C:\Users\MD Jaman\Desktop\mywebpro\node_modules\bcrypt>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build "--module=C:\Users\MD Jaman\Desktop\mywebpro\node_modules\bcrypt\lib\binding\bcrypt_lib.node" --module_name=bcrypt_lib "--module_path=C:\Users\MD Jaman\Desktop\mywebpro\node_modules\bcrypt\lib\binding" --napi_version=1 --node_abi_napi=napi )  else (node "" configure --fallback-to-build "--module=C:\Users\MD Jaman\Desktop\mywebpro\node_modules\bcrypt\lib\binding\bcrypt_lib.node" --module_name=bcrypt_lib "--module_path=C:\Users\MD Jaman\Desktop\mywebpro\node_modules\bcrypt\lib\binding" --napi_version=1 --node_abi_napi=napi )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\MD Jaman\\Desktop\\mywebpro\\node_modules\\bcrypt\\lib\\binding\\bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=C:\\Users\\MD Jaman\\Desktop\\mywebpro\\node_modules\\bcrypt\\lib\\binding" "--napi_version=1" "--node_abi_napi=napi"
gyp ERR! cwd C:\Users\MD Jaman\Desktop\mywebpro\node_modules\bcrypt
gyp ERR! node -v v8.9.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\MD Jaman\Desktop\mywebpro\node_modules\bcrypt\lib\binding\bcrypt_lib.node --module_name=bcrypt_lib --module_path=C:\Users\MD Jaman\Desktop\mywebpro\node_modules\bcrypt\lib\binding --napi_version=1 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\MD Jaman\Desktop\mywebpro\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Windows_NT 10.0.10240
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\MD Jaman\\Desktop\\mywebpro\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\MD Jaman\Desktop\mywebpro\node_modules\bcrypt
node-pre-gyp ERR! node -v v8.9.0
node-pre-gyp ERR! node-pre-gyp -v v0.9.0
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\MD Jaman\Desktop\mywebpro\node_modules\bcrypt\lib\binding\bcrypt_lib.node --module_name=bcrypt_lib --module_path=C:\Users\MD Jaman\Desktop\mywebpro\node_modules\bcrypt\lib\binding --napi_version=1 --node_abi_napi=napi' (1)
npm WARN jaman@1.0.0 No description
npm WARN jaman@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@2.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@2.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MD Jaman\AppData\Roaming\npm-cache\_logs\2018-04-15T23_48_53_805Z-debug.log

**Comment by agathver** [comment]
Pre built binaries are broken ATM. You should install a compiler as mentioned in install instructions.

**Comment by agathver** [comment]
With 2.0.1, you should no longer see this issue

**Comment by jaman99** [comment]
Its work Its work  ha ha ha thanks so much bro   i feel so so happy  😄 😄 😄 😄 😄 😄 😄 😄 😄 😄 😄 😄 😄 😄 😄
