### ISSUE TITLE
Question about v2 changes

### ISSUE THREAD

**Issue by paglias** [kelektiv/node.bcrypt.js#593]
Hi,

In the Changelog I found that 

> Make 2b the default bcrypt version

while all the passwords we're storing are using the 2a algorithm ($2a$ prefix.

In the readme it's stated that 

> This library supports $2a$ and $2b$ prefix bcrypt hashes. $2x$ and $2y$ hashes are specific to bcrypt implementation developed for Jon the Ripper. *In theory, they should be compatible with $2b$ prefix.*

Does this mean that I can safely upgrade to v2 without worrying about compatibility issues?

Thanks,
Matteo

**Comment by paglias** [comment]
I've tried decrypting a password prefixed with $2a$ with v2 of bcrypt and it worked, so I guess I'm okay?

**Comment by agathver** [comment]
We don't break existing passwords, we just added another hash scheme. Existing hashes will continue to work. 

For some reason if you want the old hashes, you can specify that as the parameter of `genSalt`
