### ISSUE TITLE
Warning for dependency node-pre-gyp

### ISSUE THREAD

**Issue by FunnyB0y** [kelektiv/node.bcrypt.js#594]
I'm getting the following warning for one of the dependencies

`npm in ./node_modules/node-pre-gyp/lib/util/compile.js`

What could be causing this issue? I don't use this package myself, only as a dependency of bcrypt.

**Comment by agathver** [comment]
node-pre-gyp v9.0 (what we use) was broken. A new patch release with fixed node-pre-gyp is in works.

**Comment by FunnyB0y** [comment]
@agathver Awesome, thanks. Looking forward to it.
