### ISSUE TITLE
Version 2.0.0 hashed passwords not compatible with version 1.0.3

### ISSUE THREAD

**Issue by hfsd** [kelektiv/node.bcrypt.js#596]
Passwords hashed with version 2.0.0 of the module are not compatible with version 1.0.3. 

This means essentially that: if one application generates a hash with version 2.0.0 and another one compares the hash with version 1.0.3, the comparison will return false for the correct string.

Why is this behavior and why is it not documented?

**Comment by agathver** [comment]
> This means essentially that: if one application generates a hash with version 2.0.0 and another one compares the hash with version 1.0.3, the comparison will return false for the correct string.

This is true. However, there is backward compatibility between the hashes. Hashes generated in v1.0.2 will continue to work in v2.0.0. 

_However, you may, for 99.99% of cases, get v2 hashes running in v1.0.3 by replacing `2b` with `2a`._

**Comment by hfsd** [comment]
You mean 1.0.3? How about then patching version 1.0.3 to throw an error that an unsupported bcrypt hash is being used; or ammend it so that it will pretend that 2b == 2a, and throw if it really is not?

**Comment by agathver** [comment]
@hfsd, Throwing an error means a breaking change, we have strong semver guarantees, it will not be possible to introduce them, unfortunately.
