### ISSUE TITLE
update node-pre-gyp after vulnerability is fixed

### ISSUE THREAD

**Issue by filipesantoss** [kelektiv/node.bcrypt.js#604]
`node-pre-gyp@0.9.1` is vulnerable to prototype pollution. This can be fixed by updating its dependencies. 
https://github.com/mapbox/node-pre-gyp/issues/378

Please update as soon as `node-pre-gyp` is updated.

**Comment by crutchcorn** [comment]
`node-pre-gyp` has been fixed, however it was in a major version fix:
https://github.com/mapbox/node-pre-gyp/blob/master/CHANGELOG.md#0100

Please update to v0.10 in order to fix this
