### ISSUE TITLE
Excessive memory usage for 2.x.x

### ISSUE THREAD

**Issue by adamreisnz** [kelektiv/node.bcrypt.js#609]
Hi there, we've upgraded Bcrypt to 2.x.x and it crashed our Heroku app due to excessive memory usage (> 1GB). Downgrading to 1.0.3 resolved the issue again. Tried again later, but same result.

Any thoughts on what could be happening?

We use bcrypt in a very basic manner:

```
    const salt = await bcrypt.genSalt(rounds);
    const hash = await bcrypt.hash(superPassword, salt);
```

**Comment by agathver** [comment]
This is strange. I run a Heroku demo and it runs fine.

It's ultra barebones though: https://github.com/agathver/bcrypt-demo

bcrypt-demo.herokuapp.com

**Comment by adamreisnz** [comment]
Yeah, initially it ran fine for the first 3 hours or so, but then the problems started and persisted even after a dyno restart. What's the load like on your demo server? We get about 3-5 requests per second later in the evening, which may have triggered it under the increased load.

When I downgraded the problems went away, and when we tried again later, it started pretty much right away, as the server was still under similar load.

**Comment by agathver** [comment]
>What Node version do you run the demo under?
Node 8

I tried to replicate your setup on my local. I was repeatedly hashing and comparing strings for a few hours and found no visible signs of a leak. RSS pegged at ~35mb for most of the time.

I'll run it a bit longer and come with some graphs.

**Comment by adamreisnz** [comment]
Same version here. How many rounds were you using in your setup?
We are using 15 here. Perhaps that's too many?

**Comment by adamreisnz** [comment]
Ironically, I spent this morning investigating another memory issue for a package I help maintain (https://github.com/sendgrid/sendgrid-nodejs), where a user experienced memory problems after upgrading to the newest version.

The problem there was narrowed down to a logger which was logging the response success object after the mail was sent. This contained circular data which the logger could not process properly. 

It appeared the cause was the sendgrid library, but in reality it was because the return value changed which was then being logged, which was the actual problem.

So with that in mind, has anything else in the API of bcrypt changed in 2.0.0 by any chance that might indirectly affect other parts of the app?

**Comment by agathver** [comment]
The number of rounds depend on how fast your systems are and how valuable are your user's passwords. 

The library's default is 10, but 13 is also starting to become the common practice.

**Comment by agathver** [comment]
Between 1x and 2x, nothing changed dramatically, except the fact that we default to 2b now. That's a couple of if-else here and there.

**Comment by adamreisnz** [comment]
Ok thanks. I'm experimenting with it again on our staging environment but so far nothing happening. Will try to reduce the rounds to 10.

**Comment by adamreisnz** [comment]
@agathver have you found the cause of this? We still haven't upgraded back to 2.x due to this issue.

**Comment by adamreisnz** [comment]
We have skipped 2.x and now upgraded to 3.x under heroku-18 running Node 10.15, and so far (fingers crossed) no issues.
