### ISSUE TITLE
Azure Web App failing when requiring bcrypt

### ISSUE THREAD

**Issue by johnmeister** [kelektiv/node.bcrypt.js#610]
Here is most of  my package.json
{    "@sendgrid/mail": "^6.2.1",
    "bcrypt": "^2.0.1",
    "express": "~4.15.5",
    "express-session": "^1.15.6",
    "passport": "^0.4.0",
    "passport-local": "^1.0.0",
    removed other for TL;DR
}
I can install bcrypt and the app will run in azure however when I require the package into the app my azure app crashes with a HTTP ERROR 500
example:
--App works--
//const bcrypt = require('bcrypt');
const ... = require('...');
const saltRounds = 10;
--App stops working--
const bcrypt = require('bcrypt');
const ... = require('...');
const saltRounds = 10;

--Edit--
The app runs fine locally
node version 8.11.1

**Comment by agathver** [comment]
Need more logs

**Comment by johnmeister** [comment]
Only log I get at that iisnode can't find a (literally a) path. From azure.

**Comment by agathver** [comment]
This is nothing at all. It's hard to debug such an error.

Can you somehow return the stack trace of any exception that is generated?

**Comment by agathver** [comment]
@johnmeister You can mail me that. I'll have a look.

I do not have any experience of Azure websites so a few questions first - but does it support native modules? It should either allow outbound connections during building your app or include a C++ compiler in the container image (or whatever they use).

If you package and deploy everything (as in AWS lambda) make sure that the OS and node versions in Azure and your dev environment is same.

**Comment by johnmeister** [comment]
Nevermind, i'll just use something else. Thanks for your time.

**Comment by DaneSlattery** [comment]
Also having this issue, the following from my server logs: 

Thu May 17 2018 19:56:20 GMT+0000 (Coordinated Universal Time): Application has thrown an uncaught exception and is terminated:
Error: The module '\\?\D:\home\site\wwwroot\node_modules\bcrypt\lib\binding\bcrypt_lib.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

I am using Azure, with NodeJS 8.11.1

**Comment by johnmeister** [comment]
@DaneSlattery 
The version of node you used when you first installed bcrypt is different than the version Azure is using Maybe that's what was also going on with mine. I had this issue when I updated my node version locally and tried to use bcrypt.

**Comment by DaneSlattery** [comment]
The node server says this : D:\home\site\wwwroot>npm i
npm ERR! code ETARGET
npm ERR! notarget No matching version found for bcrpyt@^2.0.1
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'shopping'
npm ERR! notarget 


npm ERR! A complete log of this run can be found in:
npm ERR!     D:\local\AppData\npm-cache\_logs\2018-05-17T20_15_01_013Z-debug.log

**Comment by DaneSlattery** [comment]
@johnmeister , I fixed this by pointing my dependency for the package.json directly to the repository like this

"bcrypt": "https://github.com/kelektiv/node.bcrypt.js/tarball/v2.0.1"

**Comment by agathver** [comment]
@DaneSlattery It is available on NPM. Perhaps, Azure has a different registry that hasn't pulled the changes yet? I'm not very familiar with Azure.

**Comment by rayfoss** [comment]
This problem also manifested it's self in RunKit. Which doesn't have a package.json because it depends on all packages. 

```
var bcrypt = require("bcrypt")

bcrypt.hash('password', 'saltRounds').then(function(hash) {
    console.log(hash)
});
```

![screen shot 2018-05-22 at 5 33 12 pm](https://user-images.githubusercontent.com/876076/40393731-440d6412-5de6-11e8-86ad-0fb46dd3b83c.png)

**Comment by fega** [comment]
maybe this is related: in Windows linux subsystem, when I try to execute the code:

```
[TypeScript] module.js:549
[TypeScript]     throw err;
[TypeScript]     ^
[TypeScript]
[TypeScript] Error: Cannot find module '/mnt/c/Users/Acer/projects/idp/services/node_modules/@zubko/crypt/node_modules/bcrypt/lib/binding/bcrypt_lib.node'
[TypeScript]     at Function.Module._resolveFilename (module.js:547:15)
[TypeScript]     at Function.Module._load (module.js:474:25)
[TypeScript]     at Module.require (module.js:596:17)
[TypeScript]     at require (internal/module.js:11:18)
[TypeScript]     at Object.<anonymous> (/mnt/c/Users/Acer/projects/idp/services/node_modules/@zubko/crypt/node_modules/bcrypt/bcrypt.js:6:16)
[TypeScript]     at Module._compile (module.js:652:30)
[TypeScript]     at Object.Module._extensions..js (module.js:663:10)
[TypeScript]     at Module.load (module.js:565:32)
[TypeScript]     at tryModuleLoad (module.js:505:12)
[TypeScript]     at Function.Module._load (module.js:497:3)
[TypeScript]     at Module.require (module.js:596:17)
[TypeScript]     at require (internal/module.js:11:18)
```

**Comment by rayfoss** [comment]
Happy to report that bcryptjs works like a charm

```
var bcrypt = require("bcryptjs")

bcrypt.hash('password', 10).then(function(hash) {
    console.log(hash)
});
```
![screen shot 2018-06-01 at 11 47 27 am](https://user-images.githubusercontent.com/876076/40852908-b6af6008-6591-11e8-80c3-d339c0c220b3.png)

**Comment by agathver** [comment]
@fega If you are on SFL, make sure you perform `npm install` inside `bash`, else incorrect versions of modules will be installed.

**Comment by agathver** [comment]
@rayfoss, It's probably an issue with RunKit - something we have no control over. Can you report any other native module that works on RunKit? Like the related `argon2`?

**Comment by rayfoss** [comment]
@agathver it uses docker... should run fine. The issue appers to be that this package expects a package.json file to exist... that's can't be the case in runkit which has every package in NPM preinstalled in the docker image.

**Comment by fega** [comment]
@agathver Sure, I use it.

**Comment by agathver** [comment]
@rayfoss , This package only expects to find it's own `package.json` i.e, [this file](https://github.com/kelektiv/node.bcrypt.js/blob/master/package.json).

**Comment by 39otrebla** [comment]
still happening to me on Azure web app (windows), running on node 8.10.0 and npm 5.6.0.

**Comment by sawdit** [comment]
> still happening to me on Azure web app (windows), running on node 8.10.0 and npm 5.6.0.
> 
> **EDIT**: tried `cd node_modules/bcrypt` and `npm install`. Failed with:
> 
> ```
> 'node-pre-gyp' is not recognized as an internal or external command,
> operable program or batch file.
> �[37;40mnpm �[31;40mERR! code ELIFECYCLE
> �[37;40mnpm �[31;40mERR! errno 1
> �[37;40mnpm �[31;40mERR! bcrypt@2.0.1 install: `node-pre-gyp install --fallback-to-build`
> �[37;40mnpm �[31;40mERR! Exit status 1
> �[37;40mnpm �[31;40mERR! 
> �[37;40mnpm �[31;40mERR! Failed at the bcrypt@2.0.1 install script.
> �[37;40mnpm �[31;40mERR! This is probably not a problem with npm. There is likely additional logging output above.
> ```
> 
> And app then crashes as it doesn't find bcrypt.node.
> 
> **EDIT**: solved adding `node-pre-gyp` as project dependency and manually doing `cd node_modules\bcrypt && npm install` as postinstall script (dunno why isn't working out of the box).

I tried this and it didn't work? I get the same error repeated. Are there any other prereqs for node-pre-gyp?

**Comment by agathver** [comment]
@sawdit https://github.com/kelektiv/node.bcrypt.js/wiki/Installation-Instructions
