### ISSUE TITLE
Add 32-bit Linux Support

### ISSUE THREAD

**Issue by Starz0r** [kelektiv/node.bcrypt.js#613]
It seems that I can't use software that depends on this package because it doesn't have 32-bit Linux support. Is it a possibility that we can get releases for this on Linux 32-bit?

Neverthought I'd be asking for this, but I do have an old machine that only supports regular x86 without 64-bit extensions, having this would still allow me to get some use of the machine.

**Comment by agathver** [comment]
> it doesn't have 32-bit Linux support.

32 bit is supported. You need python2.7, make and G++. NPM will automatically build the extension for you.

Pre-built binaries are available on a best-effort basis, if you can provide a working CI setup for 32 bit, we may decide to put them up. However, I don't feel it will be worth the effort. OSs are starting to phase out 32 bit entirely, and the number of 32-bit Linux users are very less. (Windows is different). 

> Neverthought I'd be asking for this, but I do have an old machine that only supports regular x86 without 64-bit extensions, having this would still allow me to get some use of the machine.

Very old indeed.

**Comment by Starz0r** [comment]
Reasonable.
