### ISSUE TITLE
node_modules are published

### ISSUE THREAD

**Issue by caub** [kelektiv/node.bcrypt.js#616]
https://unpkg.com/bcrypt@2.0.1/node_modules/

I don't think that's intentional, is it?

**Comment by caub** [comment]
Yes thanks, moving to bcryptjs is dafer

**Comment by agathver** [comment]
But slower!

You could try one of those isomorphic wrappers, which import `bcrypt/bcryptjs` depending on what is available. Parse server does this too.

**Comment by caub** [comment]
Yes right, a bit [slower](https://repl.it/@caub/bcrypt-perfs)
