### ISSUE TITLE
Bcrypt compare returns false after a certain amount of time 

### ISSUE THREAD

**Issue by ayush1810** [kelektiv/node.bcrypt.js#620]
I am using bcrypt (v2.0.1) in a MERN project (Node v8.10.0) to store user passwords in MongoDB using Mongoose. The hash function: 

```javascript
SellerSchema.pre('save', function (next) {
    var user = this;
    bcrypt.hash(user.password, 10, function (err, hash) {
      if (err) {
        return next(err);
      }
      user.password = hash;
      next();
    });
});
```
The authenticate part: 

```
SellerSchema.statics.authenticate = function (email, password, callback) {
    Seller.findOne({ email: email })
      .exec(function (error, user) {
        if (error) return callback(error);
        else if (!user) {
          var err = new Error('User not found.');
          err.status = 401;
          return callback(err);
        }
        bcrypt.compare(password, user.password).then(function (result){
          if (result == true) {
            return callback(null, user);
          } else {
            return callback();
          }
        });
      });
}; 
```
The login route: 

```
router.post('/login', function(req, res, next) {
    if (req.body.email && req.body.password) {  
    Seller.authenticate(req.body.email, req.body.password,function (error, user) {
        if (error || !user) {
            console.log("this "+error);
        var err = new Error('Wrong email or password.');  // logged everytime the compare result was false 
        err.status = 401;
        return next(err);
        }  else {
        res.json(user);
        }
    });
    } else {
    var err = new Error('Email and password are required.');
    err.status = 401;
    return next(err);
    }
});
```

When signing up new users, the hash is stored fine ("$2b$10$oh4Kjby9YiLdjWmpMqsGSOFxtYEp.318OczgXirqyR9CvbX8xzKg6" for "ayush") and logging in using the plain-text *does* passes the compare() for few times, but returns false after that. 
If I signup a new user and login, it works again for sometime and then starts returning false. 

* What went wrong?
`bcrypt.compare()` returns false for all passwords stored in mongoose db after some amount of time.  
* What did you expect to happen?
return `true` when passwords match
* Which version of nodejs and OS?
Node : 8.10.0 , OS: Ubuntu 18.04 

Thanks!

**Comment by agathver** [comment]
What is "the certain" amount of time? Does it depend on the number of compares?

**Comment by ayush1810** [comment]
I'm not sure but yeah, it might be going wrong after some 10-15 logins/compares.

**Comment by ayush1810** [comment]
Hi @agathver , Sorry for the trouble.
The issue was with the `pre`  hook, I missed a modified check before hashing. 
Adding a `if (user.isModified('password'))` solved it obviously. 
You can close/delete this issue.
