### ISSUE TITLE
Potential "Constant Time" inconsistency with bcrypt.compare

### ISSUE THREAD

**Issue by rtablada** [kelektiv/node.bcrypt.js#630]
## What Went Wrong

Calling `compare` with an invalid hash value exits early.

## What did you expect to happen?

In the documentation it specifically says:

> The "compare" function counters timing attacks (using a so-called 'constant-time' algorithm)

Based on this I would expect the `compare` function to be `constant-time` no matter the input arguments

## Which version of nodejs and OS?

Node v10.5.0
Mac OSX 10.12.6

## Why This is Important

Reading the docs and bringing over best practices around password checking it is best practice to do a "dummy check" of a password to maintain constant timing on things like login routes.

For instance if logging in with username and password if the user with the given username does not exist a call to a constant time function is usually used to balance out the time between checking passwords and not (to avoid leaking information of what usernames exist/don't based on response times).

Based on the documentation, the `compare` function would seem to be the `constant-time` function to be called and one would expect this to have similar execution time to a real hash check.

Example Code:

```js
if (!user) {
  await bcrypt.compare(password, ''); // Attempt dummy bcrypt check
 
  throw new UnauthorizedError();
} 

if (!await bcrypt.compare(password, user.hash)) {
  throw new UnauthorizedError();
}

// Do what you want with the authorized user.
```

But the above code gives inconsistent results since `bcrypt.compare` exits early when the hash is not a valid hash.

## Recommendation

I think there's three possible solutions to this problem.

1. Document the inconsistency and explicitly note that `compare` is only `constant-time` with valid hash and recommend using `bcrypt.hash(someValue)` instead
2. Create a `bcrypt.dummyCompare` similar to the `dummy_checkpw` function provided by [comeonin](https://github.com/riverrun/comeonin) - This would still need update documentation noting that `compare` is only `constant-time` for valid hashes
3. Make `compare` constant time regardless of hash value validity

**Comment by rtablada** [comment]
Example Timer to show inconsistency:

```js
const bcrypt = require('bcrypt');

async function main () {
  const hash = await bcrypt.hash('HELLO WORLD', 10);

  for (let i = 0; i < 20; i++) {
    console.time('compareHash');
    await bcrypt.compare('HELLO WORLD', hash);
    console.timeEnd('compareHash');
  }

  for (let i = 0; i < 20; i++) {
    console.time('compareNotHash');
    await bcrypt.compare('HELLO WORLD', '');
    console.timeEnd('compareNotHash');
  }
}

main();
```


Output

```js
compareHash: 73.189ms
compareHash: 68.553ms
compareHash: 71.108ms
compareHash: 70.089ms
compareHash: 72.180ms
compareHash: 70.864ms
compareHash: 70.431ms
compareHash: 69.053ms
compareHash: 66.719ms
compareHash: 66.866ms
compareHash: 67.552ms
compareHash: 69.358ms
compareHash: 67.532ms
compareHash: 69.094ms
compareHash: 66.438ms
compareHash: 69.639ms
compareHash: 70.990ms
compareHash: 69.772ms
compareHash: 67.925ms
compareHash: 68.812ms
compareNotHash: 0.079ms
compareNotHash: 0.026ms
compareNotHash: 0.068ms
compareNotHash: 0.075ms
compareNotHash: 0.073ms
compareNotHash: 0.033ms
compareNotHash: 0.043ms
compareNotHash: 0.023ms
compareNotHash: 0.041ms
compareNotHash: 0.068ms
compareNotHash: 0.044ms
compareNotHash: 0.073ms
compareNotHash: 0.033ms
compareNotHash: 0.023ms
compareNotHash: 0.022ms
compareNotHash: 0.021ms
compareNotHash: 0.029ms
compareNotHash: 0.025ms
compareNotHash: 0.024ms
compareNotHash: 0.022ms
```

**Comment by agathver** [comment]
We could document this. We perform an early exit on an invalid hash value as the underlying C++ engine performs some initialization from the hash value and handling errors from the C++ environment is tricky. 

My rationale for such approach is timing attacks is worthless if the hash value itself is invalid.

The hash value is supposed to be fetched from a database which should be well-formed. If the hash value is invalid, it should be reported as a server side error to the user.
