### ISSUE TITLE
process.dlopen(module, path.toNamespacedPath(filename))

### ISSUE THREAD

**Issue by webPpei** [kelektiv/node.bcrypt.js#635]
hi,
version: os->10.13.3  node->v8.4.0 vscode->1.25.1;"bcrypt": "^3.0.0".
if i debug in vscode:
![image](https://user-images.githubusercontent.com/25998977/42858103-803380be-8a7f-11e8-866a-5b55aa85718d.png);
if I start the service with node, it works fine.
I tried to change the node version and the bcrypt version，it no works.

**Comment by agathver** [comment]
Recompile node module with npm rebuild bcrypt.

Also make sure vscode uses the same node as your CLI. Sometimes node
version managers or old vscode config makes this version mismatch.

**Comment by webPpei** [comment]
thanks,I tried it but it didn't work out.

**Comment by webPpei** [comment]
thanks,I tried it but it didn't work out.

**Comment by nkanand4** [comment]
@webPpei I ran into the same issue. Rebuild didn't help. I removed the bcrypt from node_modules and ran the npm install again. Also, do make sure your nodejs runtime version is same as the compiling version.

**Comment by vaaski** [comment]
i had to pass the rebuild flag, otherwise it would use the already installed version.

my issue was solved by doing
### `npm rebuild bcrypt --build-from-source`

**Comment by rohitgaidhane** [comment]
> i had to pass the rebuild flag, otherwise it would use the already installed version.
> 
> my issue was solved by doing
> 
> ### `npm rebuild bcrypt --build-from-source`

this works for me!!!

**Comment by Kade-95** [comment]
> @webPpei I ran into the same issue. Rebuild didn't help. Do make sure your nodejs runtime version in vscode is same as the compiling version.

How

**Comment by madhukarreddyganga** [comment]
I have the same issue I cannot resolve please give me some ideas

**Comment by uurtech** [comment]
same here. suggestions did not work for me either

**Comment by jmassery** [comment]
For me, I just ran **npm install bcrypt** again and it worked. I tried the rebuild command and got nowhere.

**Comment by bamne123** [comment]
Any resolutions for this issue?

**Comment by bamne123** [comment]
Got it working after spending hours.
1. Stop the images by `docker-compose down` 
2. Build the images by `docker-compose build`
3. Start the images by `docker-compose up`

For reference my dockerfile is as follows,
```
FROM node:10.16.0
RUN npm install -g --unsafe-perm prisma2@2.0.0-preview-12

RUN mkdir /app
WORKDIR /app

COPY package*.json /app
COPY prisma /app/prisma/
COPY src /app/src

ARG MYSQL_URL
ENV MYSQL_URL "$MYSQL_URL"

RUN npm install
RUN npm audit fix --force

RUN prisma2 generate

CMD ["npm", "start" ]
```

**Comment by irsol** [comment]
> Got it working after spending hours.
> 
> 1. Stop the images by `docker-compose down`
> 2. Build the images by `docker-compose build`
> 3. Start the images by `docker-compose up`
> 
> For reference my dockerfile is as follows,
> 
> ```
> FROM node:10.16.0
> RUN npm install -g --unsafe-perm prisma2@2.0.0-preview-12
> 
> RUN mkdir /app
> WORKDIR /app
> 
> COPY package*.json /app
> COPY prisma /app/prisma/
> COPY src /app/src
> 
> ARG MYSQL_URL
> ENV MYSQL_URL "$MYSQL_URL"
> 
> RUN npm install
> RUN npm audit fix --force
> 
> RUN prisma2 generate
> 
> CMD ["npm", "start" ]
> ```

@bamne123 try to add `node_modules` to your `.gitignore` file

**Comment by luvy1428** [comment]
I just ran the below command and then tried to install and it worked:
npm install node-pre-gyp -g

**Comment by soymikey** [comment]
I have same problem. but I have found the problem is that I have binded the node_modules folder from local machine to container‘s. Bc my local machine is based on Windows, and all files in node_modules folder are compiled by Windows which caused problem to run on container. The solutions is when you creating image install all dependencies to image. Hope this going to help you out.

**Comment by JNaeemGitonga** [comment]
seeing inside of docker container using docker-compose...blew away `node_modules` and ran `docker-compose up --build`...problem no more...

**Comment by Mafia-boss-lvl-420** [comment]
for me, it was working fine but only did this when I tried to put it on Heroku(a hosting website) to fix it I just delete node_modules this will only work if what you host with will auto download your modules

**Comment by Vancey567** [comment]
> > i had to pass the rebuild flag, otherwise it would use the already installed version.
> > my issue was solved by doing
> > ### `npm rebuild bcrypt --build-from-source`
> 
> this works for me!!!

I am using yarn. And it says rebuild not found what to do??

**Comment by kottu-fullstack** [comment]
> > Got it working after spending hours.
> > 
> > 1. Stop the images by `docker-compose down`
> > 2. Build the images by `docker-compose build`
> > 3. Start the images by `docker-compose up`
> > 
> > For reference my dockerfile is as follows,
> > ```
> > FROM node:10.16.0
> > RUN npm install -g --unsafe-perm prisma2@2.0.0-preview-12
> > 
> > RUN mkdir /app
> > WORKDIR /app
> > 
> > COPY package*.json /app
> > COPY prisma /app/prisma/
> > COPY src /app/src
> > 
> > ARG MYSQL_URL
> > ENV MYSQL_URL "$MYSQL_URL"
> > 
> > RUN npm install
> > RUN npm audit fix --force
> > 
> > RUN prisma2 generate
> > 
> > CMD ["npm", "start" ]
> > ```
> 
> @bamne123 try to add `node_modules` to your `.gitignore` file

adding node_modules to docker.ignore solved the issue

**Comment by Njuguna-JohnBrian** [comment]
For me I just reinstalled bcrypt `npm i bcrypt`  and all was good.

**Comment by davidhasek1** [comment]
I found a solution. Instead of installing `bcrypt`, install `bcryptjs`. After that everything works as expexted.

**Comment by EHsieh0212** [comment]
From a ubuntu env, you can try these commands:

```
rm -rf node_modules/
npm update
```
The commands will remove current node_modules including the error showing bycrypt package, and then install new one with updated newest version. It works for me on ubuntu env.

**Comment by saminwankwo** [comment]
Had this problem, this morning. uninstalling the package and reinstalling it, fixed the error for me

**Comment by joss12** [comment]
In my case i just deleted the node_module folder and run: npm install and my project works well

**Comment by felixdomingos1** [comment]
> i had to pass the rebuild flag, otherwise it would use the already installed version.
> 
> my issue was solved by doing
> 
> ### `npm rebuild bcrypt --build-from-source`

it is not working on my code

**Comment by joss12** [comment]
Try to delete the node_module and run nom install

**Comment by felixdomingos1** [comment]
I did, and A fixed it using another form, but thanks!
*Are y*ou working now as a Dev?

joss12 ***@***.***> escreveu no dia terça, 1/08/2023 à(s)
23:55:

**Comment by joss12** [comment]
Yes sir. I do work as free lancer backend dev

**Comment by felixdomingos1** [comment]
Glad to hear it! me too, So can we change a contact
where are you from?

joss12 ***@***.***> escreveu no dia quarta, 2/08/2023 à(s)
02:15:

**Comment by felixdomingos1** [comment]
this is my whatsApp +244 954 208 455

Félix S. Domingos ***@***.***> escreveu no dia quarta,
2/08/2023 à(s) 17:17:

**Comment by felixdomingos1** [comment]
https://prod.liveshare.vsengsaas.visualstudio.com/join?DB41AD9BE7B3B5AF35366B6ABE3E5B2466FF


Félix S. Domingos ***@***.***> escreveu no dia quarta,
2/08/2023 à(s) 17:20:

**Comment by felixdomingos1** [comment]
https://prod.liveshare.vsengsaas.visualstudio.com/join?A401AFF76868B090B4A8723FE7E653C1F4C5


Félix S. Domingos ***@***.***> escreveu no dia quinta,
3/08/2023 à(s) 15:31:

**Comment by vaaski** [comment]
@felixdomingos1 fyi you're sharing this publicly right now

**Comment by felixdomingos1** [comment]
https://meet.google.com/jpw-ygtj-qfs

vaaski ***@***.***> escreveu no dia quinta, 3/08/2023 à(s)
15:41:

**Comment by REACT-DEVELOPER-IBROKHIM** [comment]
`npm i bcrypt` worked for me. It is absolutely from bcrypt. So maybe upgrade or downgrade bcrypt version or reinstalling it can solve your problem.

**Comment by rohanbadgujar20011** [comment]
make sure you download bcryptjs not bcrypt in your project

**Comment by miguel-pv-biglo** [comment]
i uninstalled bcrypt ( `npm uninstall bcrypt` ) and changed it for bcryptjs (you have to install it first, of course `npm install bcrypt` ). That solved it for me. Hope it helps someone :)

**Comment by aldo235** [comment]
i try to stick using bcrypt rather than using "bcryptjs" because after i test "bcryptjs" with k6 my api avg time increast from 1sec to 2sec, 
<img width="735" alt="Screenshot 2024-10-09 at 11 19 12" src="https://github.com/user-attachments/assets/da65810c-63b3-45ed-9540-3c0919148259">
 the second one using "bcryptjs", so i found the other solution by adding dockerignore
 ```bash
    docker build -t boilerplate:latest . 
  ```
and also change my Dockerfile 
 ```bash
    FROM node:18

  WORKDIR /usr/src/app
  
  COPY package*.json ./
  
  RUN npm install --build-from-source=bcrypt
  
  COPY . .
  
  EXPOSE 8080
  CMD [ "node", "app.js" ]
  ```
