### ISSUE TITLE
Is it possible to provide an API to get the salt used in a hash?

### ISSUE THREAD

**Issue by MathiasSM** [kelektiv/node.bcrypt.js#637]
* What went wrong? Has no obvious way to get the salt from a hash
* What did you expect to happen? For it to provide an API for that
* Which version of nodejs and OS? Any
* If you find a bug, please write a failing test. Not a bug. Feature request.

If I understand bcrypt correctly, the first 22 characters after the version and number of rounds are the salt. A function much like `getRounds` should work. I have no experience with native modules here, though, and there might be some caveats with that hash information I'm not aware of.

**Comment by agauniyal** [comment]
why would you want it though? :thinking:

**Comment by agathver** [comment]
If you want to generate a salt, use the `genSalt` or `genSaltSync` and strip the version and rounds info (the $2b$10$) part. It returns a salt conforming to the [modular crypt format](https://passlib.readthedocs.io/en/stable/modular_crypt_format.html#overview).
