### ISSUE TITLE
Comparison fails under Ubuntu 16.03 if the hash was generated on a Windows 10 machine

### ISSUE THREAD

**Issue by simon-lorenz** [kelektiv/node.bcrypt.js#639]
I ran into an issue with invalid salt revisions and failed comparisons when I generated hashes on Windows 10 (locally) and compared them under Ubuntu 16.03 (Heroku). Both sides use Node v8.11.3.

`bcrypt.hashSync('hello', 12)` on a windows machine results in something like `$2b$12$kSvPARGDmLE6lC0JKq0cXuRVgkqUljlGvF5IKeavwkwOCh8/JEXDC`.

Against my expectations the following returns false under Ubuntu/Heroku:
`bcrypt.compareSync('hello', '$2b$12$kSvPARGDmLE6lC0JKq0cXuRVgkqUljlGvF5IKeavwkwOCh8/JEXDC') // false`

I checked [https://www.devglan.com/online-tools/bcrypt-hash-generator](url) and it said "Invalid salt revision". If I change the prefix from $2b$ to $2a$ the comparison succeeds. 

This surely is an edge case and I think that normally no one would create and compare hashes on different platforms. Yet I did and this behaviour cost me a few hours. 😃

Maybe the compare functions could throw an error like the above linked generator did? Just getting false didn't make a lot of sense to me, when everything worked correctly on my machine.

**Comment by agathver** [comment]
> I ran into an issue with invalid salt revisions and failed comparisons when I generated hashes on Windows 10 (locally) and compared them under Ubuntu 16.03 (Heroku). Both sides use Node v8.11.3.

Make sure both sides use bcrypt >= v2.0

> Against my expectations the following returns false under Ubuntu/Heroku:
`bcrypt.compareSync('hello', '$2b$12$kSvPARGDmLE6lC0JKq0cXuRVgkqUljlGvF5IKeavwkwOCh8/JEXDC')`

I tested on bcrypt v3, Node 10.7 on Ubuntu 18.04, it worked fine: returns `true`.

> This surely is an edge case and I think that normally no one would create and compare hashes on different platforms. Yet I did and this behaviour cost me a few hours.

It isn't. I can see a lot of valid use cases.

> Maybe the compare functions could throw an error like the above linked generator did? Just getting false didn't make a lot of sense to me, when everything worked correctly on my machine.

It should return something in the `err` callback.

**Comment by simon-lorenz** [comment]
Thank you for your quick response!

> Make sure both sides use bcrypt >= v2.0

That's it. I specified `^1.0.3` according to the version compatibility table in README.md.
Now everything works as expected. Thanks again!
