### ISSUE TITLE
Bcrypt returning false when comparing the hashedPassword from Database

### ISSUE THREAD

**Issue by abhi914** [kelektiv/node.bcrypt.js#641]
I am trying to compare the typed password, with the hashedPassword, but bcrypt shows false, even the hashed password is correct
Here is the code

```
userSchema.statics.findByCredentials = function(email, password) {
const User = this;

return User.findOne({email}).then((user) => {
    if(!user) {
        return Promise.reject();
    }
    // console.log(user.password);

    return new Promise((resolve, reject) => {
        bcrypt.compare(password, user.password, (err,res) => {
             if(res) {
                 resolve(user);
             }
             else {
                 reject("Problem here");
             }
            console.log(res);

        });            
    });
});
};
```

Promise should be resolved, but its being rejected

Here is the route code of express:

```
app.post('/users/login', (req, res) => {
const body = _.pick(req.body, ['email', 'password']);
// res.send(body);

User.findByCredentials(body.email, body.password)
    .then((user) => {
        res.send(user);
    }).catch((e) => res.send(e));
```

PS: database is fetching the correct value, it has been checked

**Comment by paulogdm** [comment]
Hello, can you post a complete reproducible example (I repo with the minimum stuff)? This is quite odd...

**Comment by sparkletets** [comment]
Same thing happened to me, comparing against a hash in a MySQL table...

Swapped in the [bcryptjs ](https://www.npmjs.com/package/bcryptjs) library instead, works fine now.

This is the bones of my express route:

```
app.post('/login/', (req,res)=>{
    let b = req.body;
    sess = req.session;

    let sql = "SELECT username, password FROM archiver.users WHERE username = '"+b.username+"'"

    connection.query(sql, (error, results, fields) => {

        if(results.length >0){
            let verified = bcrypt.compareSync(b.password, results[0].password);
            
            if(verified){
                sess.user = results[0].username;
                res.json({msg:'success', user: sess.user, sessid: sess.id})
            }else{
                res.json({msg: 'fail'})
            }
        }else{
            res.json({msg: 'fail'})
        }
    })
})
```

**Comment by agathver** [comment]
@abhi94 You are probably comparing a hash generated by a newer bcrypt implementation with a older version of the library.

Please mention the version and an example hash that fails.

**Comment by BHARATHPABBA** [comment]
I am not able to compare when a password contains # in it

**Comment by agathver** [comment]
@BHARATHPABBA The test suite contains passwords that contain #, please check your code for errors. Open a different issue if problem persists.
