### ISSUE TITLE
The non-configurable node-pre-gyp's binary remote_path prevented from using bcrypt 1.0.3 off an enterprise artifactory

### ISSUE THREAD

**Issue by ilatypov** [kelektiv/node.bcrypt.js#646]
* What went wrong?
Attempts to install bcrypt's pre-built binary from a local artifactory failed due to ignoring the subpath /artifactory/node-pre-gyp-binaries.
`npm install bcrypt@"^1.0.3" --bcrypt_lib_binary_host_mirror=https://INTERNAL_HOST/artifactory/node-pre-gyp-binaries`

* What did you expect to happen?
The host mirror variable substitutes both the host name and the beginning of the path.

* Which version of nodejs and OS?
nodejs 8.9.4, Windows 7

**Comment by ilatypov** [comment]
Not starting `"binary": { "remote_path": ... }` with a forward slash works around the url.resolve call made in `node-pre-gyp`,

https://github.com/mapbox/node-pre-gyp/blob/master/lib/util/versioning.js

**Comment by ilatypov** [comment]
This is accidentally worked around for bcrypt releases past 3.0.0.

https://github.com/kelektiv/node.bcrypt.js/commit/18efb66467e020057c2a94b1d4f95ed31f6c1687

**Comment by agathver** [comment]
This is something I never took into consideration
