### ISSUE TITLE
Bcrypt@3.0.0 failed to install on Node 8.11.4

### ISSUE THREAD

**Issue by aks667** [kelektiv/node.bcrypt.js#648]
While trying to install bcrypt on Ubuntu 16, with Node 8.11.4 running, returns following error

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@3.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@3.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Thanks!

**Comment by bh4r4th** [comment]
I'm also getting the same error when I install bcrypt@3.0.0 using
system Darwin 17.7.0
nvm v0.33.6
node v10.9.0
npm v6.2.0

**Comment by agathver** [comment]
Please send the logs.

>

**Comment by MylesBorins** [comment]
Seeing this particular line in the versions that are failing

```
18:36:48 error:                     | sed: can't read ./Release/.deps/Release/obj.target/bcrypt_lib/src/bcrypt_node.o.d.raw: No such file or directory  
```

**Comment by MylesBorins** [comment]
@agathver this was noticed while testing for the v8.12.0 release... apologies for the confusion. The difference appears to be the upgrade from npm v5.6.0 to v6.4.1 (although v6.2.0 appears to exhibit the same behavior).

I believe it is either something in npm or node-gyp that changed... although in our smoke testing bcrypt is the only native module exhibiting this behavior, so there may be something else weird going on.

There be dragons 😄

**Comment by aks667** [comment]
I found a temporary solution to work with this problem.
I got the error when I was running the node on Node v8.11.
In bcrypt docs it is recommended to use Bcrypt v1.0.3 for Node x8.x.x

![npm_bcrypt_version_compatibility](https://user-images.githubusercontent.com/33094835/45072995-fa276b00-b0fa-11e8-9d70-99a558a2b02f.png)

This works for me on AWS. I hope this should help you around.

:)

**Comment by bh4r4th** [comment]
Rolling back node v10.9.0 => v9.11.2
Updating npm v6.2.0 => v6.4.0
bcrypt 3.0.0 worked for me.

**Comment by MylesBorins** [comment]
To be clear, the error is not consistent outside of our CI. I've spun up a bunch of VMs of various operating systems and I only hit this edge case a fraction of the times I go through the motions

**Comment by bh4r4th** [comment]
please update the dependency `nan` to 2.11.0 and give a go. I can see that's the only dependency in the stack is little bit behind and this 2.10.0 is having issues that are resolved in 2.11.0

**Comment by MylesBorins** [comment]
Made a fork and updated the dependency

--> https://github.com/MylesBorins/node.bcrypt.js/tree/update-nan

Running the CITGM against that... if it is green then we have a solution

--> https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/1534/

Will update this comment when I have results

**Comment by iglizar** [comment]
> I found a temporary solution to work with this problem.
> I got the error when I was running the node on Node v8.11.
> In bcrypt docs it is recommended to use Bcrypt v1.0.3 for Node x8.x.x
> 
> ![npm_bcrypt_version_compatibility](https://user-images.githubusercontent.com/33094835/45072995-fa276b00-b0fa-11e8-9d70-99a558a2b02f.png)
> 
> This works for me on AWS. I hope this should help you around.
> 
> :)

Solved by doing this. Thanks so much!
