### ISSUE TITLE
Snyk is flagging a TOCTOU vulnerability on bcrypt 

### ISSUE THREAD

**Issue by azmeer** [kelektiv/node.bcrypt.js#652]
Snyk is currently flagging a TOCTOU vulnerability due to bcrypt's dependency on chownr (bcrypt@3.0.0 › node-pre-gyp@0.10.2 › tar@4.4.6 › chownr@1.1.1) See [the relevant snyk report](https://snyk.io/vuln/npm:chownr:20180731). 

Chownr does not seem to have the issue fully addressed (See: https://github.com/isaacs/chownr/issues/14) so I was wondering if you guys had a plan to address this issue on your end.

Thanks!

**Comment by agathver** [comment]
It's low priority as we do not use node-pre-gyp during runtime. 
It is used during install time with fixed input.
