### ISSUE TITLE
where is salt stored?

### ISSUE THREAD

**Issue by marialovesbeans** [kelektiv/node.bcrypt.js#654]
If i run this package on different machines and at different time, it should give the same salt, right? So the salt must be hardcoded somewhere to so the value is consistent. Where is it stored?

**Comment by piemonkey** [comment]
The generated salt should be different, but the salt used when verifying the password should be the same, otherwise it would never match, I assume that's what you mean?
The salt is stored in the hash that is output, taking the example from [wikipedia](https://en.wikipedia.org/wiki/Bcrypt):
> For example, the shadow password record `$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy` specifies a cost parameter of 10, indicating 2^10 key expansion rounds. The salt is `N9qo8uLOickgx2ZMRZoMye` and the resulting hash is `IjZAgcfl7p92ldGxad68LJZdL17lhWy`.

**Comment by agathver** [comment]
`bcrypt` uses the modular crypt format, as @piemonkey explained, the salt is stored as the part of the generated hash itself.

**Comment by marialovesbeans** [comment]
If salt is revealed in the hashed form of password, isn't that insecure? Aka, in a normal hashing algorithm, the attacker would have to guess the salt, right?

**Comment by piemonkey** [comment]
Salting isn't done for that purpose. You need to know the salt to check the password, so even if it was stored separately the code to verify the password would need to have both the hash and the salt and an attacker could almost certainly get the salt if they can get the hash. Most password hashing algorithms either produce a modular format or expect the random salt to be stored alongside each hash e.g. in another field in the same DB table.

Salting is done to prevent attacks such as the use of rainbow tables. If the salt wasn't included, any 2 users with the same password would have the same hash and an attacker could hash a list of common passwords and discover what passwords people have used. When salting is used you'd need to generate one of these 'rainbow tables' of common password hashes for each salt, which would be slower than just using brute-force to try all of the common passwords.

To be secure the salt needs to be random and long, but doesn't need to be any more secret than the hash of the password.

**Comment by vancouverwill** [comment]
good question, I was under the impression that the salt would be stored alongside the hash of the password too but this solution is very elegant and avoids mis-implementation 👍

**Comment by ManBearPigg** [comment]
I was going to ask, how does your bcrypt.compare know the correct number of hashing iterations to perform? I know that the salt is stored in the produced hash, so I figured the number of iterations probably is too.

In your example above, if I remove the hash and the salt from the shadow password, I'm left with 
`$2a$10$`

Presumably the '$' are delimiters so you can parse out the numbers, the '10' means 10 salt rounds, and I imagine the 2a has to mean that we are doing 2^[salt rounds] hashing iterations. 

Is that right?

**Comment by piemonkey** [comment]
There are more details on the format on Wikipedia, either on [the page I linked](https://en.wikipedia.org/wiki/Bcrypt#Versioning_history) or for the origin of the format in the [C standard library](https://en.wikipedia.org/wiki/Crypt_(C)#Key_derivation_functions_supported_by_crypt).

In short, `2a` is the algorithm used.

**Comment by sugat009** [comment]
To add on to the original question, we need to know both the salt and password to authenticate the user. Where does this package store the salt? And by store I don't mean the salt prepended in the password.
Because if salt is not stored anywhere then, how does it work?

**Comment by piemonkey** [comment]
@sugat009 Does your edit mean that you've figured out the answer to your question?

**Comment by sugat009** [comment]
@piemonkey sorry, for the late reply and yes, I've figured it out. :D

**Comment by rtvkiz** [comment]
@piemonkey If the final output has a salt appended to the hash, and we know that the version, rounds and salt are limited to certain characters, and at last we have the password salt, so can an attacker just retrieve the last part, the one of the hashed password, and then perform rainbow table attack on it?

**Comment by piemonkey** [comment]
It's funny how this issue keeps getting resurfaced.

@rtvkiz You could indeed perform a rainbow table attack on just the hashed password, but you'd need a different rainbow table for each password salt. Since the salt is different for each, you'd need one rainbow table per hash. The work of generating the rainbow table is wasted, so you're better off doing a brute-force attack. I'd suggest reading [the wikipedia page on rainbow tables](https://en.wikipedia.org/wiki/Rainbow_table#Defense_against_rainbow_tables) for more info.
