### ISSUE TITLE
Node-gyp 

### ISSUE THREAD

**Issue by KarimMohamed2005** [kelektiv/node.bcrypt.js#659]
Anyone can solve this ?

> bcrypt@3.0.1 install /home/karim/node/jwt_db/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 

/home/karim/node/jwt_db/node_modules/bcrypt/node_modules/tar/lib/create.js:4
const hlo = require('./high-level-opt.js')
^^^^^
node-pre-gyp ERR! UNCAUGHT EXCEPTION 
node-pre-gyp ERR! stack SyntaxError: Use of const in strict mode.
node-pre-gyp ERR! stack     at Module._compile (module.js:439:25)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:474:10)
node-pre-gyp ERR! stack     at Module.load (module.js:356:32)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:312:12)
node-pre-gyp ERR! stack     at Module.require (module.js:364:17)
node-pre-gyp ERR! stack     at require (module.js:380:17)
node-pre-gyp ERR! stack     at Object.<anonymous> (/home/karim/node/jwt_db/node_modules/bcrypt/node_modules/tar/index.js:4:30)
node-pre-gyp ERR! stack     at Module._compile (module.js:456:26)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:474:10)
node-pre-gyp ERR! stack     at Module.load (module.js:356:32)
node-pre-gyp ERR! System Linux 4.15.0-34-generic
node-pre-gyp ERR! command "node" "/home/karim/node/jwt_db/node_modules/bcrypt/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/karim/node/jwt_db/node_modules/bcrypt
node-pre-gyp ERR! node -v v0.11.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN bookshelf@0.13.3 requires a peer of knex@>=0.6.10 <0.15.0 but none was installed.
npm WARN jwt_db@1.0.0 No description
npm WARN jwt_db@1.0.0 No repository field.
npm ERR! Linux 4.15.0-34-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install" "--save" "bcrypt"
npm ERR! node v0.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@3.0.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 7
npm ERR! 
npm ERR! Failed at the bcrypt@3.0.1 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/karim/node/jwt_db/npm-debug.log

**Comment by KarimMohamed2005** [comment]
Solved

**Comment by KennPunt** [comment]
> Solved

how?
