### ISSUE TITLE
Failed at the bcrypt@*** install script 'node-gyp rebuild'.

### ISSUE THREAD

**Issue by unckleg** [kelektiv/node.bcrypt.js#664]
Problem is same as in: #476

We should move to: https://www.npmjs.com/package/bcryptjs

Library have bug and should be fixed instead of closing issues.

**Comment by agathver** [comment]
Try including `request` module, `npm i request`. `node-pre-gyp` used `needle` which does not work with github. This should fix the installation issues.

**Comment by kaysiz** [comment]
@agathver that worked for me.

**Comment by xavierfuentes** [comment]
bcryptjs is around 30% slower... :(

**Comment by Wikinaut** [comment]
> Try including `request` module, `npm i request`. `node-pre-gyp` used `needle` which does not work with github. This should fix the installation issues.

Please include this 
* in your installation code
* in your installation instructions

**Comment by hbi99** [comment]
Too much hassle..it just doesn't work building docker images with newer node-alpine versions.
[bcrypt.js](https://github.com/dcodeIO/bcrypt.js) works just fine and with zero dependencies.
