### ISSUE TITLE
Move to prebuild

### ISSUE THREAD

**Issue by recrsn** [kelektiv/node.bcrypt.js#665]
`node-pre-gyp` has been causing a lot of installation errors. Move to [prebuilt](https://github.com/prebuild/prebuild). This should fix most of the installation errors.

_This task is high priority_

**Comment by hroland** [comment]
+1

**Comment by thom-nic** [comment]
I've created a branch that uses prebuildify.  https://github.com/thom-nic/node.bcrypt.js/tree/prebuildify-and-docker-build

It builds locally on darwin-x64 and I can create prebuilds in a Docker container for linux-x64.  I have Dockerfile definitions to cross-build for armhf and aarch64.  Builds succeed on both of those environments however unit tests fail.  I would love to get some eyes on the failing tests.

To start with Docker build like this:
```
# Build everything and run unit tests:
docker build -t thom/bcryptjs-linux-x64-builder .   
# Create a container just so we can copy the artifacts from the host (for deployment)
docker create --name donut thom/bcryptjs-linux-x64-builder
docker cp donut:/usr/local/opt/bcrypt-js/prebuilds .
```
Then you'll see (on MacOS, have already built locally):
```
± ls -lF prebuilds
total 0
drwxr-xr-x  3 thom  staff  96 Sep  2 22:20 darwin-x64/
drwxr-xr-x  3 thom  staff  96 Sep  2 22:20 linux-x64/
```
To run the armhf build, it is similar but add -f to choose a different docker file:
```
docker build -t thom/bcryptjs-linux-aarch64-builder -f Dockerfile-aarch64 .
```
To not run the failing tests then start an interactive session for test/debugging, do:
```
docker build -t voltserver/bcryptjs-linux-aarch64-builder -f Dockerfile-aarch64 --build-arg=RUN_TESTS=false .
docker run -it --name donut-aarch64 voltserver/bcryptjs-linux-aarch64-builder /bin/bash -l
```
As a baseline I'm going to try running the unit tests on a native armhf device and see if unit tests pass or fail there.

Feedback welcome.

**Comment by recrsn** [comment]
Thanks a lot @thom-nic

**Comment by thom-nic** [comment]
@recrsn would you like me to submit a PR?  I made some tweaks so it is as merge-friendly as possible.

**Comment by recrsn** [comment]
@thom-nic Please submit a PR, I can check why the tests are failing

**Comment by JasonMan34** [comment]
@recrsn Any idea when v6 will be released?
