### ISSUE TITLE
Second argument must be a 16 byte Buffer

### ISSUE THREAD

**Issue by dsudzy** [kelektiv/node.bcrypt.js#673]
After upgrading from 1.0.3 to 3.0.2 I get the error: 
`node_modules/bcrypt/bcrypt.js:82
        bindings.gen_salt(minor, rounds, randomBytes, cb);
                 ^
TypeError: Second argument must be a 16 byte Buffer`

in my code I have just as I did before and as it is stated in the docs:
`bcrypt.hash(req.body.password, 10, function(err, hash)  {`

using node v8.9.3

has this function changed but the docs have not? why might I be getting this error here?

**Comment by agathver** [comment]
Could you please provide a small example code that reproduces this. Your function call looks fine to me.

Also, please try `npm rebuild bcrypt`.

Please be warned that Node v8.9 is problematic. NodeJS broke the ABI.

**Comment by agathver** [comment]
You have mismatching native module and JavaScript code. Rebuild the underlying module with npm rebuild bcrypt
