### ISSUE TITLE
Remove aws-sdk as a dependecy

### ISSUE THREAD

**Issue by greenboxal** [kelektiv/node.bcrypt.js#680]
Bumping #607 as using webpack has nothing to do with running on node/backend.

There's no reason at all to have aws-sdk as dependency, it's not used anywhere and only installing tons of unnecessary packages.

**Comment by EdanKriss** [comment]
Mind if I ask why bundling is not supported?

Are there any alternatives supported for generating single minified bundle for app using bcrypt?

**Comment by agathver** [comment]
Bundling is not supported as this is a native extension and relies on a compiled dynlib for working. You can build a workaround by loading the dynlib yourself. Patches are welcome to make it bundling friendly. aws-sdk is a transitive dev dependency (on which I have no control)
