### ISSUE TITLE
Any async function from bindings not working

### ISSUE THREAD

**Issue by trmaphi** [kelektiv/node.bcrypt.js#681]
* What went wrong?
Bcrypt from npm installation not working with following script
```
const bcrypt = require('bcrypt');

console.log(bcrypt);

bcrypt.hash('This is plain text password', 10, function(err, hash) {
    console.log(err);
    console.log(hash);
 });
```
Result in console:
```
{ genSaltSync: [Function: genSaltSync],
  genSalt: [Function: genSalt],
  hashSync: [Function: hashSync],
  hash: [Function: hash],
  compareSync: [Function: compareSync],
  compare: [Function: compare],
  getRounds: [Function: getRounds] }
```
* Which version of nodejs and OS?
```
❯ node --version
v8.9.0
❯ npm --version
5.5.1
❯ [System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      17134  0
❯ MSBuild.exe /version
Microsoft (R) Build Engine version 15.8.169+g1ccb72aefa for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

15.8.169.51996
```

**Comment by trmaphi** [comment]
The problem might be npm scripts. I going to `node_modules\bcrypt\`, trying to run `npm install` and test the script again, it still doesn't work. But after, I use `npm run test`, then it work?

**Comment by trmaphi** [comment]
Running `npm run install --build-from-source` does make it works.

**Comment by trmaphi** [comment]
I download source code and run `npm install`. This time, I try to add code at the end of `bcrypt.js` to test
```
crypto.randomBytes(16, function(error, randomBytes) {
    if (error) {
        cb(error);
        return;
    }

    bindings.gen_salt('b', 10, randomBytes, function(err, hash) {
        console.log(err);
        console.log(hash);
    });
});
```

No output at console

**Comment by agathver** [comment]
Do you, somehow have transitive dependencies that install bcrypt and were not deduped?

This happens all the time when we have multiple versions of bcrypt native library loaded into Node.
