### ISSUE TITLE
[DEP0106] DeprecationWarning

### ISSUE THREAD

**Issue by theOpric** [kelektiv/node.bcrypt.js#686]
i was using bcrypt.js.I saw warning text on terminal;
-(node:7884) [DEP0106] DeprecationWarning: crypto.createDecipher is deprecated.

I just want to say that for the arrangements.

Thanks for bcrypt.js and i'm sorry to bad english.

**Comment by agathver** [comment]
We don't use it anywhere. Perhaps you meant to look into `bcrypt.js`

**Comment by agathver** [comment]
https://github.com/dcodeIO/bcrypt.js
