### ISSUE TITLE
bcrypt@3.0.3 install: `node-pre-gyp install --fallback-to-build`

### ISSUE THREAD

**Issue by lucasmunafo** [kelektiv/node.bcrypt.js#692]
I have the same issue as everyone i tried everythong but the prob still there please can u help me with it?

`bcrypt@3.0.3 install: `node-pre-gyp install --fallback-to-build``

package.json:
`  "dependencies": {
    "bcryptjs": "^2.4.3",
    "body-parser": "^1.18.3",
    "express": "^4.16.4",
    "mongoose": "^5.4.0",
    "morgan": "^1.9.1",
    "multer": "^1.4.1",
    "request": "^2.88.0"
  },`

[2018-12-30T18_54_42_961Z-debug.log](https://github.com/kelektiv/node.bcrypt.js/files/2717427/2018-12-30T18_54_42_961Z-debug.log)

VERSIONS:
      npm: 6.4.1
      node: v10.14.2

**Comment by ihteshamqazi** [comment]
Any solutions to this

**Comment by Jack89ita** [comment]
Same here

**Comment by agathver** [comment]
Install dependencies. It's mentioned everywhere in the README

**Comment by rkarami** [comment]
i installed dependencies, locally and globally but nothing changed!

**Comment by Akshay-Rana-Gujjar** [comment]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@3.0.3 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@3.0.3 install script.

Facing same issue.
Old version works fine.

**Comment by Akshay-Rana-Gujjar** [comment]
version 3.0.1 works fine

**Comment by andersonmendesdev** [comment]
Version 3.0.2 same problem.

**Comment by zabahey** [comment]
I think we should follow the instruction to install this library. Please click [here](https://github.com/kelektiv/node.bcrypt.js/wiki/Installation-Instructions)

**Comment by Fenny** [comment]
Same issue, I noticed I could not hash passwords for my users after I updated the node version.

**Comment by orgertot** [comment]
I installed the dependencies but still no prebuild ...

**Comment by zhuhang-jasper** [comment]
tried?
`npm install --global --production windows-build-tools`

**Comment by XadillaX** [comment]
@multinerd I have the same issue. Why there's no 3.0.3's v64?

**Comment by djanowski** [comment]
3.0.2 does work on Node 10 / macOS.

**Comment by ACPK** [comment]
@djanowski  - 3.0.2 did not work on my Mac.

**Comment by Mujahid122418** [comment]
bcrypt@3.0.6 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@3.0.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by nezlicodes** [comment]
Fixed it by installing the dependecies: https://github.com/kelektiv/node.bcrypt.js/wiki/Installation-Instructions

**Comment by diamond95** [comment]
it works for me after installing visual studio 2019( c++ desktop development ), python 3.8.0 and 
npm install -g node-gyp
npm install --g --production windows-build-tools
npm install bcrypt

**Comment by krishheii** [comment]
Please try this it will definitely work, this error occur because you are not using a stable version of node
`npm install --save bcryptjs && npm uninstall --save bcrypt
`

**Comment by edgargaza** [comment]
@diamond95 worked for me, just pointing it out!

**Comment by vjainlion** [comment]
Steps:-
1 npm install --global --production windows-build-tools(from the shell as administrator)
2 npm i bcrypt.

**Comment by theclabs** [comment]
it's a permissions issue in AWS
try 
cd project
chmod 777 node_modules
npm install bcrypt -save
chmod go-w node_modules

or 
cd proyect 
echo "# Force npm to run node-gyp also as root, preventing errors in AWS with npm@5 or @6" >> .npmrc
echo "unsafe-perm=true" >> .npmrc
npm install

**Comment by ericjeker** [comment]
You can check the list of pre-built releases here: https://github.com/kelektiv/node.bcrypt.js/releases

One should match your OS and Node version. 

As of today, on Windows, only 3.0.6 is pre-built for Node 12.x. That's not ideal but at least you can avoid downloading the MS dependencies by fixing the version in your package.json.

**Comment by elsoftsolutions** [comment]
This is due to unstable version of Node version.  
1. Install stable version of node with 
sudo npm cache clean -f
sudo npm install -g n
sudo n stable

2. Make sure you follow the instructions here: https://github.com/kelektiv/node.bcrypt.js/wiki/Installation-Instructions#ubuntu-and-derivatives---elementary-linux-mint-etc

3. install package with root permission:
sudo npm install  --unsafe-perm=true --allow-root

**Comment by PulkitAgg** [comment]
I was facing this issue because of my node js version 12.8.3. I just changed my node version to 12.4.1. And then try to install bcrypt using npm i bcrypt. Now its working fine for me.

Check/Download Different Node.js version from this [Link](https://nodejs.org/en/download/releases/)

**Comment by jonntan** [comment]
Try installing node-pre-gyp again then npm installing any missing modules.

```node
npm i node-pre-gyp
```
