### ISSUE TITLE
Bcrypt Installation error `node-pre-gyp install --fallback-to-build`

### ISSUE THREAD

**Issue by rigalpatel001** [kelektiv/node.bcrypt.js#695]
I am trying to Install bcrypt but getting errors. I have also tired to install older version but still getting same error.

I had tried  to globally install dependancy NPM "node-gyp" but still getting errors.

Error screenshot 
https://screencast.com/t/ADSe6khYE6pm

`> bcrypt@3.0.3 install /Users/rigalpatel/rect-practice/vidly-api-node/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.3/bcrypt_lib-v3.0.3-node-v64-darwin-x64-unknown.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for bcrypt@3.0.3 and node@10.9.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:239:12)
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/rigalpatel/rect-practice/vidly-api-node/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/Users/rigalpatel/rect-practice/vidly-api-node/node_modules/bcrypt/lib/binding" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd /Users/rigalpatel/rect-practice/vidly-api-node/node_modules/bcrypt
gyp ERR! node -v v10.9.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/rigalpatel/rect-practice/vidly-api-node/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/Users/rigalpatel/rect-practice/vidly-api-node/node_modules/bcrypt/lib/binding --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/rigalpatel/rect-practice/vidly-api-node/node_modules/bcrypt/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:250:5)
node-pre-gyp ERR! System Darwin 17.5.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/rigalpatel/rect-practice/vidly-api-node/node_modules/bcrypt/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/rigalpatel/rect-practice/vidly-api-node/node_modules/bcrypt
node-pre-gyp ERR! node -v v10.9.0
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/rigalpatel/rect-practice/vidly-api-node/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/Users/rigalpatel/rect-practice/vidly-api-node/node_modules/bcrypt/lib/binding --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
npm WARN vidly@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@3.0.3 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@3.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

**Environments**

OS:  Mac 10.13.4
Node 10.9.0
NPM 6.2.0

Thanks

**Comment by rigalpatel001** [comment]
I just install and configure xcode and bcrypt is working fine.

**Comment by ACPK** [comment]
@herlarb - This did not work for me. Any other suggestions?

**Comment by mewajda** [comment]
I just started experiencing this in my ci/cd pipeline on azure devops.  I am using the Ubuntu 16.04 agent. I haven’t changed/updated any packages.

**Comment by Hosein-mh** [comment]
new version of bcrypt make that error 
use verseion 3.0.2 or lower
`npm install --save bcrypt@3.0.2`

**Comment by Badestrand** [comment]
@agathver Everyone hates gyp and it just doesn't work for so many people. Can we not try to get rid of it? I don't exactly know what it does, but maybe a makefile could replace it?

**Comment by tonitomystery** [comment]
I had the same problem using alpine but I solved it with this:
1. `apk add --no-cache python make g++`
2. `npm install`

**Comment by mollibethcox** [comment]
I'm currently having this problem and none of the answers are working for me. Help??

**Comment by abolishperson** [comment]
Same I just got here this morning

**Comment by mollibethcox** [comment]
@abolishperson I used bcryptjs instead and it worked fine in my code. Doesn't have nearly as many issues.
