### ISSUE TITLE
How to avoid bcrypt generating hashes with a slash?

### ISSUE THREAD

**Issue by deemeetree** [kelektiv/node.bcrypt.js#696]
https://stackoverflow.com/questions/54269808/how-to-avoid-bcrypt-node-adding-slashes-to-the-hash?noredirect=1#comment95362518_54269808

**Comment by agathver** [comment]
We cannot. It will make hashes incompatible with other implementations. bcrypt hashes are base64 encoded, which includes `/` in its charset. Alternatively, you can do your manual transformations over the generated hash, or build your own implementation with the base_64 encoding that substitutes `/` with something else.
