### ISSUE TITLE
Support for Node 11

### ISSUE THREAD

**Issue by MerzDaniel** [kelektiv/node.bcrypt.js#701]
Hi 

Node 11 currently doesn't seem to be supported. 

Also the local build using 
`npm rebuild --build-from-source bcrypt` and 
`npm rebuild --update-binary bcrypt` 
fail locally. 

We are currently checking our dependencies concerning the upcoming Node12 release. 

Is Node 11 / 12 support planned in the (near) future?

Thanks in advance!
Daniel

**Comment by agathver** [comment]
Node 11 is supported. Node 12 support has also landed on NPM

**Comment by MerzDaniel** [comment]
Ok seems to be working with current version 3
