### ISSUE TITLE
package includes node_modules?

### ISSUE THREAD

**Issue by wmertens** [kelektiv/node.bcrypt.js#704]
You can see for yourself at https://unpkg.com/bcrypt@3.0.4/ - there is a node_modules directory which has node-pre-gyp and all its dependencies.

Is this intentional? It wasn't there in the 2.0 releases.

**Comment by agathver** [comment]
`node-pre-gyp` used to recommended bundling because older NPM versions did not install it predictably. Now they have stopped recommending it.

This is some debt we need to get rid of in a future release.

**Comment by agathver** [comment]
Cleaned up in v3.0.5
