### ISSUE TITLE
404 bcrypt error when building docker container

### ISSUE THREAD

**Issue by austinyearlykim** [kelektiv/node.bcrypt.js#706]
currently bcypt v3.0.4

404 on when building docker container with all alpine versions 8+:

https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.4/bcrypt_lib-v3.0.4-node-v67-linux-x64-musl.tar.gz

I noticed at:
https://github.com/kelektiv/node.bcrypt.js/releases

there is: bcrypt_lib-v3.0.4-node-v67-linux-x64-glibc.tar.gz

instead of *glibc*.tar.gz, my npm is looking for *musl*.tar.gz

let me know if i can be of any more help

**Comment by austinyearlykim** [comment]
https://github.com/kelektiv/node.bcrypt.js/wiki/Installation-Instructions

this was incredibly helpful if anyone was having this problem.

my issue was i was using an alpine version.  i previously wasnt using bcrypt in a previous build and didnt notice it was a package i shouldve adjusted my Dockerfile for

**Comment by agathver** [comment]
We would love to have musl (alpine) builds available.
