### ISSUE TITLE
Help: Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Jeff-Tian** [kelektiv/node.bcrypt.js#708]
Env: Node version 10

the following code

```
const bcrypt = require("bcrypt");

const a = bcrypt.hash('123', 10)
console.log('a = ', a)
```

generates the following error:

```
Segmentation fault (core dumped)
```

Can anyone shed some light on this?

**Comment by Jeff-Tian** [comment]
Fixed it by downgrade it from 3.0.4 to 3.0.3.

**Comment by agathver** [comment]
Could you please share the OS and NodeJS versions?

Also, do you have a multiple libraries depending on bcrypt by chance?

>

**Comment by Jeff-Tian** [comment]
As mentioned in the question, I met that error in node 10.

For the OS, it's docker image of node:10.15-alpine.

**Comment by agathver** [comment]
I think you are copying node_modules from the host into the docker. This occurs when there is a mismatch between libC runtimes. Alpine uses musl-libc and the host probably uses glibc.

Make sure you have `node_modules` in `.dockerignore` and perform an `npm install` inside the docker. Also, bcrypt in alpine-node will require a source compile. So you need python, make and gcc as well. 

https://github.com/kelektiv/node.bcrypt.js/wiki/Installation-Instructions

**Comment by Jeff-Tian** [comment]
Thanks!
