### ISSUE TITLE
bcrypt crashes in child process

### ISSUE THREAD

**Issue by Suvitruf** [kelektiv/node.bcrypt.js#709]
If you are trying to load bcrypt in child process (worker thread) it will fail with the error:
~~~
Error: Module did not self-register.
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:779:18)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (O:\Texts\Sources\my\bcrypt-shild-process\node_modules\bcrypt\bcrypt.js:6:16)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
~~~

Info:
-
- Node v11.10.0
- bcrypt v3.0.4

I've created sample project for this issue: https://github.com/Suvitruf/bcrypt-child-process-crash-proof

**Comment by agathver** [comment]
What would be the output if it runs?

Can you try experimenting with the n-api version of the module? `npm i bcrypt@napi`

**Comment by Suvitruf** [comment]
I've updated my repo. The output should be:

```
I'm ok, because I'm alpha main
same
I'm sad, because I can't load bcrypt
same
```

Same problem with n-api version.

**Comment by agathver** [comment]
child_process is not same as worker_thread. I guess, we have some issues when multiple threads try to access native libraries.

In my system (Ubuntu 18.04, Node 11.11.0), napi crashes without any error message

**Comment by Suvitruf** [comment]
I'm running it on Windows 7.

**Comment by agathver** [comment]
Here's my code after NAPI modifications: https://github.com/agathver/bcrypt-child-process-crash-proof/tree/napi

I would need to catch hold of a Windows machine to test this.

I saw `worker_threads` are still marked as experimental, and we have warnings about using native modules in electronjs Web workers. Perhaps there may be some bugs in the implementation.

**Comment by Suvitruf** [comment]
> I saw `worker_threads` are still marked as experimental

Yeh, but recently they said that it's kinda stable right now: https://github.com/nodejs/node/pull/25361. You don't even need to use `--experimental-worker` flag anymore.

**Comment by NickNaso** [comment]
I everyone the problem here is that when you use `worker-threads` the addon will be loaded multiple times in multiple contexts and to allow this the addon must support multiple initializations.
My opinion is he it's necessary to modify `brcypt` to be a **[context aware addon](https://docs.nodejs.org/api/addons.html#addons_context_aware_addons)**.  
@agathver @Suvitruf  What do you think about this? Do you agree to apply this change?

**Comment by Suvitruf** [comment]
@NickNaso good idea. But I'm not familiar with native modules =/

**Comment by agathver** [comment]
@NickNaso The module uses no static variables, this change should be trouble free. We need to add a new worker_threads test case too.

**Comment by NickNaso** [comment]
If it's ok for you I will try to work on this issue and solve the problem.

**Comment by agathver** [comment]
Sure go ahead. AFAIK, there are only a few lines of change at bcrypt_node.cc

And the napi version already works out of the box with worker_threads

**Comment by agathver** [comment]
@NickNaso Let me know if you will be able to work on the issue. It's a minor change. Else I would go ahead and publish the version myself

**Comment by NickNaso** [comment]
@agathver if you want go for work on the issue. Unfortunately I had time in this week.

**Comment by khangaridb** [comment]
Any updates on this issue?

**Comment by agathver** [comment]
@khangaridb You can use the napi variant of the module. `npm i bcrypt@napi`

The primary module will be compatible in few days, I did some initial work and it needs some polish before I can publish

**Comment by Suvitruf** [comment]
> You can use the napi variant of the module. `npm i bcrypt@napi`

Which version? `^3.0.6-napi` doesn't work on Windows.

**Comment by agathver** [comment]
napi is 3.0.4, it doesn't quite track mainline bcrypt yet

**Comment by barry1cassidy** [comment]
I have this same problem on windows 10. Any update?

**Comment by yovanoc** [comment]
I have this problem too, even with the napi one, any update?

**Comment by agathver** [comment]
Can you check if v4 solves your problem?

**Comment by NickNaso** [comment]
@agathver  The version 4 is not published on npm, but only available on GitHub.

**Comment by NickNaso** [comment]
> @agathver The version 4 is not published on npm, but only available on GitHub.

Now is on `npm` Thanks to everybody.
