### ISSUE TITLE
Can't start Npm

### ISSUE THREAD

**Issue by Maximillliano** [kelektiv/node.bcrypt.js#710]
[2019-03-10T13_38_53_805Z-debug.log](https://github.com/kelektiv/node.bcrypt.js/files/2949514/2019-03-10T13_38_53_805Z-debug.log)

I was fixing some issues with bcrypt but didn't figured out if I corrected it or not. Now is the problem with "gulp build", maybe I did something wrong? Can you help me plz?

node: v10.15.3
npm: 6.4.1

**Comment by agathver** [comment]
Doesn't seem like a bcrypt error to me. Program crashes with a SIGABRT, there can be several reasons behind it.
