### ISSUE TITLE
bcrypt install fails using npm but is successful with yarn and pnpm (NodeJS versions 8.15.1 and 10.15.3)

### ISSUE THREAD

**Issue by cocomatt** [kelektiv/node.bcrypt.js#711]
Thanks for reporting a new issue with the node bcrypt module!

To help you resolve your issue faster please make sure you have done the following:

* Searched existing issues (even closed ones) for your same problem
* Make sure you have installed the required dependencies listed on the readme
* Read your npm error log for lines telling you what failed, usually it is a problem with not having the correct dependencies installed to build the native module

Once you have done the above and are still confident that the issue is with the module, please describe it below. Some things that really help get your issue resolved faster are:

* What went wrong?

Bcrypt does not install on a brand new project with no dependencies. NodeJS 8.15.1/NPM 5.10.0 and NODEJS 10.15.3/NPM 6.4.1. Installation via yarn or pnpm worked on both versions of node however.

* What did you expect to happen?

I expected bcrypt to install.

* Which version of nodejs and OS?

NodeJS 8.15.1/NPM 5.10.0 and NodeJS 10.15.3/NPM 6.4.1.

Mac OS 10.13.6 but using a VM:

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
```

* If you find a bug, please write a failing test.

**NodeJS 8.15.1/NPM 5.10.0**

```
vagrant [testBcrypt]> npm install bcrypt
npm WARN testBcrypt@1.0.0 No description
npm WARN testBcrypt@1.0.0 No repository field.

npm ERR! path /vagrant/testBcrypt/node_modules/bcrypt/node_modules/minipass/node_modules/safe-buffer/package.json.192514024
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/vagrant/testBcrypt/node_modules/bcrypt/node_modules/minipass/node_modules/safe-buffer/package.json.192514024'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

```
**NodeJS 10.15.3/NPM 6.4.1**

```
vagrant [testBcrypt]> npm install bcrypt
npm WARN testBcrypt@1.0.0 No description
npm WARN testBcrypt@1.0.0 No repository field.

npm ERR! path /vagrant/testBcrypt/node_modules/bcrypt/node_modules/minipass/node_modules/safe-buffer/package.json.2761945069
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/vagrant/testBcrypt/node_modules/bcrypt/node_modules/minipass/node_modules/safe-buffer/package.json.2761945069'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```
Please refer to [this stackoverflow question](https://stackoverflow.com/questions/55229246/cant-install-bcrypt-on-server-for-vuejs-2-6-9-webpack-4-29-6-project-using-node)

Thanks!

P.S. If it doesn't look like you read the above then your issue will likely be closed without further explanation. Sorry, but there are just too many issues opened with no useful information or questions which have been previously addressed.

**Comment by agathver** [comment]
Did you try with a folder other than /vagrant? May be some folder under home which is not shared with the host. 

I tried it on a Linux host and it did not happen. I use virtualbox provider and

**Comment by YasharF** [comment]
I can not produce the issue on node 12.8 / npm 610.2.

Is this still an issue? Can this be marked as resolved?
