### ISSUE TITLE
bcrypt v3.0.5 failing in windows x64

### ISSUE THREAD

**Issue by 47arathore** [kelektiv/node.bcrypt.js#713]
Thanks for reporting a new issue with the node bcrypt module!

To help you resolve your issue faster please make sure you have done the following:

* Searched existing issues (even closed ones) for your same problem
* Make sure you have installed the required dependencies listed on the readme
* Read your npm error log for lines telling you what failed, usually it is a problem with not having the correct dependencies installed to build the native module

Once you have done the above and are still confident that the issue is with the module, please describe it below. Some things that really help get your issue resolved faster are:

* What went wrong?
npm install failing for bcrypt v3.0.5 due to the binaries not being there.
It is failing while downloading it from  `https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.5/bcrypt_lib-v3.0.5-node-v64-win32-x64-unknown.tar.gz`
which is not there in downloads, giving 404.

* What did you expect to happen?
Needed the required binary to be there
`https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.5/bcrypt_lib-v3.0.5-node-v64-win32-x64-unknown.tar.gz`

* Which version of nodejs and OS?
NodeJs v10 and Windows 10 OS

* If you find a bug, please write a failing test.

Thanks!

P.S. If it doesn't look like you read the above then your issue will likely be closed without further explanation. Sorry, but there are just too many issues opened with no useful information or questions which have been previously addressed.

**Comment by agathver** [comment]
Thanks for reporting. For some reason, it was not automatically pushed from Appveyor. Uploaded the release manually.

**Comment by martianboy** [comment]
@agathver There's no pre-built binary for v67 (Node 11) either. And compiling from the source gives the following error:

```
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  blowfish.cc
  bcrypt.cc
  bcrypt_node.cc
  win_delay_load_hook.cc
c1xx : fatal error C1083: Cannot open source file: '..\src\bcrypt_node.cc': No such file or directory [C:\Users\Abbas\Project\node_modules\bcrypt\build\bcrypt_lib.vcxproj]
c1xx : fatal error C1083: Cannot open source file: '..\src\bcrypt.cc': No such file or directory [C:\Users\Abbas\Project\node_modules\bcrypt\build\bcrypt_lib.vcxproj]
c1xx : fatal error C1083: Cannot open source file: '..\src\blowfish.cc': No such file or directory [C:\Users\Abbas\Project\node_modules\bcrypt\build\bcrypt_lib.vcxproj]
```

**Comment by agathver** [comment]
Not sure about why you would get a file not found error.

Binaries have been updated.

**Comment by martianboy** [comment]
Thank you!
