### ISSUE TITLE
Automatic computation of salt rounds based on target hash time

### ISSUE THREAD

**Issue by cdhowie** [kelektiv/node.bcrypt.js#714]
Would it be possible to implement a feature where we can ask `bcrypt.hash` to target a specific amount of time (0.5 seconds for example) when comparing the password later?  This would effectively automatically determine the number of salt rounds, using a large enough value to get comparisons to take _at least_ the specified amount of time (obviously on the current hardware).

**Comment by agathver** [comment]
It is possible. There is a benchmark script that recommends the rounds to use. I'm not very convinced to add an automatic round guessing mode. You could always perform in your application code. 

13 rounds on current systems will be 0.5 seconds.
