### ISSUE TITLE
Prebuild binaries for Node 12 LTS (v72)

### ISSUE THREAD

**Issue by frlinw** [kelektiv/node.bcrypt.js#721]
Currently, bcrypt requires a manual build to work with the latest Node 12

**Comment by agathver** [comment]
It's because Node 12 was released very recently and I haven't got the time to generate a prebuilt binary unfortunately

**Comment by frlinw** [comment]
I know, don't worry, it's nothing more than a reminder ;)

**Comment by tmirun** [comment]
Same problem, i am waiting too =)

**Comment by CherryNerd** [comment]
Any idea when it'll be ready to use?
I'd like to be able to use the faster async/await and other V8 improvements of Node 12 :)

**Comment by agathver** [comment]
@CherryNerd You can use it, just install dependencies for source compile. A cyclone hit my city and currently, I am stuck at a place with no power and really poor internet, I cannot promise any ETA about when I would be able to provide a pre-compiled binary for Node 12.

**Comment by tmirun** [comment]
@agathver I hope you are well

**Comment by tmirun** [comment]
@frlinw can you write how to build it manually for the latest Node 12, I start a project with electron 5 and it only working with node 12 =(
ty guy

**Comment by frlinw** [comment]
@tmirun it's in the README: install dependencies then update bcrypt and it will try to build it https://github.com/kelektiv/node.bcrypt.js#dependencies
Note:
Requirement for node-gyp: https://github.com/nodejs/node-gyp#on-windows

**Comment by tmirun** [comment]
@frlinw Oh, right, ty guy I will try it =)

**Comment by netok421** [comment]
Will this be fixed?

**Comment by nosizejosh** [comment]
bcrypt still fails with node 12.14.1

**Comment by orgads** [comment]
ping?

**Comment by orgads** [comment]
Why was this closed?

**Comment by agathver** [comment]
@orgads See #796

Prebuilt libraries are available, NodeJS update has broken the download mechanism. But it is fixed in v5.0.0 which will be released soon
