### ISSUE TITLE
bcrypt 中 bcrypt.genSalt停止运行

### ISSUE THREAD

**Issue by guanghui1995** [kelektiv/node.bcrypt.js#722]
我想使用bcrypt 在保存数据前对密码加盐加密，但是 bcrypt.genSalt没有运行，同时后面的插入等操作也没有运行

**Comment by agathver** [comment]
could you please translate into english?

**Comment by tmirun** [comment]
@agathver hi guy, he said bcrypt.genSalt callback isn't called.

**Comment by tmirun** [comment]
@guanghui1995 你可以用第二个方法,  (you can use the 2n way)
![image](https://user-images.githubusercontent.com/8052536/57387371-7dcbb700-71b6-11e9-9c8f-d47b8c7fd0f8.png)

**Comment by YasharF** [comment]
Is this still an issue? Can this be marked as resolved?
