### ISSUE TITLE
module initialization error: Error

### ISSUE THREAD

**Issue by PranayShastrula** [kelektiv/node.bcrypt.js#724]
Thanks for reporting a new issue with the node bcrypt module!

To help you resolve your issue faster please make sure you have done the following:

* Searched existing issues (even closed ones) for your same problem
* Make sure you have installed the required dependencies listed on the readme
* Read your npm error log for lines telling you what failed, usually it is a problem with not having the correct dependencies installed to build the native module

Once you have done the above and are still confident that the issue is with the module, please describe it below. Some things that really help get your issue resolved faster are:

Am using bcrypt in my aws sam local running on docker container & while doing any request i see below error

module initialization error: Error
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/task/node_modules/bcrypt/bcrypt.js:6:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)

Throwing error at below line of code
const bcrypt = require('bcrypt');

But when I ran the exact same code it worked on my mac.
bcrypt.compareSync(actualValue, hashedValue);
bcrypt.hashSync('value',SALT_ROUNDS);

Below is the simple code I executed.

* What went wrong? - Lambda import itself
* What did you expect to happen? 
* Which version of nodejs and OS? - Node V 11.8.0  & MacOs
* If you find a bug, please write a failing test.

**Comment by agathver** [comment]
You are probably mounting the filesystem inside the container. It causes it
to pickup the module compiled for mac and then error out (Docker for mac is
on a Linux VM).

Make sure you don't copy node_modules into it

**Comment by YasharF** [comment]
Is this still an issue? Can this be marked as resolved?

**Comment by PranayShastrula** [comment]
This was an issue with containers, resolved it
