### ISSUE TITLE
Pre-built binaries not found for bcrypt@3.0.6 and node@12.2.0 (node-v72 ABI, unknown) 

### ISSUE THREAD

**Issue by RyleeAndrews** [kelektiv/node.bcrypt.js#725]
Hi I have exhausted my options in finding a solution for this. My operating system is macOSHighSierra 10.13.6. In the docs i believe it says pre-built binaries for osx are already available. Upon installing bcrypt i get the 404 error of trying to download 

https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.6/bcrypt_lib-v3.0.6-node-v72-darwin-x64-unknown.tar.gz. 

Now i expected everything to download fine because you said the binaries should work on osx but i still see this error. Upon trying to push to heroku I get this log 

Error: The module '/app/server/node_modules/bcrypt/lib/binding/bcrypt_lib.node' was compiled against a different Node.js version using NODE_MODULE_VERSION 72. This version of Node.js requires NODE_MODULE_VERSION 64. Please try re-compiling or re-installing. 

I tried many times to just delete my node modules and install again but no luck. The version of node I am using is node 12.2.0 and of course the latest version of bcrypt 3.0.6. I have installed node-pre-gyp manually and made sure the dependencies were met for that package. Any help would be appreciated thanks.

**Comment by Sozialarchiv** [comment]
What I did with max os x 14.4:

1. I deleted node_modules
1. yarn globall add node-gyp
1. yarn install

After that it was working.

In the beginning I had the problem that yarn was using another node then my development environment. I fixed, that by removing the second node version.

**Comment by agathver** [comment]
NodeJS 12 binaries are not up yet.

You can have such error only if you are pushing compiled node_modules from
local to heroku.


Alternativelv perform an npm rebuild bcrypt to fix your local version

>

**Comment by saifali96** [comment]
I have tried to follow the directions in wiki and ended up compiling it myself via fallback, still if someone looking for the binary `v72` for `node 12` on `Windows 10 64bit`, you may take it from here: https://filebin.net/69cxwjgeytd7feiy

**Comment by saifali96** [comment]
@agathver I wanted to create a PR and share the binary but look like I cannot share binaries via PR?

**Comment by ken0x0a** [comment]
I got same error today.

@agathver That's weird. My build was success before, and now it failed.

code 404 for following URL
https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.6/bcrypt_lib-v3.0.6-node-v72-linux-x64-musl.tar.gz

9 days ago & 4 days ago, it was successfully built. Was that miracle?...

**Comment by YasharF** [comment]
Thank you for the great work @agathver.  It looks like the prebuilt Note 12 binary for OSX/darwin is up, but the Linux and Windows ones aren't there yet.  Is that something that is still on your todo list, or is there an issue with the build process that needs to be fixed?

**Available:**  
- https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.6/bcrypt_lib-v3.0.6-node-v72-darwin-x64-unknown.tar.gz

**Missing:**
- https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.6/bcrypt_lib-v3.0.6-node-v72-linux-x64-glibc.tar.gz
-https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.6/bcrypt_lib-v3.0.6-node-v72-win32-x64-unknown.tar.gz
-https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.6/bcrypt_lib-v3.0.6-node-v72-win32-ia32-unknown.tar.gz


Thanks again!

**Comment by Ardi83** [comment]
for windows 10 this worked  for me: 
npm install --global --production windows-build-tools

ref link: https://github.com/kelektiv/node.bcrypt.js/wiki/Installation-Instructions

**Comment by baktash93** [comment]
I had a similar issue:

    node-pre-gyp WARN Using request for node-pre-gyp https download
    node-pre-gyp WARN Tried to download(404): 
    https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.4/bcrypt_lib-v3.0.4-node-v72- 
    linux-x64-glibc.tar.gz
    node-pre-gyp WARN Pre-built binaries not found for bcrypt@3.0.4 and node@12.16.1 (node-v72 
    ABI, glibc) (falling back to source compile with node-gyp)

This issue arises mainly because of different global and local versions of `node` and that the node-gyp compilation happens with the node installed globally on your system for which the _pre-built binaries_ are not available. 

### **Solution**
The solution is to install a global (_possibly earlier_) version of node for which the _prebuilt binaries_ for node-gyp is available.

**Comment by imechemi** [comment]
[node-gyp](https://github.com/nodejs/node-gyp) has 88% python code. So you might be running an older version of bcrypt which needs node-gyp that requires older python versions. 

If you can create python2 environment using `pyenv`, then you will have a successful build. Refer [pyenv guide](https://realpython.com/intro-to-pyenv/), it's simple. 

What I did.

1. `pyenv local 2.7.13`
2. `npm install` 

It worked.
