### ISSUE TITLE
72 bytes not characters?

### ISSUE THREAD

**Issue by cullylarson** [kelektiv/node.bcrypt.js#731]
The readme says:

> Per bcrypt implementation, only the first 72 characters of a string are used. Any extra characters are ignored when matching passwords.

However, isn't it actually the first 72 **bytes** that are used? If the string is UTF-8 encoded and has e.g. emojis, it could potentially be truncated before 72 characters.

**Comment by agathver** [comment]
> However, isn't it actually the first 72 bytes that are used? If the string is UTF-8 encoded and has e.g. emojis, it could potentially be truncated before 72 characters.

Yes

**Comment by YasharF** [comment]
@cullylarson would you be able to submit a PR for updating the readme?

**Comment by cullylarson** [comment]
@YasharF Yeah, I can do that.
