### ISSUE TITLE
Salt rounds 20 not working

### ISSUE THREAD

**Issue by pSnehanshu** [kelektiv/node.bcrypt.js#734]
Bcrypt doesn't seem to work when Salt round is passed 20
```javascript
var token = await bcrypt.hash('abcxyz', 20);
// It just hangs there
```
But passing 10 works perfectly.

**Comment by agathver** [comment]
Salt rounds 20 will make 10^20 rounds, this will take almost 6 years to return a result.

**Comment by nfahrni** [comment]
Not really 6 years. More like 1 - 2 minutes depending on your CPU.
