### ISSUE TITLE
403 forbidden when downloading package from curl or npm

### ISSUE THREAD

**Issue by jfdoube** [kelektiv/node.bcrypt.js#738]
Since today we are getting 403 from AWS s3 bucket when trying to download the S3 bucket.

It seems that it's either encoding of the url or HEAD that is not allow in the bucket.

here's an example url.

https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.2/bcrypt_lib-v3.0.2-node-v64-linux-x64-glibc.tar.gz

Can you please check urgently as it is preventing us to deploy.

**Comment by YasharF** [comment]
It sounds like the issue may have been with AWS.  The link you provided downloads for me.  Can this issue be closed?
