### ISSUE TITLE
Bcrypt install fails with json error

### ISSUE THREAD

**Issue by MD-AZMAL** [kelektiv/node.bcrypt.js#742]
I am using kali linux x64. I tried installing bcrypt but it gave me the following error. I have attached the log below.
Please help.

```shell
root@loopaz:~/Project Files/temp# npm -v
6.4.1
root@loopaz:~/Project Files/temp# node -v
v8.16.0
root@loopaz:~/Project Files/temp# npm install bcrypt
npm ERR! Unexpected end of JSON input while parsing near '...dirp":"~0.5.0","rc":"'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-07-22T06_42_19_920Z-debug.log

```

**Comment by agathver** [comment]
Network issue and please do not install as root. It will fail in a different step

**Comment by MD-AZMAL** [comment]
Thanks @agathver 

actually i run kali on root so had to install it in root. There was a problem with npm cache so i cleaned it and while installing i used --unsafe-perm and there were no issues.
