### ISSUE TITLE
cannot install Bcrypt

### ISSUE THREAD

**Issue by mindquaker** [kelektiv/node.bcrypt.js#746]
Thanks for reporting a new issue with the node bcrypt module!

To help you resolve your issue faster please make sure you have done the following:

* Searched existing issues (even closed ones) for your same problem
* Make sure you have installed the required dependencies listed on the readme
* Read your npm error log for lines telling you what failed, usually it is a problem with not having the correct dependencies installed to build the native module

Once you have done the above and are still confident that the issue is with the module, please describe it below. Some things that really help get your issue resolved faster are:

* What went wrong?
* What did you expect to happen?
* Which version of nodejs and OS?
* If you find a bug, please write a failing test.

Thanks!

P.S. If it doesn't look like you read the above then your issue will likely be closed without further explanation. Sorry, but there are just too many issues opened with no useful information or questions which have been previously addressed.

**Comment by mindquaker** [comment]
$ npm i bcrypt@3.0.2

> bcrypt@3.0.2 install C:\Users\Ashutosh\Desktop\Secrets-Starting-Code\Secrets - Starting Code\node_modules\bcrypt
> node-pre-gyp install --fallback-to-build

'node' is not recognized as an internal or external command,
operable program or batch file.
npm WARN secrets@1.0.0 No description
npm WARN secrets@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@3.0.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@3.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ashutosh\AppData\Roaming\npm-cache\_logs\2019-07-26T14_01_40_525Z-debug.log

**Comment by agathver** [comment]
You probably don't have nodejs in PATH of the current session. Try adding
it and restarting.

>

**Comment by YasharF** [comment]
Is this still an issue?  Can this be closed?
