### ISSUE TITLE
WebAssembly

### ISSUE THREAD

**Issue by lastmjs** [kelektiv/node.bcrypt.js#747]
I've searched through the issues in this repository and the bcryptjs repository: https://github.com/dcodeIO/bcrypt.js, and it seems like no one is discussing this.

I think it could be useful to compile bcrypt to WebAssembly. Benefits:

* Combine bcrypt for Node.js and bcryptjs, one universal binary for all popular JS engines
* Remove requirement to compile for individual CPU architectures
* Near native performance

WebAssembly could simplify a lot of installation and distribution requirements, and still maintain good performance. I hope it will be considered.

**Comment by lastmjs** [comment]
Wow, I was just looking through the other open issues a bit...shipping a WebAssembly binary I imagine could fix most of those issues

**Comment by YasharF** [comment]
The reason to use this project is that the server ends up with a compiled C code producing a higher performance.  Applications compiled to WebAssembly run slower by an average of 45% (Firefox) to 55% (Chrome), with peak slowdowns of 2.08x (Firefox) and 2.5x (Chrome).  See https://arxiv.org/abs/1901.09056

For anyone that is not interested in the higher-performing native code, there is a different project: https://www.npmjs.com/package/bcryptjs

**Comment by kroleg** [comment]
@YasharF does performance matters for bcrypt algorithm? I thought that bcrypt is intentionally slow. Btw you can just decrease amount of rounds to speed it up

**Comment by YasharF** [comment]
> @YasharF does performance matter for bcrypt algorithm?

Yes
