### ISSUE TITLE
Salt shows up as first part of hash? 

### ISSUE THREAD

**Issue by NealWalters** [kelektiv/node.bcrypt.js#749]
I'm not overly familiar with salts and hashes, but don't you hash the password and salt together? 
In my tests, I'm always seeing the Salt at the beginning of the hash result. 
Looks to me like you are hashing the password, then just concatenating the salt at the beginning.  I was going to create a different salt for each user, and store in a separate database column. 

```
const bcrypt = require('bcrypt');
const saltRounds = 10;
var salt = bcrypt.genSaltSync(saltRounds);
console.log("salt=" + salt);

var  myPlaintextPassword = '12345';
var hash1 = bcrypt.hashSync(myPlaintextPassword, salt);
console.log("hash1=" + hash1); 

myPlaintextPassword = '67890';
var hash2 = bcrypt.hashSync(myPlaintextPassword, salt);
console.log("hash2=" + hash2); 
```

Results: 

> salt=$2b$10$40ssPEeuGp6J43tqQtzNC.
> hash1=$2b$10$40ssPEeuGp6J43tqQtzNC.NVaeuOVFR0tR9jB8IUFJarNnMjDnb.i
> hash2=$2b$10$40ssPEeuGp6J43tqQtzNC.SJrDsV4U8GNXMTQTJEFK4lOrpjusxGy

Thanks,
Neal

**Comment by ncb000gt** [comment]
Yep. This is correct and is a part of the bcrypt algorithm.

You can read more about it here: https://en.wikipedia.org/wiki/Bcrypt
