### ISSUE TITLE
Problem using compare when hashed password comes from database

### ISSUE THREAD

**Issue by freis** [kelektiv/node.bcrypt.js#75]
Don't know what's the problem but when i try the examples everything works fine but when i store the hash in the db and then try to compare it it gives me false.

to store it:
var salt = bcrypt.genSaltSync(10);  
var hash = bcrypt.hashSync(password, salt);
User.registerUser(login, hash);

to get it:
User.authenticateUser(login, function(err,user){
    result = bcrypt.compareSync(password, user.password);
    console.log(result);
});
this gives me one user base on the username and then i use the password to compare them

**Comment by mtterranova** [comment]
I am also having an issue with compare if the hashed password comes from my database. Below is a snippet of my auth model:

```javascript
const db = require('../db/db');
const bcrypt = require('bcrypt');

module.exports = {

	signUp: (req, res) => {
	   var firstName = req.body.firstName;
	   var lastName = req.body.lastName;
	   var username = req.body.username;
	   var plainPassword = req.body.password;
		
	   bcrypt.genSalt(10, (err, salt) => {
	      bcrypt.hash(plainPassword, salt, (err, hash) => {
                 db.connection.query('INSERT INTO database.Users VALUES ("' + firstName + '","' + lastName + '","' + username + '","' + hash + '")', (err, result) => {
                    if (err) {
		       console.log(err);
		    } else {
		       console.log(result);
		    }
		 });
	      });
           });
	},

	login: (req, res) => {
	   var username = req.body.username;
	   var plainPassword = req.body.password;
	   var hashedPassword;

	   db.connection.query('SELECT password FROM database.Users WHERE username = "' + username + '" ', (err, result) => {
	      if (err) {
	         console.log(err);
	      } else {
	         hashedPassword = result[0].password;	
	         bcrypt.compare(plainPassword, hashedPassword, (err, result) => {
	            if (err) {
	               console.log('bcrypt - error - ', err);
	            } else {
	               console.log('bcrypt - result - ', result);
	            }
	         });
	      }
	   });
	}
```
The result from the compare method is always false. There is no error, it just believes that the plainPassword does not match the hashed one. If I add the compare method to "signUp", the result will be true. The problem only occurs if I use the hash after it has been stored in my database. 

I can store a plaintext password to the database and compare it to the same word and everything is good. The result I get from the database is a string so that isn't the problem. The compare method just doesn't like the bcrypt hash that comes from the database.

Any ideas?

**Comment by cur4so** [comment]
the same issue here. I use bcrypt.hashSync and bcrypt.compareSync. Though in my case comparison of the password with the result of  bcrypt.hashSync right after it has been generated, return false for all passwords I've tried. 
Reading this thread sounds like it may work or it may not, nobody knows in advance.

**Comment by cur4so** [comment]
I figured it out: bcrypt.hashSync(arg,...) returns a decent hash while arg is undefined

**Comment by bachdgvn** [comment]
It's may be your password field in your db is too short to save byscrypt hashed password.

**Comment by Mahmoudibrahim03** [comment]
have the same problem 👎

**Comment by Diferno** [comment]
Hi, I have the exact same problem. I was working with bcrypt, moved to AWS Lambdas and used bcryptjs and things that were working, started to crash.

Here's my flow. Please help me Obi Wan Kenobi, you're my only hope.

```
The user registers with email and password:
wtf2@gmail.com | asdfasdf

var salt = bcrypt.genSaltSync(5)
return bcrypt.hash(password, salt)
  .then(hashedPassword => {
    console.log(`${hashedPassword}`)
```    
CONSOLE LOG OUTPUTS=>  $2a$05$dqfejDWGqzNjY8FdcmQgvew7NM5Tq8Nre/eHgLpq7FTSPQ967HqlC

then on the login process:
```
var email= wtf2@gmail.com  
var password = asdfasdf

var salt = bcrypt.genSaltSync(5)
var hash = bcrypt.hashSync(password, salt)
console.log(hash)
```
CONSOLE LOG OUTPUTS=>	$2a$05$KegwBuVW40lepuGbWeAV4OU3fEgDg8v1kOkxHqXEsaKLtScx6Xup6
```
var hashedPassword = bcrypt.hashSync(user.password.toString(), salt)
console.log(hashedPassword)
```
CONSOLE LOG OUTPUTS=>  $2a$05$KegwBuVW40lepuGbWeAV4OhGtF2ig63j3ATymU3aY9HxjzvuFu/zy
```
bcrypt.compare(password, hashedPassword)
  .then(isValid => {
    console.log(`isPassword valid? ${isValid}`)
```
CONSOLE LOG OUTPUTS=>  isPassword valid? false



Field in MySql is defined as Binary(200) to avoid truncation things.

Any help, pls?

**Comment by orshee** [comment]
Having the same problem using promises.
Figured out that field nvarchar(100) was not long enough, 
nvarchar(120) fixed it for 60 char hash

**Comment by bhaskr11** [comment]
Same issue. Changing my length of password field in mysql database to 150 chars helped solve this issue.

**Comment by InnocentZaib** [comment]
Please help me my password hash compare returns false when i compare my password from database

userSchema.statics.findByCredentials = async (email, password) => {
    const user = await User.findOne({ email })

    console.log(user.password) // Getting same password like stored in MongoDB

    if(!user) {
        throw new Error('Unable to login')
    }
    const isMatch = await bcrypt.compare(password, user.password)
    console.log(isMatch) // showing false PLEASE HELP ME
if(!isMatch) {
        throw new Error('Unable to login')
    }

    return user

}

**Comment by VigneshMeem** [comment]
I had same issue 
 bcrypt.compareSync(user.password, data.old_pass)
I interchanged changed params 
 bcrypt.compareSync(data.old_pass, user.password)

**Comment by owenwesley** [comment]
I'm kind of having the same problem, when I run it locally it works just fine but when I connect it to my online database through 1 and 1.com I can add a user just fine but when I go to login it gives me invalid password. here is a code snippet....

const express = require('express');
const router = express.Router();
const connection = require('../../db/Connection');
const bcrypt = require('bcryptjs');

const SELECT_USER_QUERY = 'SELECT * FROM users';

router.post('/', (req, res) => {
  let { userName, password = req.body.password } = req.query;

  connection.query(
    SELECT_USER_QUERY + ` WHERE userName=?`,
    [userName],
    (error, results) => {
      if (error) throw error;
      if (!userName || !password) {
        return res.status(400).send({ message: 'No info' });
      } else {
        if (results.length > 0 || password === '') {
          bcrypt.compare(password, results[0].password, (err, result) => {
            if (result) {
              return res.send({ message: 'Login Successful' });
            } else {
              return res.status(400).send({ message: 'Invalid Password' });
            }
          });
        } else {
          return res.status(400).send({ message: 'Invalid userName' });
        }
      }
    }
  );
});

module.exports = router;

**Comment by agathver** [comment]
@owenwesley This is a different module

**Comment by AmosSpark** [comment]
Issue with bcrypt.compare. 

+ doing:

let user = await User.findOne({email: req.body.email});

* user will return a user document that match the email in the req.body.email
* user.password will return the hashed password value in the returned user document. 

+ doing:

const comparePassword = await bcrypt.compare(req.body.password,user.password);

* returns a TypeError: Cannot read property "password" of null.

**Comment by agathver** [comment]
perhaps `req.body` is null  @AmosSpark

**Comment by ormoon** [comment]
> Issue with bcrypt.compare.
> 
> **doing:
> 
> let user = await User.findOne({email: req.body.email});
> 
> * user will return a user document that match the email in the req.body.email
> * user.password will return the hashed password value in the returned user document.
> 
> ** doing:
> 
> const comparePassword = await bcrypt.compare(req.body.password,user.password);
> 
> * returns a TypeError: Cannot read property "password" of null.

May be you haven't use body parser....
const app = require('express')();
app.use(express.json())

**Comment by ormoon** [comment]
> Issue with bcrypt.compare.
> 
> **doing:
> 
> let user = await User.findOne({email: req.body.email});
> 
> * user will return a user document that match the email in the req.body.email
> * user.password will return the hashed password value in the returned user document.
> 
> ** doing:
> 
> const comparePassword = await bcrypt.compare(req.body.password,user.password);
> 
> * returns a TypeError: Cannot read property "password" of null.

**Comment by AmosSpark** [comment]
@agathver @ormoon yes, I didn't use body-parser in main file. Fixed and thank you.

**Comment by Webeon** [comment]
Hi everyone. I also faced problems with 'bcrypt' package. Try to use 'bcryptjs' instead

**Comment by chwasifjameel** [comment]
@Webeon I'm using bcryptjs and facing the same issue. Tried everything mentioned above and nothing was wrong.

**Comment by hanipro91** [comment]
change length of password in database to more than 512+SALT_ROUND+6

**Comment by Bottomline2sky** [comment]
> Hi everyone. I also faced problems with 'bcrypt' package. Try to use 'bcryptjs' instead
at the bottom I  found the tiny but amazing answer

**Comment by ahmerdevopsinertia** [comment]
Despite other answers, if it is still not resolving your issue.  Try by applying the **toString()** when passing the password upon login like this.

**result = bcrypt.compareSync(password.**toString()**, user.password);**

**Comment by harshad4321** [comment]
through the signup form, I insert  name, password, and email in the DataBase, and the password is encrypted it is successful. but, I created a login form through which I inserted the same email and password but *** bcrypt. compare*** is only getting login failed.

```
var objectId=require('mongodb').ObjectId
 

module.exports={
    doSignup:(userData)=>{
        return new Promise (async(resolve,reject)=>{
         userData.password=  salt=   await bcrypt.genSalt(10);
             await  bcrypt.hash(userData.password,10,(err, password,hash) => {
                if(err) throw (err);
                 else
                password=hash
                  db.get().collection(collection.USER_COLLECTION).insertOne(userData).then((data)=>{
                    resolve(data.insertedId) 
                    // console.log(userData.password)
                    // console.log(userData.email)                    
                });
                });
            }); 
     },
        
     doLogin: (userData) => {
        return new Promise(async (resolve, reject) => {
            let loginStatus = false
            let response = {}
            let user = await db.get().collection(collection.USER_COLLECTION).findOne({ email: userData.email })
            if (user) {
                bcrypt.compare(userData.password, user.password,(error,isMatch) => {
                    console.log(user.password)
                    console.log(userData.password)
                    if (error) {
                        console.log('login failed due to err');
                        // resolve({status: false})
                    } else {
                        if (isMatch) {
                            console.log("login success...");
                            // response.user=user
                            // response.status=true
                            // resolve(response)
                        } else {
                            console.log('login failed try again');
                        // resolve({status: false})
                        }
                    }
                })
            } else {
                console.log("login failed because email is not there..")
                //     resolve({status: false})
            }
        })
    
    }
```
I was asked the same question two days ago in StackOverflow. but, No solution was found.  [](https://stackoverflow.com/q/72284986/18701654)

**Comment by harshad4321** [comment]
through the signup form I insert my name, password, and email in the DataBase and the password is encrypted it is successful. but, I created a login form through that I inserted the same email and same password but *** bcrypt. compare*** is only getting login failed.

```

var objectId=require('mongodb').ObjectId
 

module.exports={
    doSignup:(userData)=>{
        return new Promise (async(resolve,reject)=>{
         userData.password=  salt=   await bcrypt.genSalt(10);
             await  bcrypt.hash(userData.password,10,(err, password,hash) => {
                if(err) throw (err);
                 else
                password=hash
                  db.get().collection(collection.USER_COLLECTION).insertOne(userData).then((data)=>{
                    resolve(data.insertedId) 
                    // console.log(userData.password)
                    // console.log(userData.email)                    
                });
                });
            }); 
     },
        
     doLogin: (userData) => {
        return new Promise(async (resolve, reject) => {
            let loginStatus = false
            let response = {}
            let user = await db.get().collection(collection.USER_COLLECTION).findOne({ email: userData.email })
            if (user) {
                bcrypt.compare(userData.password, user.password,(error,isMatch) => {
                    console.log(user.password)
                    console.log(userData.password)
                    if (error) {
                        console.log('login failed due to err');
                        // resolve({status: false})
                    } else {
                        if (isMatch) {
                            console.log("login success...");
                            // response.user=user
                            // response.status=true
                            // resolve(response)
                        } else {
                            console.log('login failed try again');
                        // resolve({status: false})
                        }
                    }
                })
            } else {
                console.log("login failed because email is not there..")
                //     resolve({status: false})
            }
        })
    
    }
```

**Comment by hanipro91** [comment]
> through the signup form, I insert name, password, and email in the DataBase, and the password is encrypted it is successful. but, I created a login form through which I inserted the same email and password but *** bcrypt. compare*** is only getting login failed.
> 
> ```
> var objectId=require('mongodb').ObjectId
>  
> 
> module.exports={
>     doSignup:(userData)=>{
>         return new Promise (async(resolve,reject)=>{
>          userData.password=  salt=   await bcrypt.genSalt(10);
>              await  bcrypt.hash(userData.password,10,(err, password,hash) => {
>                 if(err) throw (err);
>                  else
>                 password=hash
>                   db.get().collection(collection.USER_COLLECTION).insertOne(userData).then((data)=>{
>                     resolve(data.insertedId) 
>                     // console.log(userData.password)
>                     // console.log(userData.email)                    
>                 });
>                 });
>             }); 
>      },
>         
>      doLogin: (userData) => {
>         return new Promise(async (resolve, reject) => {
>             let loginStatus = false
>             let response = {}
>             let user = await db.get().collection(collection.USER_COLLECTION).findOne({ email: userData.email })
>             if (user) {
>                 bcrypt.compare(userData.password, user.password,(error,isMatch) => {
>                     console.log(user.password)
>                     console.log(userData.password)
>                     if (error) {
>                         console.log('login failed due to err');
>                         // resolve({status: false})
>                     } else {
>                         if (isMatch) {
>                             console.log("login success...");
>                             // response.user=user
>                             // response.status=true
>                             // resolve(response)
>                         } else {
>                             console.log('login failed try again');
>                         // resolve({status: false})
>                         }
>                     }
>                 })
>             } else {
>                 console.log("login failed because email is not there..")
>                 //     resolve({status: false})
>             }
>         })
>     
>     }
> ```
> 
> I was asked the same question two days ago in StackOverflow. but, No solution was found. [] https://stackoverflow.com/q/72284986/18701654

you problem is here: {userData.password=  salt=  ...} you just reset user password to salt. instead use {salt = ...}

**Comment by lylest** [comment]
same problem here

**Comment by AkshayJ0shi** [comment]
> same problem here

Use bcrypt.compareSync instead of bcrypt.compare. It worked for me.

**Comment by hirantravassos** [comment]
> You do not need to store the salt. I would try generating a new user. maybe the password was misstyped? I did a basic hash and compare test and it works for me.
> 
> what version of node.js and bcrypt library are you using?

Jesus Christ, I had a duplicated user... of course it didn't cross my mind on that.......

Your comment saved me, tnx @defunctzombie !!!

**Comment by AlexFabra** [comment]
I had the same error. bcrypt.compareSync(password, hash) always returned false. In my case, in the database I had the 'password' column with collation armscii8_bin and when I passed it to utf8_general_ci it worked as expected.
