### ISSUE TITLE
cant install 3.0.6 on win10 

### ISSUE THREAD

**Issue by ray0324** [kelektiv/node.bcrypt.js#750]
![1](https://user-images.githubusercontent.com/5204198/63217271-eb07c480-c175-11e9-8366-a2c45a74718e.png)

node version:  v12.8.0
node-gyp version: 5.0.3

node-gyp configure
![2](https://user-images.githubusercontent.com/5204198/63217278-302bf680-c176-11e9-8268-7e8d4d30b9ee.png)

**Comment by agathver** [comment]
You have some additional package.json which is interfering the compilation

**Comment by ray0324** [comment]
Use Node 10.16.3  it works!
