### ISSUE TITLE
Failed when compared hash generated by online generator

### ISSUE THREAD

**Issue by valdineifer** [kelektiv/node.bcrypt.js#753]
Hey guys.
Maybe I'm being a noob with cryptography and BCrypt, but I confused with one thing.
I was using this package to login API request. I noticed that when I used a bcrypt online generators, the `bcrypt.compare()` fails.

I use the following websites:
https://bcrypt-generator.com/
https://www.bcryptgenerator.com/

I also test the script on Repl.it
https://repl.it/@valdinei/bcrypt-test

Locally, i'm using the Node v10.16.3 and the Repl.it is using v10.16.0

I don't know if this is really a bug, so I prefer not mark as one.

Thanks for helping!

**Comment by agathver** [comment]
$2y$ is John the Ripper specific, we do not support it explicitly. Changing `y` to `b` should work
