### ISSUE TITLE
Python 2 will be deprecated in a little more than 3 months

### ISSUE THREAD

**Issue by madacol** [kelektiv/node.bcrypt.js#754]
> We have decided that January 1, 2020, will be the day that we sunset Python 2.That means that we will not improve it anymore after that day, even if someone finds a security problem in it. You should upgrade to Python 3 as soon as you can.
 **Source:** https://www.python.org/doc/sunset-python-2/

The dependency **node-gyp**, depends on python 2.

There seems to be much progress going on https://github.com/nodejs/node-gyp/pull/1844

I opened this basically to keep track of **node-gyp** status, until they release a version which defaults to python 3.

**Comment by DRoet** [comment]
it's worth noting that `node-gyp` : `6.0.0` has been released that accepts Python 3 by default

**Comment by cclauss** [comment]
Please use __node-gyp >= 6.0.1__ because that point release has some key updates.
https://github.com/nodejs/node-gyp/blob/master/CHANGELOG.md

**Comment by agathver** [comment]
We don't bundle node-gyp but use the one provided with NPM.

**Comment by cclauss** [comment]
Perfect.  Then just upgrade npm.
