### ISSUE TITLE
No longer installs

### ISSUE THREAD

**Issue by electic** [kelektiv/node.bcrypt.js#756]
`> bcrypt@3.0.6 install /home/electic/backend/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp ERR! Completion callback never invoked!
node-pre-gyp ERR! System Linux 4.9.0-11-amd64
node-pre-gyp ERR! command "/usr/bin/node" "/home/electic/backend/node_modules/bcrypt/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/electic/backend/node_modules/bcrypt
node-pre-gyp ERR! node -v v11.15.0
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>
npm WARN restify-cors-middleware@1.1.1 requires a peer of restify@2.6.x - 7.x.x but none is installed. You must install peer dependencies yourself.
npm WARN coinhub_processor@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 6
npm ERR! bcrypt@3.0.6 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 6
npm ERR!
npm ERR! Failed at the bcrypt@3.0.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/electic/.npm/_logs/2019-09-23T23_45_30_878Z-debug.log`

It might be related to this: https://github.com/mapbox/node-pre-gyp/issues/477

**Comment by loading189** [comment]
Having the same issue. Have not found a fix yet.

**Comment by davidcostadev** [comment]
Try to use `bcrypt@2` version, it's work to me

**Comment by loading189** [comment]
I was able to use bcrypt@2

**Comment by hedikasmanto** [comment]
I have some issue and can install bcrypt 3.0.6 with add minipass on package.json 
Please follow this link : https://github.com/lovell/sharp/issues/1882#issuecomment-534266128
 
Env : 
OSX 10.14.6
Node 12.10.0
Yarn 1.17.3

**Comment by andyyykerr** [comment]
Installing bcrypt@3.0.2 first as a temporary workaround allowed my failing npm install to complete

**Comment by elssar** [comment]
Can confirm I can install bcrypt now. I think it had something to do with `node-pre-gyp` - https://github.com/mapbox/node-pre-gyp/issues/477

**Comment by elssar** [comment]
Aand looks like another dependency has broke `node-pre-gyp`. This time it is `minizlib`. Getting the following error

```

**Comment by elssar** [comment]
This is only happening on node <=6, due to a change introduced in minizlib v1.3.0. My workaround was to add `minizlib v1.2.2` to my dependencies.

Ref: https://github.com/isaacs/minizlib/issues/9

**Comment by davidcostadev** [comment]
@electic try to run `npm install` again.

**Comment by himanshusinghs** [comment]
> This is only happening on node <=6, due to a change introduced in minizlib v1.3.0. My workaround was to add `minizlib v1.2.2` to my dependencies.
> 
> Ref: [isaacs/minizlib#9](https://github.com/isaacs/minizlib/issues/9)

This actually worked
