### ISSUE TITLE
Error bcrypt@3.0.6   bcrypt@3.0.7 in node 12

### ISSUE THREAD

**Issue by CristianPumaES6** [kelektiv/node.bcrypt.js#760]
* What went wrong?
- Don't let me install bcrypt

* What did you expect to happen?
- It works normally.

* Which version of nodejs and OS?
- v12.12.0

* If you find a bug, please write a failing test.
![image](https://user-images.githubusercontent.com/29841048/67154098-6b07f300-f2bb-11e9-9137-9cdce2cdd116.png)

Thanks!

P.S. also try to install the bcrypt@3.0.7.

**Comment by phonic22** [comment]
node-gyp only works with stable/released versions of node. node v12 is not there yet but it's due to start Active LTS on the 21st Oct.

**Comment by CristianPumaES6** [comment]
![image](https://user-images.githubusercontent.com/29841048/67322504-b77b4a80-f4d6-11e9-9445-6bf8ac3693e2.png)

**Comment by arefsaran** [comment]
> * What went wrong?
> 
> * Don't let me install bcrypt
> 
> * What did you expect to happen?
> 
> * It works normally.
> 
> * Which version of nodejs and OS?
> 
> * v12.12.0
> 
> * If you find a bug, please write a failing test.
>   ![image](https://user-images.githubusercontent.com/29841048/67154098-6b07f300-f2bb-11e9-9137-9cdce2cdd116.png)
> 
> Thanks!
> 
> P.S. also try to install the bcrypt@3.0.7.

just update your node.js(12.13.1)

**Comment by vhcord** [comment]
Delete: NODE_MODULES
Delete: bcrypth -> package.json
open terminal and writte `yarn add bcrypt@3.0.6`

**Comment by lokeshdaiya** [comment]
Facing same issue for below Environment 

Window 10
node 12.13.1

**Comment by CristianPumaES6** [comment]
Good,
I hope to help you, I solve it by installing

  npm install -g node-gyp
  npm install -g node-pre-gyp
  npm install --save bcrypt@3.0.2
  npm install --save types/bcrypt@3.0.0

I hope it helps you
Regards!

PSD: Looking for a job: C
https://www.linkedin.com/in/cristianpumaes6/
