### ISSUE TITLE
why i can install 3.0.6,bug i can't install 3.0.7

### ISSUE THREAD

**Issue by CQzhangshuai** [kelektiv/node.bcrypt.js#768]
why i can install 3.0.6,bug i can't install 3.0.7

**Comment by agathver** [comment]
If it's windows then please wait till we upload pre-compiled binaries

**Comment by simplecommerce** [comment]
@agathver when do you think the pre-compiled binaires will be available?

**Comment by 2JJ1** [comment]
The issue still exists. I ended up reverting back to 3.0.6.

**Comment by adogbeji** [comment]
Hi guys,
I've used this package before and never had any issues. This time, I tried installing it and got errors inside the command line and couldn't see what I'd done wrong. This package is currently being updated, so these issues aren't OUR fault. Once everything has been sorted out on their end, things should revert back to normal. 
In the meantime, I recommend using the previous version of bcrypt; that is version 3.0.6. You can get access to it by running this command in your terminal:

npm install bcrypt@3.0.6

Hope this helps!

**Comment by SHIVAMSINGH0101** [comment]
> Hi guys,
> I've used this package before and never had any issues. This time, I tried installing it and got errors inside the command line and couldn't see what I'd done wrong. This package is currently being updated, so these issues aren't OUR fault. Once everything has been sorted out on their end, things should revert back to normal.
> In the meantime, I recommend using the previous version of bcrypt; that is version 3.0.6. You can get access to it by running this command in your terminal:
> 
> npm install bcrypt@3.0.6
> 
> Hope this helps!

Installing older version helped. Thanks
