### ISSUE TITLE
v3.0.7 release missing windows .tar.gz files

### ISSUE THREAD

**Issue by alexandre-combemorel** [kelektiv/node.bcrypt.js#770]
Hi all,

when trying to install Keystone (https://github.com/keystonejs/keystone) this package attempt to fetch the latest version of bcrypt (3.0.7) and attempt to download this url:

[https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.7/bcrypt_lib-v3.0.7-node-v72-win32-x64-unknown.tar.gz](https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.7/bcrypt_lib-v3.0.7-node-v72-win32-x64-unknown.tar.gz)

I just wondered why 3.0.6 and previous version have the windows package and not 3.0.7?
I would like to avoid to modify the keystone package in order to fetch the right dependency.

Many thanks.

**Comment by alexandre-combemorel** [comment]
Apologies I haven't red properly before:
https://github.com/kelektiv/node.bcrypt.js/issues/768#issuecomment-557792008

however be aware that this break other dependencies like Keystonejs to work has it seems they haven't fix the version of bcrypt in their subdependencies.

**Comment by serkaneo** [comment]
![2019-12-23_21-10-47](https://user-images.githubusercontent.com/52151765/71373579-c65ea600-25c8-11ea-991c-fd43e26c1f17.png)
