### ISSUE TITLE
Prebuild releases for window

### ISSUE THREAD

**Issue by enneid** [kelektiv/node.bcrypt.js#775]
From version 3.0.7 windows prebuild releases are not  not avaiable. Are there are planned to be add in latest versions?

**Comment by mgodu01** [comment]
waiting for it

**Comment by ramijarrar** [comment]
Looks like they have now been added to the release in [3.0.8](https://github.com/kelektiv/node.bcrypt.js/releases/tag/v3.0.8).

**Comment by simplecommerce** [comment]
@ramijarrar Seems to be only for NodeJS 13? I am on NodeJS 8 so I assume it won't work for now.

**Comment by simplecommerce** [comment]
Didn't work for me on v8.10.0 (node), I had to fallback to 3.0.6.

**Comment by agathver** [comment]
Node 8 is EOL. No compiled binaries will be provided for EOL versions

**Comment by simplecommerce** [comment]
@agathver That's what I figured, thanks, I will work on updating my version of node instead.
