### ISSUE TITLE
Version 4 doenst work with node 8.15

### ISSUE THREAD

**Issue by bobo-le** [kelektiv/node.bcrypt.js#786]
After upgrading to Bcrypt4.0.0 node exits without an error message.
The documentation says Node8.15 should work with Bcrypt <= 4.0.0
Is this right, or should it be <4.0.0?

With Node12.10 it works fine.

Thank you.

**Comment by mhaamann** [comment]
According to the changelog it looks like the support for Node8 was dropped: https://github.com/kelektiv/node.bcrypt.js/blob/master/CHANGELOG.md

**Comment by bobo-le** [comment]
#785 should then be merged..
