### ISSUE TITLE
Linux-alpine issue

### ISSUE THREAD

**Issue by yk3lee** [kelektiv/node.bcrypt.js#788]
Hello,

I am trying to dockerizing my nodejs app with bcrypt@4.0.1

I am still getting the following error when I try to run my node js dockerized app.

api_1  | 
api_1  | > mapnote-api@1.0.0 start /app
api_1  | > npx ts-node src/index.ts
api_1  | 
api_1  | Error starting server: Error loading shared library /app/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node: Exec format error
api_1  | npm ERR! code ELIFECYCLE
api_1  | npm ERR! errno 255
api_1  | npm ERR! mapnote-api@1.0.0 start: `npx ts-node src/index.ts`
api_1  | npm ERR! Exit status 255
api_1  | npm ERR! 
api_1  | npm ERR! Failed at the mapnote-api@1.0.0 start script.
api_1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
api_1  | 
api_1  | npm ERR! A complete log of this run can be found in:
api_1  | npm ERR!     /root/.npm/_logs/2020-03-03T08_49_20_740Z-debug.log

---

here are my Dockerfile

FROM node:12.6-alpine

# Create app directory
WORKDIR /app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

# RUN apk --no-cache add --virtual builds-deps build-base python
# RUN npm install
# RUN npm rebuild bcrypt --build-from-source 
# RUN apk add --no-cache make gcc g++ build-base python
# RUN npm rebuild bcrypt --build-from-source

# RUN apk add --no-cache make gcc g++ build-essential python && \
#     npm install && \
#     npm rebuild bcrypt --build-from-source && \
#     apk del make gcc g++ python

RUN apk --no-cache add --virtual builds-deps build-base python && \
    npm install && \
    npm rebuild bcrypt --build-from-source

# Bundle app source
COPY . .

EXPOSE 3000
CMD [ "npm", "start" ]

It looks like it still has some issue with running bcrypt on node12.6-alpine image.

Thanks

**Comment by agathver** [comment]
Check again, the CI had uploaded corrupted binaries

**Comment by hckhanh** [comment]
Hi @yk3lee, I wanna ask what is the base image you choose to create your image with bcrypt.

**Comment by AdriVanHoudt** [comment]
Is it possible that the darwin binary is missing for 4.0.1?
`Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v4.0.1/bcrypt_lib-v4.0.1-napi-v3-darwin-x64-unknown.tar.gz `
(if not related I can open a new issue)

**Comment by david-golightly-leapyear** [comment]
@AdriVanHoudt you are correct that the Darwin binary is missing; however, the docs explicitly say that binaries sometimes take days to arrive after a build is published. Arguably it doesn't make sense to publish a build until the binaries are ready, particularly since this library doesn't build with python 3, but publishing at least gives the option for users to figure it out on their own.

**Comment by AdriVanHoudt** [comment]
Yeah this is not blocking me or anything and I've seen before that binaries came in later, just wanted to give y'all a heads up.
Is there anything I can do to help getting MacOS binaries out there?

**Comment by agathver** [comment]
@AdriVanHoudt Yes the darwin binary was also missing. I uploaded those
