### ISSUE TITLE
Installation failed bcrypt@4 on windows 10

### ISSUE THREAD

**Issue by dasith91** [kelektiv/node.bcrypt.js#789]
```
1237 verbose node v12.14.1
1238 verbose npm  v6.13.6
1239 error code ELIFECYCLE
1240 error errno 1
1241 error bcrypt@4.0.1 install: `node-pre-gyp install --fallback-to-build`
1241 error Exit status 1
1242 error Failed at the bcrypt@4.0.1 install script.
1242 error This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by agathver** [comment]
Please post the full log.

If it's a download problem, please retry or use the full installation instructions available on the wiki

**Comment by dasith91** [comment]
Thanks for your feedback. I think its dependency issue because of I was used python v3. After I installed python v2 and I just ran the following then tried the install and it worked

```
npm install -g node-gyp
npm install --g --production windows-build-tools
```

**Comment by dasith91** [comment]
Thanks for your feedback. I think its dependency issue because of I was
used python v3.

After I installed python v2 and I just ran the following then tried the
install and it worked

npm install -g node-gyp
npm install --g --production windows-build-tools
