### ISSUE TITLE
mkdirp@0.5.3: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)

### ISSUE THREAD

**Issue by ridoy19** [kelektiv/node.bcrypt.js#791]
Thanks for reporting a new issue with the node bcrypt module!

To help you resolve your issue faster please make sure you have done the following:

* Searched existing issues (even closed ones) for your same problem
* Make sure you have installed the required dependencies listed on the readme
* Read your npm error log for lines telling you what failed, usually it is a problem with not having the correct dependencies installed to build the native module

Once you have done the above and are still confident that the issue is with the module, please describe it below. Some things that really help get your issue resolved faster are:

* What went wrong?
* What did you expect to happen?
* Which version of nodejs and OS?
* If you find a bug, please write a failing test.

Thanks!

P.S. If it doesn't look like you read the above then your issue will likely be closed without further explanation. Sorry, but there are just too many issues opened with no useful information or questions which have been previously addressed.

**Comment by Rahul626** [comment]
I am also getting same messagae:
For my new laptop fassing issue  while trying to install React Native.
 Processing template
× Installing dependencies
error Error: Command failed: npm install
npm WARN deprecated mkdirp@0.5.4: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)

![image](https://user-images.githubusercontent.com/42401032/77944333-66b91a80-72dc-11ea-80ff-a8b73ea7924f.png)

**Comment by DRoet** [comment]
this problem is located in the upstream `node-pre-gyp` project so we'd have to wait for a fix there.
