### ISSUE TITLE
Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.8/bcrypt_lib-v3.0.8-node-v64-linux-x64-musl.tar.gz 

### ISSUE THREAD

**Issue by keeratita** [kelektiv/node.bcrypt.js#793]
Hi there,

I tried to search in the issue but there is no related to my issue. (the same version of bcrypt).

* What went wrong?

I got this error from my docker.
```
[0m[91mnode-pre-gyp WARN Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.8/bcrypt_lib-v3.0.8-node-v64-linux-x64-musl.tar.gz 
node-pre-gyp WARN[0m[91m Pre-built binaries not found for bcrypt@3.0.8 and node@10.16.3 (node-v64 ABI, musl) (falling back to source compile with node-gyp) 
```

Once you have done the above and are still confident that the issue is with the module, please describe it below. Some things that really help get your issue resolved faster are:

* What did you expect to happen?

Install it completely

* Which version of nodejs and OS?

I use docker `node:10.16.3-alpine`.

* If you find a bug, please write a failing test.

```
FROM node:10.16.3-alpine as server

COPY package*.json ./

RUN apk add --no-cache --virtual .gyp \
  build-base \
  autoconf \
  automake \
  g++ \
  libpng-dev \
  libtool \
  make \
  nasm \
  python \
  git \
  && apk del .gyp

RUN npm install --only=production
```

**Comment by agathver** [comment]
musl binaries are not available for this release
