### ISSUE TITLE
Failing to install prebuild binaries in node v12 and Ubuntu 18.04

### ISSUE THREAD

**Issue by shivarajnaidu** [kelektiv/node.bcrypt.js#796]
* What went wrong ?
When I try to install bcrypt (    "bcrypt": "^4.0.1",
) in ubuntu 18.04 its getting failed with node v12.
After installing build essentials and make its gets compiled in system itself.. but my concern is it is not working with prebuild versions..

* What did you expect to happen?
To be able to install without any issue

* Which version of nodejs and OS?
Output of lab_release below.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic

* If you find a bug, please write a failing test.
![image](https://user-images.githubusercontent.com/12374494/81132583-91962e80-8f6c-11ea-8a6b-53b48c7ad430.png)

Thanks!

**Comment by agathver** [comment]
Looks like an issue with needle again, we had this issue earlier. A workaround will be to run `npm install requests`

**Comment by maxorlovsky** [comment]
@agathver indeed it solve the problem. Just a headsup for people who will end up here instead of requests you need to install request package. `npm install request`

**Comment by Brooooooklyn** [comment]
Try [@node-rs/bcrypt](https://github.com/napi-rs/node-rs/tree/master/packages/bcrypt)

**Comment by agathver** [comment]
NodeJS updated their OpenSSL library which broke needle which is used to download binaries.

As a workaround, do `npm install request` to let bcrypt use request to download binaries

https://github.com/mapbox/node-pre-gyp/issues/500
https://github.com/tomas/needle/issues/312
https://github.com/nodejs/node/issues/33254
