### ISSUE TITLE
Want to have document update about combination of bcrypt@4.x and alpine linux

### ISSUE THREAD

**Issue by takayukioda** [kelektiv/node.bcrypt.js#801]
Does bcrypt@4.x support alpine linux (musl binary) by default?
I have try install bcrypt@4.0.1 in alpine linux as I explain in later, so I'm guessing it is.

If so, I would like to have [document](https://github.com/kelektiv/node.bcrypt.js/wiki/Installation-Instructions#alpine-linux-based-images) to be updated.
If this is still experimental and prefer to have rebuilding workaround, it would be lovely to update document as such.

Here's the commands I run to test if I can install bcrypt into alpine without fallback.
```shell
$ docker run -it --rm node:10-alpine sh
/ # cat /etc/alpine-release 
3.11.6
/ # node --version
v10.20.1
/ # mkdir /tmp/workspace && cd /tmp/workspace
/tmp/workspace # echo '{}' > package.json
/tmp/workspace # npm install bcrypt@4.0.1

> bcrypt@4.0.1 install /tmp/workspace/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download 
[bcrypt] Success: "/tmp/workspace/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node" is installed via remote
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN workspace No description
npm WARN workspace No repository field.
npm WARN workspace No license field.

+ bcrypt@4.0.1
added 68 packages from 93 contributors and audited 68 packages in 8.94s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

**Comment by agathver** [comment]
Please go ahead. And yes, it's still experimental

**Comment by takayukioda** [comment]
@agathver 
Since there is no PR feature in wiki, I'll ask for review in here.

Here's the change I made.
https://github.com/kelektiv/node.bcrypt.js/wiki/Installation-Instructions/_compare/f021fb9676cfc8f18159a51683a064a20f99551f

Let me know if I should update the text.

**Comment by takayukioda** [comment]
Seems it was good enough. Closing the issue.
