### ISSUE TITLE
Async/Await - missing 'await' results in match always being 'true'

### ISSUE THREAD

**Issue by jamiecarter7** [kelektiv/node.bcrypt.js#808]
This is more of a food for thought post than a bug issue.

I am building a login system for a personal project and found I had made a glaring error on my login system.

I originally was using bcrypt sync, mainly to do inexperience, but somewhere down the line I had switched to async/await (or so I thought).

My 'async' code:
```
login: async (_ , credentials, context) => {
  // do stuff
  const match = bcrypt.compare(credentials.login.password, user.password);
  // do stuff
}
```

I had (in my inexperience) missed the 'await' when refactoring.

On testing I noticed that my login always occurred as long as the email matched.

After a little digging I found that when the `await` is missing `Promise<boolean>` is returned and this `truthy`.

Following the guide, I changed the code slightly to throw an error if match is not true:
```
async function checkUser(username, password) {
    //... fetch user from a db etc.
 
    const match = await bcrypt.compare(password, user.passwordHash);
 
    if(!match) {
        // throw error
    }
 
    //...
}
```
if `await` is missed it will always return true and the user will always be logged in.

This was not flagged in typescript either until I changed my code:

```
 if(match !== true) {
        // throw error
 }
```

This issue is my fault (and largely due to my inexperience) but I worry others might fall into the mistake by accident. I am thankful that I have been trying to test mongodb santization and security when I found this [Testing is just so vital!].

Maybe there is a way to ensure the if(match) statement fails if await is missed?

**Comment by agathver** [comment]
> Maybe there is a way to ensure the if(match) statement fails if await is missed?

To the best of my JS knowledge, I don't know of a way to make any arbitrary object _falsy_ The Promise object returned will always be truthy.

> Testing is just so vital!

[Follow TDD](http://agiledata.org/essays/tdd.html) 😄 

You don't need to sell your soul to xUnit style stuff as advocated, mocha or jest (BDD style unit tests) will just do fine.
