### ISSUE TITLE
Upload 5.0.0 to npm

### ISSUE THREAD

**Issue by Mokto** [kelektiv/node.bcrypt.js#809]
It seems like 5.0.0 supports node.js 14? Cf 
https://travis-ci.org/github/kelektiv/node.bcrypt.js/jobs/693576154

But not deployed yet.

Thanks!

**Comment by agathver** [comment]
Thr 4.x.x series work file with NodeJS 14

**Comment by orgads** [comment]
When will you deploy 5.0.0? I want it for the binary artifacts.

**Comment by agathver** [comment]
Deployed
