### ISSUE TITLE
Version 5.0.0 symbol lookup error

### ISSUE THREAD

**Issue by GabrielSuttner** [kelektiv/node.bcrypt.js#814]
I just upgraded bcrypt to the newest version (v5.0.0) and it won't build on my server now. I reverted back to the previous version that I was using and everything is working fine. Just in case this is an actual issue I'm posting it here. This is the error code that I'm getting: 

```
$: node server/index.js

node: symbol lookup error: /root/<file>/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node: undefined symbol: napi_add_finalizer
```
Here are the versions of things that are being ran on my digital ocean server.

OS: Ubuntu 18.04.04 
Server: nginx 1.14.0
Node: v8.17.0

I don't care if this is fixed because the other version of bcrypt that I've been using has been working great, just wanted to let you know.

**Comment by agathver** [comment]
5.0.0 does not support node 8. Node 8 is EOL since 1st Jan 2020

**Comment by arihantdaga** [comment]
I am using node 14. Facing the same problem with version 5.0.1
