### ISSUE TITLE
Getting this issue

### ISSUE THREAD

**Issue by dhruvkapoor2707** [kelektiv/node.bcrypt.js#816]
bcrypt@5.0.0 install C:\Users\GM&HM\Desktop\web d\Secrets\node_modules\bcrypt
> node-pre-gyp install --fallback-to-build

The system cannot find the path specified.
internal/modules/cjs/loader.js:960
  throw err;
  ^

Error: Cannot find module 'C:\Users\node-pre-gyp\bin\node-pre-gyp'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm WARN Secrets@1.0.0 No description
npm WARN Secrets@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@5.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@5.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\GM&HM\AppData\Roaming\npm-cache\_logs\2020-07-19T17_57_57_294Z-debug.log

**Comment by agathver** [comment]
Please provide more information, better attach the npm logs

**Comment by DCasely** [comment]
I am also experiencing the same errors...
