### ISSUE TITLE
[nodemon] app crashed

### ISSUE THREAD

**Issue by comroad** [kelektiv/node.bcrypt.js#818]
[nodemon] app crashed - waiting for file changes before starting...

**Comment by agathver** [comment]
Why did it crash?

**Comment by comroad** [comment]
when i use
 const bcrypt = require('bcrypt')

in app.js 
nodemon can't start

**Comment by agathver** [comment]
Please attach stacktrace

**Comment by comroad** [comment]
[nodemon] restarting due to changes...
[nodemon] starting `node app.js`
[nodemon] app crashed - waiting for file changes before starting...

**Comment by jatinverma12** [comment]
I clone this repo and tried running node app.js but could not find app.js

**Comment by Phoscur** [comment]
Using nodemon in conjunction with bcrypt without issues.

**Comment by Naznin22** [comment]
I have exactly the same problem too! The line const bcrypt = require('bcrypt') results in app crashing without showing any error!!! And removing it makes everything fine. I didn't use bcrypt anywhere in the code. Just importing bcrypt alone makes the app crash.

**Comment by yashkondajisonawane** [comment]
try to install slightly older version of bcrypt...
