### ISSUE TITLE
Compare not working

### ISSUE THREAD

**Issue by hyphen1370** [kelektiv/node.bcrypt.js#820]
Hello, 

I tried to used the compareSync to check hash password and it always failed. There is code previously written to use bcrypt to generate hash password. However, the compareSync always return false. So I tried the following with password "Asdf#1234". 

```
let password = "Asdf#1234";
let hashPassword = await bcrypt.hashSync(password, saltRounds)
let validatePassword = await bcrypt.compareSync(password, "$2y$10$xFjEEyPAi42iEl7ERWslj.efA5S./4zQpYkfucH4YPH95zZkZzNWS");
console.log(validatePassword);
```

First, I used https://bcrypt-generator.com/ to generate a hash password for "Asdf#1234" with 10 rounds. After that, I pasted the hash password into the above code and it returned false. 
When I used the generated hash password from above code, it returned true. 

So, is this module doesn't support any hash from external? 

Thanks

**Comment by agathver** [comment]
2y hashes are not directly supported. 2y is a JTR specific extension of
bcrypt.

Replacing y with b _may_ work. Try that. Most external websites use php to
generate bcrypt hashes which in turn uses JTR under the hood.

>
