### ISSUE TITLE
 data and salt arguments required

### ISSUE THREAD

**Issue by miranaitamara** [kelektiv/node.bcrypt.js#823]
Hello;
When I try to connect (login), I have this error 
Error: data and salt arguments required
my code is `const salt = bcrypt.genSaltSync(10);` and ` bcrypt.hashSync(req.body.password, salt),` 
I use `(bcrypt.compareSync(password, data[0].password)` to compare the password and hashed password

I can't find the source of the problem
Thanks!

**Comment by mohammad-a-hossain** [comment]
@miranaitamara  i applied it but data is not defined . so how to set data ? i extract {email, password} = req.body
