### ISSUE TITLE
Error while building a docker image 

### ISSUE THREAD

**Issue by yacineBR** [kelektiv/node.bcrypt.js#824]
# this is the log : 

Error: Error loading shared library /home/node/app/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node: Exec format error

at Object.Module._extensions..node (internal/modules/cjs/loader.js:1206:18)

at Module.load (internal/modules/cjs/loader.js:1000:32)

at Function.Module._load (internal/modules/cjs/loader.js:899:14)

at Module.require (internal/modules/cjs/loader.js:1042:19)

at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:80:39)

at require (internal/modules/cjs/helpers.js:77:18)

at Object.<anonymous> (/home/node/app/node_modules/bcrypt/bcrypt.js:6:16)

at Module._compile (internal/modules/cjs/loader.js:1156:30)

at Module._extensions..js (internal/modules/cjs/loader.js:1176:10)

at Object.require.extensions.<computed> [as .js] (/home/node/app/node_modules/babel-register/lib/node.js:152:7)

at Module.load (internal/modules/cjs/loader.js:1000:32)

at Function.Module._load (internal/modules/cjs/loader.js:899:14)

at Module.require (internal/modules/cjs/loader.js:1042:19)

at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:80:39)

at require (internal/modules/cjs/helpers.js:77:18)

at Object.<anonymous> (/home/node/app/utils/auth.js:2:16)

2020-08-19T12:52:14: PM2 log: App [access-backend:0] exited with code [1] via signal [SIGINT]

2020-08-19T12:52:16: PM2 log: [Watch] Stop watching access-backend

2020-08-19T12:52:16: PM2 log: PM2 successfully stopped

# DockerFile

FROM keymetrics/pm2:12-alpine

RUN mkdir -p /app

WORKDIR /app
ARG NODE_ENV
ENV NODE_ENV $NODE_ENV

COPY package*.json ./

RUN npm cache clean --force && rm -rf node_modules  && npm install

EXPOSE 7777
CMD [ "pm2-runtime", "start", "ecosystem.config.js" ]

**Comment by MnifR** [comment]
+1

**Comment by asmafakhfakh** [comment]
I have the same problem

**Comment by aymenamaraa** [comment]
+1

**Comment by agathver** [comment]
Please do not copy `node_modules` inside Docker. It decreases your build time and prevents this kind of errors from happening.

Use a `.dockerignore` and add `node_modules/` to it

**Comment by tobslob** [comment]
Did anyone solve this problem?

**Comment by tobslob** [comment]
Adding node_modules to .dockerignore solved this.

**Comment by leolowa** [comment]
docker is not detecting changes in the layers above "run npm ..." therefore it does not build the complete image. I solved it by exchanging run position with copy

**Comment by j-labbe** [comment]
I was having the same issue. Fixed by uninstalling bcrypt before building with docker, then adding bcrypt back to `package.json`. When you build with docker after adding bcrypt back to `package.json`, it should complete with no errors.

**Comment by tufac2** [comment]
Workaround for me. Once everything was installed in docker, I uninstalled and install that library.

**Comment by rbourgeat** [comment]
I have the same problem ☹️

**Comment by acnicolasdc** [comment]
Well, actually you should Create a `.dockerignore` file and add `/node_modules` and in your `docker-compose` define an anonymous directory for node modules. 

Volumes:

   `   - /home/node/app/node_modules`


after several attempts, I have realized that it is not necessary to add a script to remove **bcrypt** and then install it.

**Comment by Marcosaurios** [comment]
I found the same issue, and learned in [this article by Richard Kotze](https://www.richardkotze.com/top-tips/install-bcrypt-docker-image-exclude-host-node-modules) that this dependency needs to be build in the SO where is running. 

So, basically after `npm ci`, adding a `RUN npm rebuild bcrypt --build-from-source` command in your dockerfile should make the trick. Addind a anonymous volume will work because volumes are completely managed by Docker, thus by the SO who is running the image.

**Comment by gardelin** [comment]
Adding `node_modules` in `•dockerignore` didn't solve problem for me

**Comment by rahuls360** [comment]
Switching to `bcryptjs` worked for me

**Comment by gkqkehs7** [comment]
make .dockerignore and add /node_modules works for me

**Comment by microchel-git** [comment]
> Switching to `bcryptjs` worked for me

+1

**Comment by thesonpb** [comment]
> Please do not copy `node_modules` inside Docker. It decreases your build time and prevents this kind of errors from happening.
> 
> Use a `.dockerignore` and add `node_modules/` to it

I worked for me

**Comment by jazzybruno** [comment]
Hello if you are facing the same error make sure you try to add the docker ignore file and add the node modules together with the npm debug role then try to rerun it will work 
![image](https://github.com/kelektiv/node.bcrypt.js/assets/95282931/cd545e08-5dba-4e5d-9b9d-ec0331d14e4d)

**Comment by shide1989** [comment]
this is yet another solution that worked for me : 
Simply specify that your container `/app/node_modules` should be anonymous : 
```yml
volumes:
      - /app/node_modules
```

**Comment by ahmnadim** [comment]
Adding node_modules to .dockerignore works for me also.

**Comment by cauta** [comment]
> Adding node_modules to .dockerignore works for me also.

me too, adding docker ignore and volume to docker compose

**Comment by kazim-asif** [comment]
Adding node_modules to .dockerignore solved this.

**Comment by castilloedwin** [comment]
> I've just had the same issue. node_modules was in the docker ignore list;
> 
> the thing is there are two ways to solve the problem, the simplest one is to install bcryptjs instead of bcrypt
> 
> As for the solution for bcrypt (in my case)
> 
> ```
> Here is my **Dockerfile**
> 
> FROM node:16.13.0-alpine
> 
> WORKDIR /app
> 
> COPY ["package.json", "package-lock.json", "./"]
> 
> RUN npm install --silent
> 
> COPY . .
> 
> CMD ["npm", "run", "server"]
> ```
> 
> and the part of **docker-compose.yml** Mind WORKDIR, volumes, double check your paths
> 
> ```
> server:
>     container_name: 'server'
>     build: '.'
>     volumes:
>       - '.:/app:rw'
>       - '/app/node_modules'
>     environment:
>       POSTGRES_URI: 'postgresql://postgres:root@db:5432/database'
>       REDIS_URI: 'redis://redis:6379'
>     links:
>       - 'db'
>       - 'redis'
>     ports:
>       - '5000:5000'
> ```
> 
> So I did a mistake in - '/app/node_modules'

It works for me!

**Comment by HARISHKUMAR023** [comment]
adding node_modules/  .dockerignore file is worked for me , Happy coding !!

**Comment by MarthL** [comment]
adding node_modules/ .dockerignore file and remove node_modules volume worked for me ! thank you very much

**Comment by joker7blue** [comment]
just use **bcryptjs**, it's platform agnostic.  When using **bcrypt** in docker environment, it need to be compiled again in that linux environment

**Comment by cedraz** [comment]
I resolved this issue adding a .dockerignore ignoring the node_modules and the package-lock.json

If you are using more than 1 folder with more than 1 Dockerfile, add a .dockerignore for each folder
