### ISSUE TITLE
I'm using node 12.18.3 and could not install bcrypt@3.0.6. 

### ISSUE THREAD

**Issue by djalle** [kelektiv/node.bcrypt.js#826]
I have done all the instructions incl. all the dependencies and searched the closed/existing issues but still could not install the bcrypt.

I'm using Win10 64, and NodeJS v.12.18.3
please help

npm i bcrypt@3.0.6
npm WARN deprecated bcrypt@3.0.6: versions < v5.0.0 do not handle NUL in passwords properly

> bcrypt@3.0.6 install C:\Users\Djalle\Documents\project03\
> node-pre-gyp install --fallback-to-build

'Security\node_modules\.bin\' is not recognized as an internal or external command,
operable program or batch file.
'Security\node_modules\.bin\' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.
npm WARN authentication@1.0.0 No description
npm WARN authentication@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! bcrypt@3.0.6 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the bcrypt@3.0.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by djalle** [comment]
> Please try with bcrypt 5, 3.0.6 has security issues and is not supported in Node 12

Thanks for the suggestion, I tried it but still same result :(

**Comment by agathver** [comment]
Does your project's node_modules absolute path has a "space" somewhere?

**Comment by djalle** [comment]
> Does your project's node_modules absolute path has a "space" somewhere?

If I understand your mssge correctly, no, there's no "space" on the path. I already have several modules installed and they worked, so I assumed the path should've been fine.

**Comment by djalle** [comment]
I rewrote my code and started all over again, and I successfully installed bcrypt. Still didn't know what went wrong on my previous attempts though.
