### ISSUE TITLE
Improve docs, more details for hash() return value

### ISSUE THREAD

**Issue by alete89** [kelektiv/node.bcrypt.js#828]
Hi guys :)
It would be awesome if you could include an explanation similar to [this](https://stackoverflow.com/questions/20394137/yii-cpasswordhelper-hashpassword-and-verifypassword/20399775#20399775) on the readme for those like me that are getting started it wasn't clear that the salt was included on the result.

Great work, btw! :kissing_heart:

**Comment by agathver** [comment]
Please feel free to add explanations/wiki page for bcrypt hash format or MCF in general.

**Comment by alete89** [comment]
Will do.
