### ISSUE TITLE
Installation Warning

### ISSUE THREAD

**Issue by raj9211** [kelektiv/node.bcrypt.js#836]
I am getting warning after installation of bcrypt@5.0.0 where i have available node version is 12.19.0 and npm version is 6.14.8,  how will it resolve?

**Comment by agathver** [comment]
What is the warning?

**Comment by raj9211** [comment]
![Screenshot (4)](https://user-images.githubusercontent.com/67910476/96476337-b1878900-1252-11eb-9810-fad327e36e1a.png)
...this warning i am getting

**Comment by agathver** [comment]
You can ignore it. It is just to print out how is bcrypt is being installed from remote. 
In the past, we had a lot of bugs due to the transport used in bcrypt.
