### ISSUE TITLE
npm ERR! code ELIFECYCLE npm ERR! errno 1 npm ERR! bcrypt@3.0.2 install: `node-pre-gyp install --fallback-to-build` npm ERR! Exit status 1 npm ERR!  npm ERR! Failed at the bcrypt@3.0.2 install script. npm ERR! This is probably not a problem with npm. There is likely additional logging output above.  npm ERR! A complete log of this run can be found in: npm ERR!     C:\Users\Rohan sharma\AppData\Roaming\npm-cache\_logs\2020-12-04T09_05_44_645Z-debug.log

### ISSUE THREAD

**Issue by rohnshrma** [kelektiv/node.bcrypt.js#842]
Thanks for reporting a new issue with the node bcrypt module!

To help you resolve your issue faster please make sure you have done the following:

* Searched existing issues (even closed ones) for your same problem
* Make sure you have installed the required dependencies listed on the readme
* Read your npm error log for lines telling you what failed, usually it is a problem with not having the correct dependencies installed to build the native module

Once you have done the above and are still confident that the issue is with the module, please describe it below. Some things that really help get your issue resolved faster are:

* What went wrong?
* What did you expect to happen?
* Which version of nodejs and OS?
* If you find a bug, please write a failing test.

Thanks!

P.S. If it doesn't look like you read the above then your issue will likely be closed without further explanation. Sorry, but there are just too many issues opened with no useful information or questions which have been previously addressed.

**Comment by rohnshrma** [comment]
i tried installing bcrypt using npm buti showed the following error

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@3.0.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@3.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Rohan sharma\AppData\Roaming\npm-cache\_logs\2020-12-04T09_05_44_645Z-debug.log

![dsBuffer bmp](https://user-images.githubusercontent.com/59634590/101144958-18b09f80-363f-11eb-98b8-57242c6597a5.png)

**Comment by flaurida** [comment]
I am seeing the same thing, on the new Macbook Pro with M1.

**Comment by recrsn** [comment]
@flaurida M1 Macs are not supported (yet). I do not have the hardware to test on M1 right now. You can install XCode and try to compile the binary yourself.

**Comment by recrsn** [comment]
@rohnshrma Please remove the "&" from the folder name. There is a bug in node that doesn't treat paths with special characters properly.

**Comment by rohnshrma** [comment]
> @rohnshrma Please remove the "&" from the folder name. There is a bug in node that doesn't treat paths with special characters properly.

It try to do, as you suggested
