### ISSUE TITLE
Error while installing on ubuntu 18.04

### ISSUE THREAD

**Issue by arshadwebexcellis** [kelektiv/node.bcrypt.js#843]
npm WARN vidly@1.0.0 No description
npm WARN vidly@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@5.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@5.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-12-09T16_33_36_771Z-debug.log

**Comment by recrsn** [comment]
You are trying to install bcrypt as sudo/root/ It is not supported. Please use as a regular user or enable unsafe permissions with npm
