### ISSUE TITLE
Error While Installing Brcrypt in Ubuntu 18.04 using Node 14.15.3

### ISSUE THREAD

**Issue by Prashanthgm3** [kelektiv/node.bcrypt.js#845]
bcrypt@5.0.0 install /home/prashanthgm/Desktop/Auth Web App/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: The N-API version of this Node instance is 1. This module supports N-API version(s) 3. This Node instance cannot run this module.
node-pre-gyp ERR! stack     at Object.module.exports.validate_package_json (/home/prashanthgm/Desktop/Auth Web App/node_modules/node-pre-gyp/lib/util/napi.js:82:9)
node-pre-gyp ERR! stack     at validate_config (/home/prashanthgm/Desktop/Auth Web App/node_modules/node-pre-gyp/lib/util/versioning.js:229:10)
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (/home/prashanthgm/Desktop/Auth Web App/node_modules/node-pre-gyp/lib/util/versioning.js:279:5)
node-pre-gyp ERR! stack     at install (/home/prashanthgm/Desktop/Auth Web App/node_modules/node-pre-gyp/lib/install.js:241:31)
node-pre-gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/home/prashanthgm/Desktop/Auth Web App/node_modules/node-pre-gyp/lib/node-pre-gyp.js:52:37)
node-pre-gyp ERR! stack     at run (/home/prashanthgm/Desktop/Auth Web App/node_modules/node-pre-gyp/bin/node-pre-gyp:82:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (/home/prashanthgm/Desktop/Auth Web App/node_modules/node-pre-gyp/bin/node-pre-gyp:134:1)
node-pre-gyp ERR! stack     at Module._compile (module.js:652:30)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:663:10)
node-pre-gyp ERR! stack     at Module.load (module.js:565:32)
node-pre-gyp ERR! System Linux 5.4.0-58-generic
node-pre-gyp ERR! command "/usr/bin/node" "/home/prashanthgm/Desktop/Auth Web App/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/prashanthgm/Desktop/Auth Web App/node_modules/bcrypt
node-pre-gyp ERR! node -v v8.10.0
node-pre-gyp ERR! node-pre-gyp -v v0.15.0
node-pre-gyp ERR! not ok 
The N-API version of this Node instance is 1. This module supports N-API version(s) 3. This Node instance cannot run this module.
npm WARN notsup Unsupported engine for bcrypt@5.0.0: wanted: {"node":">= 10.0.0"} (current: {"node":"8.10.0","npm":"6.14.8"})
npm WARN notsup Not compatible with your version of node/npm: bcrypt@5.0.0
npm WARN authapp@1.0.0 No description
npm WARN authapp@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@5.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@5.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/prashanthgm/.npm/_logs/2021-01-01T15_48_16_209Z-debug.log

I am using NodeJS version 14.15.3 in Ubuntu 18.4.05, kindly let me know how to resolve this problem

**Comment by recrsn** [comment]
``` npm WARN notsup Unsupported engine for bcrypt@5.0.0: wanted: {"node":">= 10.0.0"} (current: {"node":"8.10.0","npm":"6.14.8"})```

This line says your NodeJS is 8

**Comment by Prashanthgm3** [comment]
How to resolve this issue???

**Comment by Prashanthgm3** [comment]
Node version- v14.15.3
npm version- 6.14.9
nvm version- 0.37.2

How to change to compatible version of nodejs to work with bcrypt??

**Comment by Crackz** [comment]
Node 14, 15 aren't supported yet. Check [version compatibility](https://github.com/kelektiv/node.bcrypt.js#version-compatibility
)
The latest version that you can use v12.20.1 till now

**Comment by recrsn** [comment]
@Crackz NodeJS version 14 and 15 are supported.

**Comment by recrsn** [comment]
@Prashanthgm3 that will depend on your setup. Do you have multiple NodeJS versions or do you use NVM or similar software to manage?
