### ISSUE TITLE
npm ERR! bcrypt@5.0.0 install: `node-pre-gyp install --fallback-to-build`

### ISSUE THREAD

**Issue by eshan1809** [kelektiv/node.bcrypt.js#846]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@5.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@5.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by eshan1809** [comment]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@5.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@5.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by recrsn** [comment]
Please provide the complete error message, platform and node version

**Comment by eshan1809** [comment]
$ node --version
v14.15.3

Error

$ npm install bcrypt

> bcrypt@5.0.0 install C:\Users\userName\Documents\Visual Studio Code\Web Dev\Learning\Authentication & Security\Secrets\node_modules\bcrypt
> node-pre-gyp install --fallback-to-build

'Security\Secrets\node_modules\.bin\' is not recognized as an internal or external command,
operable program or batch file.
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'C:\Users\userName\Documents\Visual Studio Code\Web Dev\Learning\node-pre-gyp\bin\node-pre-gyp'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm WARN secrets@1.0.0 No description
npm WARN secrets@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@5.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@5.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\userName\AppData\Roaming\npm-cache\_logs\2021-01-06T08_29_23_702Z-debug.log

**Comment by recrsn** [comment]
Remove that `&` in `Authentication & Security`.

It is a known npm bug in windows

**Comment by eshan1809** [comment]
Thanks, it helped
