### ISSUE TITLE
Random lock-ups with Node.js v14.15.4

### ISSUE THREAD

**Issue by TomMettam** [kelektiv/node.bcrypt.js#859]
After updating to NodeJS 14.15.4 (and recompiling the native modules including bcrypt), I found that my application was locking up in strange ways. This is a production application serving a large number of requests.

After a random period, HTTP requests stopped returning, and calls to other native modules failed in a similar fashion.

I eventually narrowed down the issue to a call to `bcrypt.compare` never resolving its promise. While the application continues to function, any further calls to bcrypt, http, or other native modules, never return.

This issue is intermittent and hard to reproduce, there can be many calls to bcrypt.compare before one fails. 

I have confirmed that this module is responsible by removing it and replacing it with `bcryptjs`, which causes the issue to go away.

bcrypt version: 5.0.0
NodeJS 14.15.4 LTS, Gentoo Linux AMD64

Additional information: Previously the application was running on `14.4.0` for several weeks without incident.

**Comment by recrsn** [comment]
Is it possible that the password you were comparing was having rounds like 15/20?

You should be able to find them by looking at the `$2y$<rounds>...` part in the db?

**Comment by TomMettam** [comment]
I ran a query to check all our stored password fields. They all have a rounds value of `13`.

**Comment by recrsn** [comment]
Were you using one of the pre-built binaries or compiling bcrypt from source. 

This can be a very tricky thing to debug.

**Comment by TomMettam** [comment]
Sometimes only after 3 or 4, sometimes after 300, it's incredibly erratic.

From my logs it looks like it only occurs when there are multiple concurrent requests.

I currently suspect that the issue may be in `libuv`, i'm running some tests to confirm.

**Comment by TomMettam** [comment]
Well, i was able to reproduce the issue without this module installed, although it's much harder to repro. So you can close this - sorry to bother!

**Comment by recrsn** [comment]
Good luck with your debugging!

Just sharing one incident which may be relevant, check if you are breaching the thread-count limit on your VM (if its Kubernetes, anywhere on the node, a single bad pod can bring down all other pods on the same node). I had this experience where NodeJS and Go scheduler went to a spin-loop because they were unable to create more threads. Some misbehaving pod was creating a lot of threads.
