### ISSUE TITLE
Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found

### ISSUE THREAD

**Issue by DannyThomas2** [kelektiv/node.bcrypt.js#863]
Hey, 

So today I was building my nodejs/react project to get ready for production and I'm running into this issue:

![image](https://user-images.githubusercontent.com/69470156/109536804-28981e00-7a8c-11eb-9aa0-2acca0da8b17.png)

npm install goes through with no problems, but this error pops up when starting the app.

**Comment by mewelling** [comment]
this fixed that issue for me on ubuntu 14.04. Not sure what caused it, but feels like it should have been a major version change.
```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install gcc-4.9 g++-4.9
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9```

**Comment by mgara** [comment]
Hello,
I have different environments between the develop env and the ECS.

the bcrypt_lib.node is compiled against GCC 4.9 ....
Thanks !

**Comment by DannyThomas2** [comment]
Hey,

I ran this command after the npm installs and it works after, 

`npm rebuild bcrypt --build-from-source`

Its kinda cumbersome to have to keep entering that command afterwards, will there be an update that fixes this issue?

**Comment by recrsn** [comment]
This is a bug. Thanks for bringing it to my attention. It has something to do with the CI. (The base image for Travis is now Xenial perhaps)

We support base RHEL7/CentOS 7 which comes with GCC 4.8.5 

I'll recompile and reupload the binaries manually and see what can be done about the CI

I'll recompile and

**Comment by felixmosh** [comment]
I'm having the same issue on CentOS 7, this is a breaking change and the version bump of `node-pre-gyp` was released as patch version.

Maybe it is better to release a patch which rolls back it?

**Comment by panga** [comment]
Hit the same issue. BCrypt 5.0.1 fails with Ubuntu 14.04.

**Comment by recrsn** [comment]
I have pulled the release for now. Everyone needs to do a source compile. 

I will upload a new binary compiled on CentOS7 tomorrow

**Comment by recrsn** [comment]
This is done

**Comment by hardmaster92** [comment]
After upgrading to the latest v.5.1.0 this issue started appearing again (CentOS 7)

**Comment by recrsn** [comment]
New binaries compatible with CentOS 7 are up
