### ISSUE TITLE
bcrypt_lib-v5.0.1-napi-v3-linux-x64-glibc.tar.gz is not found 

### ISSUE THREAD

**Issue by m-doi2** [kelektiv/node.bcrypt.js#864]
It seems that bcrypt_lib-v5.0.1-napi-v3-linux-x64-glibc.tar.gz has not been uploaded as Assets.
Due to that, when I try to install v5.0.1 on linux OS (Ubuntu 20.04) I get an error.

<img width="801" alt="screenshot" src="https://user-images.githubusercontent.com/6340506/110280793-c789c080-801e-11eb-9c08-d01c8acf9dd9.png">

```sh
[4/4] Building fresh packages...
[-/16] ⠄ waiting...
[-/16] ⠄ waiting...
[-/16] ⠄ waiting...
[4/16] ⠄ bcrypt
error /path/to/packages/api/node_modules/bcrypt: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments: 
Directory: /path/to/packages/api/node_modules/bcrypt
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.0
node-pre-gyp info using node@14.16.0 | linux | x64
node-pre-gyp info check checked for "/path/to/packages/api/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node" (not found)
node-pre-gyp http GET https://github.com/kelektiv/node.bcrypt.js/releases/download/v5.0.1/bcrypt_lib-v5.0.1-napi-v3-linux-x64-glibc.tar.gz
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/kelektiv/node.bcrypt.js/releases/download/v5.0.1/bcrypt_lib-v5.0.1-napi-v3-linux-x64-glibc.tar.gz 
node-pre-gyp WARN Pre-built binaries not installable for bcrypt@5.0.1 and node@14.16.0 (node-v83 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/kelektiv/node.bcrypt.js/releases/download/v5.0.1/bcrypt_lib-v5.0.1-napi-v3-linux-x64-glibc.tar.gz 
```

\* I am using the workspace feature for yarn v1.

Is this the intended behavior and do I need to do any additional work?

**Comment by mukeshgupta** [comment]
> bcrypt@5.0.1 install /app/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

[91mnode-pre-gyp[0m[91m [0m[91mERR![0m[91m [0m[91minstall response status 404 Not Found on https://github.com/kelektiv/node.bcrypt.js/releases/download/v5.0.1/bcrypt_lib-v5.0.1-napi-v3-linux-x64-glibc.tar.gz[0m[91m 
[0m[91mnode-pre-gyp[0m[91m [0m[91mWARN[0m[91m [0m[91mPre-built binaries not installable for bcrypt@5.0.1 and node@14.16.0 (node-v83 ABI, glibc) (falling back to source compile with node-gyp)[0m[91m 
[0m[91mnode-pre-gyp[0m[91m [0m[91mWARN[0m[91m [0m[91mHit error response status 404 Not Found on https://github.com/kelektiv/node.bcrypt.js/releases/download/v5.0.1/bcrypt_lib-v5.0.1-napi-v3-linux-x64-glibc.tar.gz[0m[91m 
[0m[91mgyp[0m[91m [0m[91mERR![0m[91m [0m[91mfind Python[0m[91m 
[0m[91mgyp[0m[91m [0m[91mERR![0m[91m [0m[91mfind Python[0m[91m Python is not set from command line or npm configuration
[0m[91mgyp[0m[91m [0m[91mERR![0m[91m [0m[91mfind Python[0m[91m Python is not set from environment variable PYTHON
[0m[91mgyp[0m[91m [0m[91mERR![0m[91m [0m[91mfind Python[0m[91m checking if "python" can be used
[0m[91mgyp[0m[91m [0m[91mERR![0m[91m [0m[91mfind Python[0m[91m - "python" is not in PATH or produced an error
[0m[91mgyp[0m[91m [0m[91mERR![0m[91m [0m[91mfind Python[0m[91m checking if "python2" can be used
[0m[91mgyp[0m[91m [0m[91mERR![0m[91m [0m[91mfind Python[0m[91m - "python2" is not in PATH or produced an error
[0m[91mgyp[0m[91m [0m[91mERR![0m[91m [0m[91mfind Python[0m[91m checking if "python3" can be used
[0m[91mgyp[0m[91m [0m[91mERR![0m[91m [0m[91mfind Python[0m[91m - "python3" is not in PATH or produced an error
[0m[91mgyp[0m[91m [0m[91mERR![0m[91m [0m[91mfind Python[0m[91m 
[0m[91mgyp[0m[91m [0m[91mERR![0m[91m [0m[91mfind Python[0m[91m **********************************************************
[0m[91mgyp[0m[91m [0m[91mERR![0m[91m [0m[91mfind Python[0m[91m You need to install the latest version of Python.
[0m[91mgyp[0m[91m [0m[91mERR![0m[91m [0m[91mfind Python[0m[91m Node-gyp should be able to find and use Python. If not,
[0m[91mgyp[0m[91m [0m[91mERR![0m[91m [0m[91mfind Python[0m[91m you can try one of the following options:
[0m[91mgyp[0m[91m [0m[91mERR![0m[91m [0m[91mfind Python[0m[91m - Use the switch --python="/path/to/pythonexecutable"
[0m[91mgyp[0m[91m [0m[91mERR![0m[91m [0m[91mfind Python[0m[91m   (accepted by both node-gyp and npm)
[0m[91mgyp[0m[91m [0m[91mERR![0m[91m [0m[91mfind Python[0m[91m - Set the environment variable PYTHON
[0m[91mgyp[0m[91m [0m[91mERR![0m[91m [0m[91mfind Python[0m[91m - Set the npm configuration variable python:
[0m[91mgyp[0m[91m [0m[91mERR![0m[91m [0m[91mfind Python[0m[91m   npm config set python "/path/to/pythonexecutable"
[0m[91mgyp[0m[91m [0m[91mERR![0m[91m [0m[91mfind Python[0m[91m For more information consult the documentation at:
[0m[91mgyp[0m[91m [0m[91mERR![0m[91m [0m[91mfind Python[0m[91m https://github.com/nodejs/node-gyp#installation
[0m[91mgyp[0m[91m [0m[91mERR![0m[91m [0m[91mfind Python[0m[91m **********************************************************
[0m[91mgyp[0m[91m [0m[91mERR![0m[91m [0m[91mfind Python[0m[91m 
[0m[91mgyp[0m[91m [0m[91mERR![0m[91m [0m[91mconfigure error[0m[91m 
[0m[91mgyp[0m[91m [0m[91mERR![0m[91m [0m[91mstack[0m[91m Error: Could not find any Python installation to use
[0m[91mgyp[0m[91m [0m[91mERR![0m[91m [0m[91mstack[0m[91m     at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:307:47)
[0m[91mgyp[0m[91m [0m[91mERR![0m[91m [0m[91mstack[0m[91m     at PythonFinder.runChecks (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:136:21)
[0m[91mgyp[0m[91m [0m[91mERR![0m[91m [0m[91mstack[0m[91m     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:179:16)
[0m[91mgyp[0m[91m [0m[91mERR![0m[91m [0m[91mstack[0m[91m     at PythonFinder.execFileCallback (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:271:16)
[0m[91mgyp[0m[91m [0m[91mERR![0m[91m [0m[91mstack[0m[91m     at exithandler (child_process.js:315:5)
[0m[91mgyp[0m[91m [0m[91mERR![0m[91m [0m[91mstack[0m[91m     at ChildProcess.errorhandler (child_process.js:327:5)
[0m[91mgyp[0m[91m [0m[91mERR![0m[91m [0m[91mstack[0m[91m     at ChildProcess.emit (events.js:315:20)
[0m[91mgyp[0m[91m [0m[91mERR![0m[91m [0m[91mstack[0m[91m     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
[0m[91mgyp[0m[91m [0m[91mERR![0m[91m [0m[91mstack[0m[91m     at onErrorNT (internal/child_process.js:465:16)
[0m[91mgyp[0m[91m [0m[91mERR![0m[91m [0m[91mstack[0m[91m     at processTicksAndRejections (internal/process/task_queues.js:80:21)
[0m[91mgyp[0m[91m [0m[91mERR![0m[91m [0m[91mSystem[0m[91m Linux 4.19.78-coreos
[0m[91mgyp[0m[91m [0m[91mERR![0m[91m [0m[91mcommand[0m[91m "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/app/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/app/node_modules/bcrypt/lib/binding/napi-v3" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
[0m[91mgyp[0m[91m [0m[91mERR![0m[91m [0m[91mcwd[0m[91m /app/node_modules/bcrypt
[0m[91mgyp[0m[91m [0m[91mERR![0m[91m [0m[91mnode -v[0m[91m v14.16.0
[0m[91mgyp[0m[91m [0m[91mERR![0m[91m [0m[91mnode-gyp -v[0m[91m v5.1.0
[0m[91mgyp[0m[91m [0m[91mERR![0m[91m [0m[91mnot ok[0m[91m 
[0m[91mnode-pre-gyp[0m[91m [0m[91mERR![0m[91m [0m[91mbuild error[0m[91m 
[0m[91mnode-pre-gyp[0m[91m [0m[91mERR![0m[91m [0m[91mstack[0m[91m Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/app/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/app/node_modules/bcrypt/lib/binding/napi-v3 --napi_version=7 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
[0m[91mnode-pre-gyp[0m[91m [0m[91mERR![0m[91m [0m[91mstack[0m[91m     at ChildProcess.<anonymous> (/app/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
[0m[91mnode-pre-gyp[0m[91m [0m[91mERR![0m[91m [0m[91mstack[0m[91m     at ChildProcess.emit (events.js:315:20)
[0m[91mnode-pre-gyp[0m[91m [0m[91mERR![0m[91m [0m[91mstack[0m[91m     at maybeClose (internal/child_process.js:1048:16)
[0m[91mnode-pre-gyp[0m[91m [0m[91mERR![0m[91m [0m[91mstack[0m[91m     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
[0m[91mnode-pre-gyp[0m[91m [0m[91mERR![0m[91m [0m[91mSystem[0m[91m Linux 4.19.78-coreos
[0m[91mnode-pre-gyp[0m[91m [0m[91mERR![0m[91m [0m[91mcommand[0m[91m "/usr/local/bin/node" "/app/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
[0m[91mnode-pre-gyp[0m[91m [0m[91mERR![0m[91m [0m[91mcwd[0m[91m /app/node_modules/bcrypt
[0m[91mnode-pre-gyp[0m[91m [0m[91mERR![0m[91m [0m[91mnode -v[0m[91m v14.16.0
[0m[91mnode-pre-gyp[0m[91m [0m[91mERR![0m[91m [0m[91mnode-pre-gyp -v[0m[91m v1.0.0
[0m[91mnode-pre-gyp[0m[91m [0m[91mERR![0m[91m [0m[91mnot ok[0m[91m 
[0mFailed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/app/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/app/node_modules/bcrypt/lib/binding/napi-v3 --napi_version=7 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
[91mnpm[0m[91m [0m[91mWARN[0m[91m [0m[91moptional[0m[91m SKIPPING OPTIONAL DEPENDENCY: fsevents@^2.1.2 (node_modules/jest-haste-map/node_modules/fsevents):
[0m[91mnpm[0m[91m [0m[91mWARN[0m[91m [0m[91mnotsup[0m[91m SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
[0m[91mnpm[0m[91m [0m[91mWARN[0m[91m [0m[91moptional[0m[91m SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/chokidar/node_modules/fsevents):
[0m[91mnpm[0m[91m [0m[91mWARN[0m[91m [0m[91mnotsup[0m[91m SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
[0m[91m

**Comment by mukeshgupta** [comment]
Same issue at my end also on GItlab CI-CD run

**Comment by recrsn** [comment]
@m-doi2 See https://github.com/kelektiv/node.bcrypt.js/issues/863

The pre-compiled binary that was uploaded was bad and was breaking RHEL/CentOS 7 users and pre-18.04 Ubuntu users, it has been removed for now. I'll publish a compiled binary shortly. Till then you need

https://github.com/kelektiv/node.bcrypt.js/wiki/Installation-Instructions

**Comment by recrsn** [comment]
This should be fixed now
