### ISSUE TITLE
Issue with installing bcrypt with npm

### ISSUE THREAD

**Issue by AmitAshton** [kelektiv/node.bcrypt.js#866]
I want to install bcrypt through npm but there was an error, my node version is 14.16.0(LTS) and I already installed npm in my project
the error:

npm ERR! code EPERM
npm ERR! syscall rename
npm ERR! path C:\Users\amita\Desktop\Development\Secrets - Starting Code\node_modules\mkdirp\package.json.3361226568
npm ERR! dest C:\Users\amita\Desktop\Development\Secrets - Starting Code\node_modules\mkdirp\package.json
npm ERR! errno -4048
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\amita\Desktop\Development\Secrets - Starting Code\node_modules\mkdirp\package.json.3361226568' -> 'C:\Users\amita\Desktop\Development\Secrets - Starting Code\node_modules\mkdirp\package.json'
npm ERR!  [OperationalError: EPERM: operation not permitted, rename 'C:\Users\amita\Desktop\Development\Secrets - Starting Code\node_modules\mkdirp\package.json.3361226568' -> 'C:\Users\amita\Desktop\Development\Secrets - Starting Code\node_modules\mkdirp\package.json'] {
npm ERR!   cause: [Error: EPERM: operation not permitted, rename 'C:\Users\amita\Desktop\Development\Secrets - Starting Code\node_modules\mkdirp\package.json.3361226568' -> 'C:\Users\amita\Desktop\Development\Secrets - Starting Code\node_modules\mkdirp\package.json'] {
npm ERR!     errno: -4048,
npm ERR!     code: 'EPERM',
npm ERR!     syscall: 'rename',
npm ERR!     path: 'C:\\Users\\amita\\Desktop\\Development\\Secrets - Starting Code\\node_modules\\mkdirp\\package.json.3361226568',
npm ERR!     dest: 'C:\\Users\\amita\\Desktop\\Development\\Secrets - Starting Code\\node_modules\\mkdirp\\package.json'
npm ERR!   },
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path: 'C:\\Users\\amita\\Desktop\\Development\\Secrets - Starting Code\\node_modules\\mkdirp\\package.json.3361226568',
npm ERR!   dest: 'C:\\Users\\amita\\Desktop\\Development\\Secrets - Starting Code\\node_modules\\mkdirp\\package.json',
npm ERR!   parent: 'Secrets - Starting Code'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\amita\AppData\Roaming\npm-cache\_logs\2021-04-03T14_30_54_921Z-debug.log

Thanks for helping!

**Comment by recrsn** [comment]
Looks like you have a space in the folder. It's an unfortunate restriction by node-gyp/npm on windows. 

Rename the folder "Secrets - Starting Code" to one without spaces 

Also I see the same question popup everytime is it from some MOOC / online course?

**Comment by AmitAshton** [comment]
> Looks like you have a space in the folder. It's an unfortunate restriction by node-gyp/npm on windows.
> 
> Rename the folder "Secrets - Starting Code" to one without spaces
> 
> Also I see the same question popup everytime is it from some MOOC / online course?

It worked!  thanks.
yah its from a web development course in Udemy
