### ISSUE TITLE
Cannot bundle bcrypt

### ISSUE THREAD

**Issue by carlgieringer** [kelektiv/node.bcrypt.js#874]
Hi,

I'm trying to bundle a node application that includes bcrypt. I am having a problem bundling bcrypt. I am using esbuild because it's quick and easy, but I think that the issue exists with any bundling solution (webpack, etc.)

I have a repro repo: https://github.com/carlgieringer/bcrypt-bundle-issue

My environment:
node v14.16.0
macOS 10.15.7

The README in the repo explains the repro steps, but basically if you build and then try and run the bundled app, it fails on [bcrypt.js:5](https://github.com/kelektiv/node.bcrypt.js/blob/d98e2ae8f8f6c5b62d8bedec6f2ab0aa49ea6639/bcrypt.js#L5) where it passes in a path to package.json.  For one, this would fail if I was trying to run the app in a directory lacking a package.json. But what happens in that repo is that node-pre-gyp complains that the package.json (the one for my example repo) is missing required fields:

```
package.json must declare these properties:
binary
```

Thanks!

**Comment by carlgieringer** [comment]
I think I can replace `bcrypt` wiith `bcryptjs` to solve this.

**Comment by recrsn** [comment]
Native nodejs modules cannot be bundled. We won't be able to fix this issue ever

**Comment by Bessonov** [comment]
> Native nodejs modules cannot be bundled. We won't be able to fix this issue ever

Of course, they can be bundled, and there are already many heavyweight modules with native parts, like [sharp](https://www.npmjs.com/package/sharp). Sharp even works on AWS Lambda.

In fact, I got `bcrypt` working with a workaround: https://github.com/mapbox/node-pre-gyp/issues/308#issuecomment-2511480221.

Therefore, I propose to reopen the issue.
