### ISSUE TITLE
ERR node-pre-gyp install --fallback-to-build

### ISSUE THREAD

**Issue by nikishh** [kelektiv/node.bcrypt.js#880]
npm ERR! code 1
npm ERR! path C:\Users\Nikish\WebD\Secrets-Starting-Code\node_modules\bcrypt
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build     
npm ERR! '"node"' is not recognized as an internal or external command,
npm ERR! operable program or batch file.

**Comment by recrsn** [comment]
Check if node is available in your path. It's a system configuration issue
