### ISSUE TITLE
npm ERR! bcrypt@5.0.1 install: `node-pre-gyp install --fallback-to-build`

### ISSUE THREAD

**Issue by tangtaoshadow** [kelektiv/node.bcrypt.js#884]
> bcrypt@5.0.1 install /root/edumeet-3.4.0/server/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Pre-built binaries not installable for bcrypt@5.0.1 and node@12.6.0 (node-v72 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error ENOENT: no such file or directory, mkdir
gyp WARN EACCES user "undefined" does not have permission to access the dev dir "/root/.node-gyp/12.6.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/root/edumeet-3.4.0/server/node_modules/bcrypt/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/root/edumeet-3.4.0/server/node_modules/bcrypt/.node-gyp'
gyp ERR! System Linux 4.18.0-301.1.el8.x86_64
gyp ERR! command "/root/node-v12.6.0-linux-x64/bin/node" "/root/node-v12.6.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/root/edumeet-3.4.0/server/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/root/edumeet-3.4.0/server/node_modules/bcrypt/lib/binding/napi-v3" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3" "--python=python2"
gyp ERR! cwd /root/edumeet-3.4.0/server/node_modules/bcrypt
gyp ERR! node -v v12.6.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/root/node-v12.6.0-linux-x64/bin/node /root/node-v12.6.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/root/edumeet-3.4.0/server/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/root/edumeet-3.4.0/server/node_modules/bcrypt/lib/binding/napi-v3 --napi_version=4 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3 --python=python2' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/root/edumeet-3.4.0/server/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Linux 4.18.0-301.1.el8.x86_64
node-pre-gyp ERR! command "/root/node-v12.6.0-linux-x64/bin/node" "/root/edumeet-3.4.0/server/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /root/edumeet-3.4.0/server/node_modules/bcrypt
node-pre-gyp ERR! node -v v12.6.0
node-pre-gyp ERR! node-pre-gyp -v v1.0.5
node-pre-gyp ERR! not ok
Failed to execute '/root/node-v12.6.0-linux-x64/bin/node /root/node-v12.6.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/root/edumeet-3.4.0/server/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/root/edumeet-3.4.0/server/node_modules/bcrypt/lib/binding/napi-v3 --napi_version=4 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3 --python=python2' (1)
npm WARN ws@7.4.6 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.4.6 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@5.0.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@5.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-07-17T03_03_13_776Z-debug.log

## ENV 
```shell
centos 8
[root@localhost server]# node -v
v12.6.0
[root@localhost server]# npm -v
6.9.0
```

**Comment by recrsn** [comment]
Retry npm install with npm install --unsafe-perm

**Comment by tangtaoshadow** [comment]
Thanks 😇
