### ISSUE TITLE
please support usage with import, not just require

### ISSUE THREAD

**Issue by mariusa** [kelektiv/node.bcrypt.js#892]
README mentions usage only with `require`
As some projects are moving to using `import` instead, would you please support usage with `import` as well, for node 16.x?

**Comment by recrsn** [comment]
Should the import does not work with the CommonJS interop already?

**Comment by mariusa** [comment]
Could you please add to README how to use `import`?

**Comment by perry-mitchell** [comment]
Works fine for me with import:

```typescript
import bcrypt from "bcrypt";

// later
await bcrypt.compare(password, hash);
```
