### ISSUE TITLE
1 vulnerabilities found - bcrypt > mapbox/node-pre-gyp

### ISSUE THREAD

**Issue by 4lessandrodev** [kelektiv/node.bcrypt.js#897]
# bcrypt > @mapbox/node-pre-gyp >

Inefficient Regular Expression Complexity in chalk/ansi-regex

Package: ansi-regex

Update dependency please

**Comment by hensansi** [comment]
Got the same alert through dependabot, I created this PR in the meanwhile to reduce the attrition in the update.
https://github.com/kelektiv/node.bcrypt.js/pull/904
