### ISSUE TITLE
Is there a way of changing the hash algorithm from `$2a$` to `$2b$`

### ISSUE THREAD

**Issue by opticSquid** [kelektiv/node.bcrypt.js#900]
Whenever I create a hash with bcrypt it uses `$2a$` as hash algorithm identifier. While going through the readme file I found out it can also have `$2b$` as hash algorithm identifier. Is there any explicit way to tell bcrypt to use `$2b$` instead of `$2a$` while creeating hashes.

**Comment by recrsn** [comment]
You are probably using a very old version of bcrypt. Never versions default to $2b2$

**Comment by opticSquid** [comment]
If then also can we customize the begining of the hash
