### ISSUE TITLE
 Error: data must be a string or Buffer and salt must either be a salt string or a number of rounds

### ISSUE THREAD

**Issue by LishuGupta652** [kelektiv/node.bcrypt.js#903]
It took me a while to figure out while this error was comming up. I tried to fix and searched a lot and finally came up with the solution that the salt created with `bcrypt.gensalt(10)` returned a string value but when i input the salt in `bcrypt.hash(pass, salt)` it required me to input the salf as integer

final solution should be 
using salt as a intenger 
`bcrypt.hash(pass, parseInt(salt))`

**Comment by headkaze** [comment]
Just use `bcrypt.hash(pass, 10)`

**Comment by DamithaPerera** [comment]
This works for me.

`let pass= pass.toString();
bcrypt.hash(pass, 10);`

**Comment by chineduG** [comment]
This also works.


let pass= pass.toString();
bcrypt.hash(pass, parseInt(salt));

**Comment by LishuGupta652** [comment]
Thank you all this issue is now been resolved

**Comment by iragena25egide** [comment]
> It took me a while to figure out while this error was comming up. I tried to fix and searched a lot and finally came up with the solution that the salt created with `bcrypt.gensalt(10)` returned a string value but when i input the salt in `bcrypt.hash(pass, salt)` it required me to input the salf as integer
> 
> final solution should be using salt as a intenger `bcrypt.hash(pass, parseInt(salt))`

thank you

**Comment by piyushrai7271** [comment]
bcrypt.compair(password.toString(),this.password) // this work for me in compairing password while login user ... thanks everyone for help
