### ISSUE TITLE
Binaries missing for linux arm64 (docker on M1 Mac)

### ISSUE THREAD

**Issue by grit96** [kelektiv/node.bcrypt.js#917]
Installing the module inside docker on an M1 Mac fails due to missing binaries at the URL https://github.com/kelektiv/node.bcrypt.js/releases/download/v5.0.1/bcrypt_lib-v5.0.1-napi-v3-linux-arm64-glibc.tar.gz.

I can see on the [releases](https://github.com/kelektiv/node.bcrypt.js/releases) page that the darwin arm64 binary exists, but not the linux arm64 binary.

**Comment by SamuelMS** [comment]
Can confirm; build works on the M1 host but not within Docker. Downgrading to `5.0.0` solves the issue.

**Comment by grit96** [comment]
The irony is that 5.0.0 doesn't have the darwin arm64 binaries uploaded so the build fails on the M1 host 🤷‍♂️

**Comment by elisap360** [comment]
Hello, did you find a workaround for this issue ?

**Comment by grit96** [comment]
I have version 5.0.1 in my package.json for use on macOS (M1 and x86) and put the following line in my Dockerfile.

```
RUN npm install bcrypt@5.0.0
```

**Comment by elisap360** [comment]
Ok thanks !

**Comment by pyc2invent** [comment]
similarly, docker failed to build for 5.0.1 due to:
`https://github.com/kelektiv/node.bcrypt.js/releases/download/v5.0.1/bcrypt_lib-v5.0.1-napi-v3-linux-arm64-musl.tar.gz`
being missing from the release.

**Comment by adam-ludgate** [comment]
Any idea as to why 5.0.1 never got a linux arm64 build?

**Comment by pearnold** [comment]
When using an image from dockerhub, i worked around the issue by building it using this file:

```Dockerfile
FROM josephdadams/tallyarbiter:latest

RUN apk add --no-cache make gcc g++ python3 && \
    npm rebuild bcrypt --build-from-source && \
    apk del make gcc g++ python3
```
Replace "josephdadams/tallyarbiter:latest" with your source image.

**Comment by fdelucchijr** [comment]
> ```dockerfile
> FROM josephdadams/tallyarbiter:latest
> 
> RUN apk add --no-cache make gcc g++ python3 && \
>     npm rebuild bcrypt --build-from-source && \
>     apk del make gcc g++ python3
> ```
@pearnold  I use this same command in order to execute bcrypt in docker, but it isn’t an elegant way because adds a lot of time into the build process. Is anyone using a more productive method? One idea I have was to upload a node image based in alpine with bcrypt already preinstaled and builded, but I haven’t had the time to do it in a more elegant way than only building a section of my dockerfile.

Please, any idea is welcomed. I even doubted if maybe it was better to move into something like Ory Kratos (ignoring at all that the project is still in MVP state) 🤣.

**Comment by rfc2119** [comment]
As @adam-ludgate said, any idea why v5.0.1 did not get an arm64 build ?

**Comment by ramonpaolo** [comment]
same problem here

**Comment by TeemuKoivisto** [comment]
It's almost funny how such a crucial package is broken due to a missing release and the best fix is to pin the version.

**Comment by recrsn** [comment]
The best fix is to compile yourself. 

The lack of CI infrastructure and the inability of me to get an ARM machine. Travis provided arm64 machines in the past during the 5.0 release but now they don't work anymore. Binaries were always best-effort basis.

 The only decent ones are macs right now and I live in a country where it's not particularly cheap to get one (more than a month's salary, even after having top-of-the-market pay)

**Comment by pketh** [comment]
@recrsn Sorry to follow up on such an old thread, but if not being able to get an m1/m2 mac is still an issue for you, have you considered opening up github sponsorships? Soooo many people use/rely on this project and you definitely deserve something for all your work on this – especially if it helps enable something as helpful as native mac builds

**Comment by CTimmerman** [comment]
I read [bcryptjs](https://www.npmjs.com/package/bcryptjs) is a drop-in replacement which is cross-platform as it's written in a higher language.

**Comment by pketh** [comment]
oh that's v interesting , taking a look now. Are there performance implications of it being higher lvl?
