### ISSUE TITLE
New npm release?

### ISSUE THREAD

**Issue by ItzRabbs** [kelektiv/node.bcrypt.js#920]
Are there any plans to release a new build? One of the dependencies, specifically `@mapbox/node-pre-gyp`, has been updated from 1.0.0 to 1.0.7 in the latest release vs the master branch, respectively. There's a number of security alerts that will get resolve in my projects, and I imagine for others as well, with a new release.

**Comment by Kintori** [comment]
I'm also facing several security vulnerability scan alerts caused by this. Hoping bcrypt gets released/ master tagged soon...

**Comment by ItzRabbs** [comment]
@amitosh any update?
