### ISSUE TITLE
I am using node version 16.14.2 and my npm is at version 8.5.0 which is  LTS Recommended For Most Users but I am getting error in my device

### ISSUE THREAD

**Issue by AKASHPRADUM** [kelektiv/node.bcrypt.js#924]
PS C:\Users\Lenovo\Desktop\nodeJs\Authentication & Security\Secrets - Starting Code> npm i bcrypt
npm ERR! code 1
npm ERR! path C:\Users\Lenovo\Desktop\nodeJs\Authentication & Security\Secrets - Starting Code\node_modules\bcrypt
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build
npm ERR! The system cannot find the path specified.
npm ERR! node:internal/modules/cjs/loader:936
npm ERR!   ^
npm ERR!
s\@mapbox\node-pre-gyp\bin\node-pre-gyp'
npm ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
npm ERR!     at node:internal/main/run_main_module:17:47 {       
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: []
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lenovo\AppData\Local\npm-cache\_logs\2022-03-19T11_12_13_160Z-debug-0.log
PS C:\Users\Lenovo\Desktop\nodeJs\Authentication & Security\Secrets - Starting Code> node -v
v16.14.2
PS C:\Users\Lenovo\Desktop\nodeJs\Authentication & Security\Secrets - Starting Code> npm -v
8.5.0

[2022-03-19T11_12_13_160Z-debug-0.log](https://github.com/kelektiv/node.bcrypt.js/files/8309073/2022-03-19T11_12_13_160Z-debug-0.log)
0

**Comment by recrsn** [comment]
`Authentication & Security\Secrets - Starting Code` rename this part to remove spaces and special characters. I have seen this issue over and over again, please ask the course instructor to change it
