### ISSUE TITLE
npm warning 

### ISSUE THREAD

**Issue by aditya22062** [kelektiv/node.bcrypt.js#927]
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'parser@0.1.4',
npm WARN EBADENGINE   required: { node: '0.4-0.9' },
npm WARN EBADENGINE   current: { node: 'v16.15.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'tokenizer@1.1.2',
npm WARN EBADENGINE   required: { node: '0.10.x' },
npm WARN EBADENGINE   current: { node: 'v16.15.0', npm: '8.5.5' }
npm WARN EBADENGINE }

**Comment by drayilara** [comment]
What version of bcrypt are you install. It seems the node version you are using is not compatible with bcrypt. Run this command to install a more compatible version: npm install bcrypt@3.0.2

**Comment by recrsn** [comment]
Please use bcrypt@5.0.0 or higher
