### ISSUE TITLE
Is this project abandoned?  

### ISSUE THREAD

**Issue by MichaelTurbe** [kelektiv/node.bcrypt.js#937]
It hasn't been updated in a year and there are outstanding security vulnerabilities in its dependencies.  I believe there are PRs out there to fix that.  Is anyone able to get those pulled in and a successful release going, or should we move away from bcrypt entirely?

**Comment by ruckonic** [comment]
I see that now some developers are using the crypto module to encrypt the password [NodeJS](https://nodejs.org/dist/latest-v18.x/docs/api/crypto.html#cryptoscryptpassword-salt-keylen-options-callback)

**Comment by recrsn** [comment]
We just had a release, which removes many of the problematic dependencies we had
