### ISSUE TITLE
npm is not installiing the bcrypt

### ISSUE THREAD

**Issue by GitAryanCode** [kelektiv/node.bcrypt.js#941]
`npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! code 1
npm ERR! path E:\HP-DRIVE\Learning\Coding\FullStack Devolopment Course\Web Apps\Auth & Security - Secrets App\node_modules\bcrypt
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build
npm ERR! 'Security' is not recognized as an internal or external command,
npm ERR! operable program or batch file.
npm ERR! node:internal/modules/cjs/loader:936
npm ERR!   throw err;
npm ERR!   ^
npm ERR!
npm ERR! Error: Cannot find module 'E:\HP-DRIVE\Learning\Coding\FullStack Devolopment Course\Web Apps\node-pre-gyp\bin\node-pre-gyp'
npm ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
npm ERR!     at node:internal/main/run_main_module:17:47 {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: []
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\krish\AppData\Local\npm-cache\_logs\2022-06-23T13_52_53_797Z-debug-0.log`

**Comment by akashvpatel** [comment]
If you are still stuck in this problem, maybe this solution can help you.

E:\HP-DRIVE\Learning\Coding\FullStack Devolopment Course\Web Apps\Auth & Security - Secrets **App\node_modules\bcrypt**

from above directory remove "&" tag from the name (Auth & Security-Secrets App)

**Comment by GitAryanCode** [comment]
Thank you for your response, but I have fixed the problem with removing it
before. But again thank you for your support.

**Comment by recrsn** [comment]
Tracking it here: https://github.com/kelektiv/node.bcrypt.js/issues/961
