### ISSUE TITLE
npm not being able to find a file

### ISSUE THREAD

**Issue by Rahuljha5671** [kelektiv/node.bcrypt.js#942]
npm ERR! code ENOENT
npm ERR! syscall spawn cmd
npm ERR! path C:\Users\Manoj Jha\web\5_Authentication and security\Secrets - Starting Code\node_modules\bcrypt
npm ERR! errno -4058
npm ERR! enoent spawn cmd ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Manoj Jha\AppData\Local\npm-cache\_logs\2022-06-23T16_46_27_790Z-debug-0.log

**Comment by recrsn** [comment]
Tracking here https://github.com/kelektiv/node.bcrypt.js/issues/961
