### ISSUE TITLE
ERROR While trying to install

### ISSUE THREAD

**Issue by dadsec-dev** [kelektiv/node.bcrypt.js#945]
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/bycript - Not found     
npm ERR! 404 
npm ERR! 404  'bycript@3.0.6' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\a\AppData\Local\npm-cache\_logs\2022-07-13T18_24_25_601Z-debug-0.log

**Comment by shubhhxmxx** [comment]
Try : npm i bcrypt@latest
