### ISSUE TITLE
should the salt or round be stored in database?

### ISSUE THREAD

**Issue by Cariaga** [kelektiv/node.bcrypt.js#948]
const saltOrRounds = 10;
    const password = 'random_password';
    const hash = await bcrypt.hash(password, saltOrRounds);
    const salt = await bcrypt.genSalt();

**Comment by flowck** [comment]
Hi @Cariaga,
Not exactly, the salt fall in the category of config data for your system to work, therefore it's better suited stored as an environment variable.

The major drawback of storing in the db is the latency to retrieve it every time somebody tries to sign in or sign up.

For further reading, I recommend taking a look at this guide: https://12factor.net/

Cheers

**Comment by Cariaga** [comment]
thank you
flowck
