### ISSUE TITLE
USYNG REACT AND NODEJS, DEPENDECE ISSUES

### ISSUE THREAD

**Issue by edcodia** [kelektiv/node.bcrypt.js#949]
IM FACING THIS BUG WHEN INSTALLING DEPENDECES

Server % npm install bcryptjs dotenv express express-async-handle
r jsonwebtoken mongoose morgan
npm ERR! code E404
npm ERR! 404 Not Found - GET https://github.com/npm/npm-registry-couchapp/bcryptjs - Not Found
npm ERR! 404 
npm ERR! 404  'bcryptjs@*' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/eduardocodia/.npm/_logs/2022-08-26T17_00_54_666Z-debug-0.log
-de-Eduardo Server %

**Comment by recrsn** [comment]
This is not bcryptjs

**Comment by edcodia** [comment]
These are all dependence that I’m trying to install, even when I’m trying to install one by one I get the same bug, I tried to install the bcryptjs but it’s not working as well
