### ISSUE TITLE
Getting 504 status code

### ISSUE THREAD

**Issue by Tamir198** [kelektiv/node.bcrypt.js#950]
Hey, I pressed this link from the README:

![image](https://user-images.githubusercontent.com/34707669/187034334-e7407e3b-5acd-45a3-8025-4c92ad0e21d4.png)

And this is the result that was displayed on the screen:

![image](https://user-images.githubusercontent.com/34707669/187034359-a6b027ad-0bd4-407b-9c1d-2c5c43293cfc.png)

**Comment by recrsn** [comment]
david-dm.org is dead
