### ISSUE TITLE
Bcrypt 5.0.1 to 5.1.0 introduces breaking changes

### ISSUE THREAD

**Issue by peterver** [kelektiv/node.bcrypt.js#966]
Upgrading from 5.0.1 to 5.1.0 causes node pods to not boot up when running with a restrictive security context in docker on kubernetes.

According to the rules of semver a minor version change should not introduce breaking changes.

Expected behavior: 5.0.1 -> 5.1.0 upgrade should have been able to be done without introducing breaking changes. We're pinning the version to 5.0.1 for now.

![Screenshot from 2022-10-13 11-52-42](https://user-images.githubusercontent.com/821415/195565378-9101eee4-5207-4fde-8b22-f797c0f87470.png)

(screenshot is from k8s logs for the affected pods)

The security context attached to these pods is the following (HCL code):

```hcl
security_context {
    allow_privilege_escalation = false
    capabilities {
        drop = ["ALL"]
    }
    privileged = false
    run_as_non_root = true
    run_as_user = 1000
}
```

**Comment by recrsn** [comment]
This is a known issue

**Comment by stupkad** [comment]
see #965 for details
`chmod 774 <path>/bcrypt/lib/binding/napi-v3/bcrypt_lib.node` might help

**Comment by recrsn** [comment]
Is this still happening?

**Comment by lcdss** [comment]
> Is this still happening?

Yep, it just happened to me using the latest version of everything.
