### ISSUE TITLE
Fails in Next.js app/ directory incl. with API Route Handlers

### ISSUE THREAD

**Issue by karlhorky** [kelektiv/node.bcrypt.js#979]
# What went wrong?

Using `bcrypt` within a [Route Handler](https://beta.nextjs.org/docs/routing/route-handlers) in Next.js (API Route Handler within the new `app/` directory) causes the app to crash with unusual errors:

```
error - ./node_modules/@mapbox/node-pre-gyp/lib/util/nw-pre-gyp/index.html
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <!doctype html>
| <html>
| <head>

Import trace for requested module:
./node_modules/@mapbox/node-pre-gyp/lib/util/nw-pre-gyp/index.html
./node_modules/@mapbox/node-pre-gyp/lib/ sync ^\.\/.*$
./node_modules/@mapbox/node-pre-gyp/lib/node-pre-gyp.js
./node_modules/bcrypt/bcrypt.js
./app/api/route.ts
```

I also reported over here in the Next.js repo:

- https://github.com/vercel/next.js/issues/46493

# What did you expect to happen?

`bcrypt` should work in the `app/` directory, including in Route Handlers

# Which version of nodejs and OS?

```
    Operating System:
      Platform: linux
      Arch: x64
      Version: Ubuntu 20.04.0 LTS Mon Feb 27 2023 14:52:57 GMT+0100 (Central European Standard Time)
    Binaries:
      Node: 16.14.2
      npm: 7.17.0
      Yarn: 1.22.19
      pnpm: 7.13.6
    Relevant packages:
      next: 13.2.2-canary.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

# If you find a bug, please write a failing test.

Ok, maybe once I find out more.

**Comment by karlhorky** [comment]
Reading this issue in the `bcrypt` repo over here, it made me think that webpack maybe should not be used to try to bundle `bcrypt`... 🤔

- https://github.com/kelektiv/node.bcrypt.js/issues/874#issuecomment-833582766

So it occurred to me that maybe I should be using an `externals` webpack config and marking `bcrypt` as external:

`next.config.js`

```diff
/** @type {import('next').NextConfig} */
const nextConfig = {
  experimental: {
    appDir: true,
  },
+  webpack: (config) => {
+    config.externals = [...config.externals, 'bcrypt'];
+    return config;
+  },
};

module.exports = nextConfig;
```

Which indeed works (does not work on StackBlitz because the native module does run there):

CodeSandbox demo: https://codesandbox.io/p/sandbox/gracious-bose-wn2731?file=%2Fnext.config.js

![Screenshot 2023-02-27 at 16 11 48](https://user-images.githubusercontent.com/1935696/221603767-4df76e13-feb1-419c-81ab-94259412b78e.png)

**Comment by karlhorky** [comment]
Closing this out here and continuing the discussion over in the Next.js repo:

- https://github.com/vercel/next.js/issues/46493

**Comment by blazestudios23** [comment]
I tried that, I got this error:

```bash
./node_modules/next-auth/core/init.js (10:14)
Module not found: Can't resolve 'crypto'
```

**Comment by ibrahimullah12** [comment]
I had the same problem. The problem was solved by installing and importing. Instead of bcrypt install bcryptjs.
```
> npm i bcryptjs 

> npm i -D @types/bcryptjs
```

**Comment by decodehud** [comment]
I'm integrating authentication with nextauth v5 in nextjs 14.0.4 with prisma and I just got the error, I don't know, but bcryptjs worked instead of bcrypt

**Comment by breno404** [comment]
I'm a little scared to install bcryptjs because its last publication was 7 years ago and there are at least 40 issues open

**Comment by 0rogerinho** [comment]
This error happens when you run bcrypt on the client side, to correct it if you don't want to use it on the client side but the error is still returning, check that all the places where you are using bctypt have "use server"

**Comment by umair-mirza** [comment]
Issue is still not resolved with Next.js 14.0. Still getting the error while using Client component

**Comment by xcodewhisperer** [comment]
Same error with argon2. I'm looking for a workaround

**Comment by mohamed-younes16** [comment]
> I had the same problem. The problem was solved by installing and importing. Instead of bcrypt install bcryptjs.
> 
> ```
> > npm i bcryptjs 
> 
> > npm i -D @types/bcryptjs
> ```

thank you it worked

**Comment by razzededge** [comment]
> Same error with argon2. I'm looking for a workaround

I'm on the same boat... got error with argon2

**Comment by umair-mirza** [comment]
Finally got around the issue. Here how you can fix this:

First, in next.config.js

push bcrypt to config.externals like so:

```
  webpack: (config) => {
    config.externals = [...config.externals, "bcrypt"];
    return config;
  },
```

Then where ever you are using bcrypt, 

instead of importing it in the traditional way (import bcrypt from 'bcrypt')

You need to import it like so:

`const bcrypt = require("bcrypt");`

And make sure to put it above the line where it's being used. For example,

```
    const bcrypt = require("bcrypt");

    const hashedPassword = await bcrypt.hash(password, 12);
```

**Comment by token-ed** [comment]
@umair-mirza Thanks brother.

**Comment by udayprakash80** [comment]
Thanks @umair-mirza .. great man

**Comment by hariyebk** [comment]
@umair-mirza 🙏🏻

**Comment by Olaw2jr** [comment]
> I'm integrating authentication with nextauth v5 in nextjs 14.0.4 with prisma and I just got the error, I don't know, but bcryptjs worked instead of bcrypt

Could you let me know if you were able to get this resolved?

**Comment by mikhatanu** [comment]
Hello. i'm encountering this problem in next js 14 middleware. Any solution?

**Comment by nin-o** [comment]
For me the solution was to use:
`import { signIn } from 'next-auth/react';`
instead of:
`import { signIn } from '@/auth';`

**Comment by razzededge** [comment]
> For me the solution was to use: `import { signIn } from 'next-auth/react';` instead of: `import { signIn } from '@/auth';`

You will not get custom event handlers etc this way, also you are importing client side only code and @/auth means your custom auth implementation which you changed to one delivered with the next-auth package

**Comment by theogenejr** [comment]
Tried all solution. The one using `bcryptjs` instead of `bcrypt` worked just fine for me.
`npm i bcryptjs`
`npm i -D @types/bcryptjs`

**Comment by pulgueta** [comment]
Still have the same issue for bcrypt, argon2, @node-rs/bcrypt and @node-rs/argon2 on Next.js 14.2.3. Set the serverComponentExternalPackages for all 4 of these packages and the Webpack configuration but still no solution. Had to use bcryptjs for now.

**Comment by ezeparziale** [comment]
> I'm integrating authentication with nextauth v5 in nextjs 14.0.4 with prisma and I just got the error, I don't know, but bcryptjs worked instead of bcrypt

I replaced bcrypt with bcryptjs, and everything works okay.

Running with:
- nextauth 5.0.0-beta.17
- nextjs 14.1.3

**Comment by pulgueta** [comment]
> > I'm integrating authentication with nextauth v5 in nextjs 14.0.4 with prisma and I just got the error, I don't know, but bcryptjs worked instead of bcrypt
> 
> I replaced bcrypt with bcryptjs, and everything works okay.
> 
> Running with:
> 
> * nextauth 5.0.0-beta.17
> * nextjs 14.1.3

Me too. Used bcryptjs and works well but super slow.

**Comment by hoanglq** [comment]
Instead of using bcrypt, we should use bcryptjs.
Here is my approach, you can try to solve the issue:

```
//const bcrypt = require("bcrypt");
var bcrypt = require('bcryptjs');

//...your codes
//const passwordsMatch = await bcrypt.compare(password, user.password);
const passwordsMatch = await bcrypt.hashSync(password, user.password);
```

**Comment by muhammadkeyton** [comment]
Hey guys this is a known issue with bcrypt, bcrypt is a native module and when nextjs tries to import it in the client side, this error happens, a simple fix is to make the file where you are importing and using bcrypt to be a server file, add the ``` ' use server' ```  at the top,this should fix it, it worked for me

**Comment by ezeparziale** [comment]
> > > I'm integrating authentication with nextauth v5 in nextjs 14.0.4 with prisma and I just got the error, I don't know, but bcryptjs worked instead of bcrypt
> > 
> > 
> > I replaced bcrypt with bcryptjs, and everything works okay.
> > Running with:
> > 
> > * nextauth 5.0.0-beta.17
> > * nextjs 14.1.3
> 
> Me too. Used bcryptjs and works well but super slow.

After several attempts, I managed to get bcrypt working with auth.js v5.0.0-beta.17.

The key lies in performing the `bcrypt.compare` operation in the `auth.ts` file, where it operates without issues, as opposed to placing it within the `auth.config.ts` file, where it fails.

The auth.ts file must be with the {...authConfig +  providers}, this way it works 100% with bcrypt.

Example: https://github.com/ezeparziale/quark/blob/main/src/auth.ts

**Comment by mawiramawira** [comment]
> webpack: (config) => {
>     config.externals = [...config.externals, "bcrypt"];
>     return config;
>   },

works for @node-rs/argon2 as well

**Comment by drilon305** [comment]
For me problem solved: 'use server' instead of 'use client' in a component.

**Comment by Bro3Simon** [comment]
> This error happens when you run bcrypt on the client side, to correct it if you don't want to use it on the client side but the error is still returning, check that all the places where you are using bctypt have "use server"

Thanks, this helped me out!

**Scenario:** I moved my function that uses bycript to a utilities file that had both client and server functions. Even though I only ever called it on the server, it still produced the error during the build. 

**Fix:** I moved all server utility functions to their own file under the `api` folder. Since it only had server functions, I didn't need to use `use server` directive. Perhaps the file being under the `api` folder also has something to do with not needing the use `use server` directive.

**Comment by FranckWebPro** [comment]
> Finally got around the issue. Here's how you can fix this:
> 
> First, in next.config.js
> 
> push bcrypt to config.externals like so:
> 
> ```
>   webpack: (config) => {
>     config.externals = [...config.externals, "bcrypt"];
>     return config;
>   },
> ```
> 
> Then where ever you are using bcrypt,
> 
> instead of importing it in the traditional way (import bcrypt from 'bcrypt')
> 
> You need to import it like so:
> 
> `const bcrypt = require("bcrypt");`
> 
> And make sure to put it above the line where it's being used. For example,
> 
> ```
>     const bcrypt = require("bcrypt");
> 
>     const hashedPassword = await bcrypt.hash(password, 12);
> ```

Sadly I have an error which say "bcrypt is not defined" this way,   has anyone else encountered this issue?"

**Comment by ahmad-elshowair** [comment]
I was facing similar error: 
![image](https://github.com/user-attachments/assets/dfb151a2-ea65-40f4-b45d-97c10e0591b9)

### to solve I did the following:
- replace bcrypt with bcryptjs
- add the following code to next.config.mjs 
```
	webpack: (config) => {
		config.externals = [...config.externals, "bcrypt"];
		return config;
	},
```

**Comment by chriskuech** [comment]
Looks like the issue occurs if you have a middleware that indirectly references bcrypt (even though the middleware should be running on the server).

**Comment by BertramYe** [comment]
but what if I use the nextjs 15 rc with the turbo compiler, how can I config and use the bcrypt as the external dependencies? with the similar config of the ,
```tsx
webpack: (config) => {
		config.externals = [...config.externals, "bcrypt"];
		return config;
	},

```

**Comment by kulubaev** [comment]
in my case this issue was resolved putting 

` use server;` directive in the file where I used `bcrypt`
i believe the library intended used in server side not client
