### ISSUE TITLE
is there any problem?

### ISSUE THREAD

**Issue by manish828132** [kelektiv/node.bcrypt.js#990]
added 55 packages, and audited 198 packages in 28s

20 packages are looking for funding
  run `npm fund` for details

7 moderate severity vulnerabilities

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

**Comment by JackBailey** [comment]
You'd need to run `npm audit` to see specifically what the issues are and if they apply to your project but it's probably #988
