### ISSUE TITLE
Bcrypt generates same hashes for the diffrent input

### ISSUE THREAD

**Issue by Viktor-the-great** [kelektiv/node.bcrypt.js#996]
**What went wrong?**
Bcrypt generates same hashes for the input string with same start (more 71 symbols)

```javascript
    const salt = bcrypt.genSaltSync(10);
    let token1 = Array.from({ length: 71 }).reduce((res) => res + '_', '') + '1';
    let token2 = Array.from({ length: 71 }).reduce((res) => res + '_', '') + '2';
    console.log(bcrypt.hashSync(token1, salt) === bcrypt.hashSync(token2, salt)) // false

    token1 = Array.from({ length: 72 }).reduce((res) => res + '_', '') + '1';
    token2 = Array.from({ length: 72 }).reduce((res) => res + '_', '') + '2';
    console.log(bcrypt.hashSync(token1, salt) === bcrypt.hashSync(token2, salt)) // true
```

**What did you expect to happen?**
Bcrypt generates different hashes for the diffrent input with same start

**Which version of nodejs and OS?**
nodejs v18.12.1/ Ubuntu 20.04.6 LTS

**Comment by recrsn** [comment]
Bcrypt as per specification uses only first 72 bytes of the input.

**Comment by spetrac-nicos-ag** [comment]
But why does the hash function don't throw an error if the string length is too long for a reliable password check? I mean, that is the whole purpose of bcrypt after all. It's not like this is a general purpose hashing method to select bins for a string...
